src/api/socket.c

5
PR https://github.com/pi-hole/FTL/pull/1370 changed the telnet API error handling. It also logs when new telnet connections were made. However, the web interface makes a lot of connections via the API, all of them get logged. This creates logspam. 
This PR changes the behavior to only log if the debug flag is set.

Log new and terminating telnet connections only when debug flag is set

---

src/dnsmasq_interface.c

---
When querying special domains (such as `use-application-dns.net`), they are getting logged with status 16 (`Blocked (special domain)`). However, subsequent queries to the same domain incorrectly get status `OK (cached)`. This PR fixes these subsequent queries to also show status 16. This big is a mere displaying issue, blocking works as expected.
Thanks to @jpgpi250 for pointing this out.

Fix status of blocked special domains when they are in FTL's DNS cache

---

src/api/socket.c
src/daemon.c

---
Do not try to remove PID and PORT files as the user `pihole` cannot do this. Write permissions on the files themselves are only sufficient to truncate the files, removing them needs write permissions on the containing directory (/run) which isn't the case, usually.
This PR reverts pi-hole/FTL#1328

Revert "Remove PID and PORT file during shutdown"

---

src/database/shell.c
src/database/sqlite3.h

---
From the SQLite3 CHANGELOG:
1. Fix an incorrect result from a query that uses a view that contains a compound SELECT in which only one arm contains a RIGHT JOIN and where the view is not the first FROM clause term of the query that contains the view. [forum post 174afeae5734d42d](https://sqlite.org/forum/forumpost/174afeae5734d42d). 
2. Fix some harmless compiler warnings. 
3. Fix a long-standing problem with [ALTER TABLE RENAME](https://sqlite.org/lang_altertable.html#altertabrename) that can only arise if the [sqlite3_limit](https://sqlite.org/c3ref/limit.html)([SQLITE_LIMIT_SQL_LENGTH](https://sqlite.org/c3ref/c_limit_attached.html#sqlitelimitsqllength)) is set to a very …

Update SQLite3 from 3.39.0 to 3.39.2

---

.devcontainer/devcontainer.json
.gitignore

---
Adds a devcontainer, along with some suggested extensions for vscode - this should make it easier to build and test for those that, for example, are nervous about setting up the build and test dependencies - this "just works"
As its kind of related, I have also reworked the build script a little to take arguments at any position (except the -D* ones as I don't really know what to do about them)
I am not sure why the compiled binaries are not uploading here - I have rebuilt several times. I am not sure it's the build script changes as the commit before failed, too.

Add a Dev container

---

.github/workflows/build.yml
.github/workflows/codespell.yml
.github/workflows/stale.yml
.github/workflows/sync-back-to-dev.yml

10
---
Same as https://github.com/pi-hole/pi-hole/pull/4833

Explicit set minor and patch version on used actions

---

src/api/api.c
src/api/api.h
src/api/request.c
src/api/request.h
src/api/socket.c
src/api/socket.h
src/daemon.c
src/daemon.h
src/dnsmasq_interface.c
src/dnsmasq_interface.h
src/enums.h
src/syscalls/accept.c
src/syscalls/calloc.c
src/syscalls/fopen.c
src/syscalls/ftlallocate.c
src/syscalls/pthread_mutex_lock.c
src/syscalls/realloc.c
src/syscalls/recv.c
src/syscalls/recvfrom.c
src/syscalls/select.c
src/syscalls/sendto.c
src/syscalls/vasprintf.c
src/syscalls/vfprintf.c
src/syscalls/vsnprintf.c
src/syscalls/vsprintf.c
src/syscalls/write.c

---
Major rewrite of the socket processing routines of FTL's Telnet-like API.
Before, we launched a new thread for each incoming connection (more than 40 threads concurrent were never allowed) to handle incoming connections independent from another and serve content concurrently. However, this could potentially be used to DoS FTL by opening and closing telnet sessions in very quick succession.
The new behavior is to, instead, launch five (compile-time setting) threads per type (independent for telnet over IPv4, IPv6, and Unix socket communication = 15 threads in total). Each of them accepts incoming connections in a FIFO manner (they always pick the first connection in the waiting …

Major rewrite of the socket processing routines

---

src/api/api.c
src/api/api.h
src/api/request.c
src/api/request.h
src/api/socket.c
src/api/socket.h
src/daemon.c
src/daemon.h
src/database/common.h
src/dnsmasq_interface.c
src/dnsmasq_interface.h
src/enums.h
src/syscalls/accept.c
src/syscalls/calloc.c
src/syscalls/fopen.c
src/syscalls/ftlallocate.c
src/syscalls/pthread_mutex_lock.c
src/syscalls/realloc.c
src/syscalls/recv.c
src/syscalls/recvfrom.c
src/syscalls/select.c
src/syscalls/sendto.c
src/syscalls/vasprintf.c
src/syscalls/vfprintf.c
src/syscalls/vsnprintf.c
src/syscalls/vsprintf.c
src/syscalls/write.c

Fixes for https://github.com/pi-hole/PADD/issues/252 independent of other fixes in development
Original PR: https://github.com/pi-hole/FTL/pull/1396

Hotfix padd issues

---

src/api/socket.c

---
Don't fail hard when we cannot open all the telnet sockets (e.g., IPv6 is disabled on the kernel level).
This PR is meant to be opened against `master` for a hotfix.

Don't enforce API sockets

---

src/api/socket.c
src/daemon.c
src/daemon.h

---
Fixes calls to `pthread_cancel(0)` causing `musl`-based binaries to crash during shutdown. Fixes https://github.com/pi-hole/FTL/issues/1405

Fix storing of API thread IDs

---

.github/workflows/build.yml
deploy.sh

---
This PR improves the build&deploy process in two ways:
1) It adds a pre-build smoke-test that checks the depth of the git branch name. Everything with more than one subdir won't pass. E.g. `tweak/smoke-test` will pass, but `tweak/smoke-test/subfeature` won't.
2) It allows to create subdirs during the deploy process when transferring the binary to our `ftl` server. We use `sftp` to transfer the files securely, but `sftp's` `mkdir` does not have a `-p` option to create subdirs. Therefore, we loop over the target branch and create each subdir one-by-one.
This test will pass the GH action. The same code of the branch`twek/sftp/mkdir` won't pass - action output here: https://github.com/pi-hole/FTL/runs/7309991123?check_suite_focus=true

Tweak build and deploy process

---

src/syscalls/fopen.c
src/syscalls/syscalls.h

---
Add missing function attribute to syscall to ensure compatibility with gcc 11.2.0 (Ubuntu 11.2.0-19ubuntu1) which was installed on my main development system after the upgrade from Ubuntu 20.04.4 LTS to Ubuntu 22.04.1 LTS.
The function `FTLfopen()` is a wrapper around `fopen()` which is, in turn, equipped with the very same attribute:
https://github.com/bminor/glibc/blob/f7b0fc5cc61301461e3c1a278240ce78701bb9a8/libio/stdio.h#L256-L260
https://github.com/bminor/glibc/blob/d055481ce39d03652ac60de5078889e15b6917ff/misc/sys/cdefs.h#L277-L284

Ensure compatibility with gcc 11.2.0 (Ubuntu 11.2.0-19ubuntu1)

---

src/dnsmasq_interface.c
src/dnsmasq_interface.h

---
Substitute "." from empty domain names passed by `dnsmasq`. This PR extends the already existing facility from internally generated DNSSEC queries also to regular queries.

Substitute "." for empty domain names

---

.github/workflows/build.yml

title. Otherwise we need to manually attach from ftl.pi-hole.net

Attach binaries to release from the correct path

---

src/dnsmasq/forward.c
src/dnsmasq/rfc1035.c
src/dnsmasq_interface.c
src/dnsmasq_interface.h
test/gravity.db.sql
test/pdns/setup.sh
test/test_suite.bats

---
Improve deep `CNAME` inspection to also work on abandoned paths. The most obvious example for such a configuration is a `CNAME` child ending without a record (`NODATA`). See [FTL#1421](https://github.com/pi-hole/FTL/issues/1421).

Improve deep CNAME inspection

---

src/database/gravity-db.c
src/database/gravity-db.h
src/database/message-table.c
src/database/message-table.h
src/datastructure.c
src/dnsmasq_interface.c
src/enums.h
test/gravity.db.sql

**How familiar are you with the codebase?:** _10_
---
Adds a warning to the `message` table (Pi-hole diagnosis) if adlists have been inaccessible during the last gravity run. We already save `status` in the `adlists` table in the `gravity.db`. This status is set during the gravity run and indicates if the "download" was successful (https://docs.pi-hole.net/database/gravity/#adlist-table-adlist). Status type `3` and `4` indicate that the adlist was inaccessible. 
This PR checks on each `FTL` reload if `gravity.db` contains adlists with `status=[3,4]` (and are enabled) and adds a warning if applicable.
Corresponding web interface PR: https://github.com/pi-hole/AdminLTE/pull/2320
Discourse thread: …

Add warning about inaccessible adlists to message table (Pi-hole diagnosis)

---

CMakeLists.txt
src/dnsmasq/cache.c
src/dnsmasq/dbus.c
src/dnsmasq/dhcp-common.c
src/dnsmasq/dhcp-protocol.h
src/dnsmasq/dhcp.c
src/dnsmasq/dhcp6-protocol.h
src/dnsmasq/dhcp6.c
src/dnsmasq/dnsmasq.c
src/dnsmasq/dnsmasq.h
src/dnsmasq/dnssec.c
src/dnsmasq/domain-match.c
src/dnsmasq/domain.c
src/dnsmasq/dump.c
src/dnsmasq/forward.c
src/dnsmasq/hash-questions.c
src/dnsmasq/helper.c
src/dnsmasq/lease.c
src/dnsmasq/netlink.c
src/dnsmasq/network.c
src/dnsmasq/option.c
src/dnsmasq/poll.c
src/dnsmasq/radv.c
src/dnsmasq/rfc1035.c
src/dnsmasq/rfc2131.c
src/dnsmasq/rfc3315.c
src/dnsmasq/rrfilter.c
src/dnsmasq/tftp.c
src/dnsmasq/util.c

---
CHANGELOG entries since our last `dnsmasq` update:
```
Enhance --domain to accept, for instance,
--domain=net2.thekelleys.org.uk,eth2 so that hosts get a domain
which relects the interface they are attached to in a way which
doesn't require hard-coding addresses. Thanks to Sten Spans for
the idea.
Fix write-after-free error in DHCPv6 server code.
CVE-2022-0934 refers.
Add the ability to specify destination port in
DHCP-relay mode. This change also removes a previous bug
where --dhcp-alternate-port would affect the port used
to relay _to_ as well as the port being listened on.
The new feature allows configuration to provide bug-for-bug
compatibility, if required. Thanks to Damian …
```

Update embedded dnsmasq to v2.87rc1

---

src/gc.c

**How familiar are you with the codebase?:**  5
---
We check two locations for free disk space and warn if disk usage >90% (https://github.com/pi-hole/FTL/pull/1249). Warning consists of adding a message in the `message_table` and logging to `FTL.log`
One location we monitor is the filesystem where the log files are located. We already ensure that we only log to the message table once, however, we continue to log to `FTL.log` every time we check (300 sec). This leads to log spam which further decreases the available space for the log files. 
See this discourse thread with a log warning every 5 minutes: https://discourse.pi-hole.net/t/disk-shortage-var-log-pihole-ftl-log- …

Only log disk space warning when usage increased

---

src/dnsmasq_interface.c

The most recent FTL release contains `dnsmasq v2.87rc1` which causes a regression for `dnssec-retry` queries leading to a bug where FTL isn't able to interpret the query type as `DS`/`DNSKEY` and incorrectly infers `TYPE<upstream-port>` as query type:
(picture taken from related [Discourse topic](https://discourse.pi-hole.net/t/log-entry-for-dns-type-type5335-with-reply-of-blob/57908))
Subsequently, FTL fails to analyze the content of this query (as it doesn't know how to handle, e.g. `TYPE5335`) and simply logs `BLOB` as return type (= some unknown binary stuff).
It is worth pointing out that DNS blocking and internal DNSSEC verification still works fine making this a displaying …

Fix handling of dnssec-retry queries.

---

.github/workflows/build.yml

Reverts PR https://github.com/pi-hole/FTL/pull/1367 after discussion here: https://github.com/pi-hole/FTL/pull/1436.
We decided after all it would be a good idea to check dependabot PR.

Revert "Do not run built workflow on dependabot pushes and PRs"

---

.github/dependabot.yml

Our build workflow restricts the dir depth of the branch names to one subdir. This makes the built fail for dependabot as it creates deeper subdirs.
Working around this by:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#pull-request-branch-nameseparator

Separate dependabot branch names with a hypthen to work around the dir depth restriction in the build workflow

---

CMakeLists.txt
src/dnsmasq/forward.c

---
`dnsmasq` v2.87 has been released today: https://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2022q3/016599.html

Update embedded dnsmasq to v2.87

---

src/api/api.c
src/database/gravity-db.c
test/test_suite.bats

---
Fix https://github.com/pi-hole/FTL/issues/1435 by changing the audit log SQL query. This is necessary as https://github.com/pi-hole/FTL/pull/1409 deprecated using `SELECT EXISTS(...)` to get domain IDs. This PR also adds a test to ensure this cannot happen again and be unnoticed.

Fix audit log

---

src/database/gravity-db.c

5
---
In `gravity-db.c`, the comment explaining how the wildcard character works when adding audit domains is wrong. 
The text says `*google.de` matches other domains **starting** in `google.de`, like `abcgoogle.de`.
This is clearly wrong, since `abcgoogle.de` **ends** with the matching text.
The PR fixes the comment.

Fix comment on `gravity-db.c`

---

.github/workflows/build.yml

**How familiar are you with the codebase?:** _{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar} 10
---
Switch from https://github.com/shimataro/ssh-key-action to https://github.com/benoitchantre/setup-ssh-authentication-action
Reason: the current action uses `Node.js 12` which is not supported by GH anymore, makes the deploy workflow failing. Also, the action repo looks a bit abandoned, last release 1 year ago with some open issues and pull requests. One issue is about Nodejs …

Switch SSH deploy action

---

.github/workflows/build.yml

Github considers the `set-output` command to be deprecated https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This PR changes our `build.yml` to use the recommended environmental `$GITHUB_OUTPUT` instead of `set-output` (https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)

Remove deprecated set-output in build.yml

---

src/api/api.c
src/args.c
src/args.h
src/datastructure.c
src/datastructure.h

---
`gcc 12.1.0` has a [known bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=18487) with incorrect attribute suggestions preventing FTL to compile correctly. This has been reported for Alpine before (#1424). This bug made it also into  `gcc 12.2.0` which is the default compiler on Ubuntu 22.10 preventing FTL to compile successfully on the latest Ubuntu release. Herein, we add a suitable workaround needed to ensure compatibility with this `gcc` version. There are no functional changes whatsoever in this PR. I tested with a few older versions of `gcc` and found no difference in compatibility due to these changes.

Fix compatibility with gcc 12.2.0

---

src/daemon.c
src/dnsmasq_interface.c
src/main.c
src/shmem.c
src/shmem.h
test/test_suite.bats

---
**Store and check shared memory ownership before resizing shared memory objects.**
The scenario we are resolving here is the following: FTL is already running and someone(/-thing) deletes all the shared memory objects. If another instance of FTL is then started, it doesn't know a previous process is running and creates new SHM objects for itself. Both processes can - in theory - run just fine without touching each other as they are both actually using *different* shared memory objects. You are right when you think this is bizarre. The reason is that the first one has the shared memory objects still mapped into memory, i.e., "deleting" them from disk only removes the visible file …

Improve shared memory protection

---

test/test_suite.bats

---
Use `dnssec.works` instead of `verteiltesysteme.net` for FTL's CI tests as the latter broke (see [here](https://github.com/pi-hole/FTL/pull/1469#issuecomment-1307718167) for further details). This PR updates the test to use a different DNSSEC validation service: https://dnssec.works/

Tests: Use dnssec.works instead of verteiltesysteme.net

---

.github/workflows/build.yml
src/CMakeLists.txt
src/FindDBus.cmake
src/dnsmasq/config.h
src/dnsmasq/dnsmasq.h
test/arch_test.sh
test/run.sh
test/test_suite.bats

---
Update CI to use [`ftl-build:v1.23`](https://github.com/pi-hole/docker-base-images/releases/tag/v1.23) containers. This includes two changes:
- Update statically linked `nettle` from version 3.8 to 3.8.1
- Include an "all-options" test build for `dnsmasq` (DBus, `conntrack`, `nftset`)

Update CI to ftl-build:v1.23 containers

---

src/database/message-table.c

Always ensure FTL messages are unique

---

src/shmem.c

Fix shared memory crashes in TCP forks

---

src/CMakeLists.txt

Increase default SQLite3 cache size from ~2 MiB to 16 MiB
FTL heavily relies on the [B-tree](https://en.wikipedia.org/wiki/B-tree) of the databases to be able to make extremely fast decisions if a domain is to be blocked. The speed-up between a B-tree and a conventional lookup is on the order of `O(N/log(N))` so something like 7,000x for 120,000 gravity-blocked domains or roughly 100,000x for two million domains.
For this to be efficient, FTL needs to have sufficiently fast access to the B-tree. By default, SQLite3 uses an upper limit for the cache of roughly 2 [MiB](https://en.wiktionary.org/wiki/mebibyte). This PR increases this limit to 16 [MiB](https://en.wiktionary.org/wiki/mebibyte). Given how much memory FTL uses overall, this seems an acceptable amount.
One further technical …

Increase SQLite3's cache size

---

CMakeLists.txt
src/dnsmasq/dbus.c
src/dnsmasq/dnsmasq.h
src/dnsmasq/option.c

Update embedded `dnsmasq` to `2.88rc3`. `rc2` fixes a very small (less than 1 KB) one-time memory leak when using hostnames as arguments to `server=...` and restores BSD-compatibility (however, FTL (probably?) isn't BSD-compatible). `rc3` fixes a bug introduced in `rc2` (the currently released FTL contains `rc1` so isn't affected).
---
2. I have commented my proposed …

Update embedded dnsmasq to v2.88rc3

---

CMakeLists.txt
src/dnsmasq/dnssec.c
src/dnsmasq/domain-match.c
src/dnsmasq/option.c

This adds the two most recent changes. One vastly improves the speed of edge-case configurations where users have many (think thousands of) `server=...` config lines. The other one fixes handling of unsupported crypto algorithms (there are none to date so that shouldn't have a practival influence).
---
3. I am …

Update embedded dnsmasq to v2.88rc4

---

src/database/query-table.c

`dnsmasq` recently re-introduced the DNSSEC status `ABANDONED` and FTL shouldn't complain if we are importing this from the database. This bug exists in `master`, however, it is very rare to ever encounter `ABANDONED` and - even then - FTL will only warn on restarts and skip these queries without any other consequences.
---
2. I have commented my proposed changes …

Fix incorrect DNSSEC-related warning during history import

---

src/args.c

FTL should exit immediately after running the config check when being invoked as `pihole-FTL dnsmasq-test`. This was not the case leading to possible (but harmless) side-effects further down the line (SEGFAULT). Hence, I'm marking this PR as bugfix.
---
---
4. I have commented my proposed changes within the code.
6. I am willing to help maintain this change if there …

Exit immediately after running dnsmasq-test

---

src/args.c
src/dnsmasq/dnsmasq.c
test/test_suite.bats

This PR adds colors (if supported by the terminal) to verbose version output and completely revamps the help function.
When the "consumer" is not a terminal (e.g. a pipe), no escape sequences will be added.
---
**`pihole-FTL -vv` BEFORE**
**`pihole-FTL -vv` NOW**
---
**`pihole-FTL -h` BEFORE**
**`pihole-FTL -h` NOW**
---
---
4. I have commented my proposed changes …

Improve -vv and --help

---

CMakeLists.txt
src/dnsmasq/dhcp-common.c

This PR adds the missing commit from `v2.88rc5` to the full release `v2.88`

Update embedded dnsmasq to v2.88

---

src/database/query-table.c

Always store time we start to save to the database (not only in debug mode). This avoids erroneous timing reports in case of errors like seen here:
```
[2022-12-26 11:29:00.102 1204/T1220] Notice: Queries stored in long-term database: 166 (took 1672072140102.7 ms, last SQLite ID 4461823)
```
This bug has no other consequences else than the wrongly logged time.
**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable): N/A
---
4. I …

Always store time we start saving to the database

---

src/args.c

PR https://github.com/pi-hole/FTL/pull/1501 added a colorful output for `pihole-FTL -h`. 
For some items it uses a `gray` color - but this is hardly readable when the terminal background is not pitch black. 
This PR removed the `gray` and switches colors of those items to `purple`
--- …

Remove gray color in help output

---

CMakeLists.txt
src/dnsmasq/cache.c
src/dnsmasq/dnsmasq.h
src/dnsmasq/option.c

Update the embedded dnsmasq to v2.89
This fixes a very severe albeit almost impossible to trigger internal cache bug. 
**CHANGELOG**
```
version 2.89
Fix bug introduced in 2.88 (commit fe91134b) which can result
in corruption of the DNS cache internal data structures and
logging of "cache internal error". This has only been seen
in one place in the wild, and it took considerable effort
to even generate a test case to reproduce it, but there's
no way to be sure it won't strike, and the effect is to break
the cache badly. Installations with DNSSEC enabled are more
likely to see the problem, but not running DNSSEC does not
guarantee that it won't happen. Thanks to Timo van Roermund
for reporting the bug and for his great efforts in chasing
it down.
```
This release furthermore adds [a …

Update embedded dnsmasq to v2.89

---

src/database/shell.c
src/database/sqlite3.h

Update the embedded SQLite3 engine. Pi-hole will benefit from improvements to the [PRAGMA integrity_check](https://sqlite.org/pragma.html#pragma_integrity_check) command and miscellaneous performance enhancements.
We do not add [SQLITE_ENABLE_STMT_SCANSTATUS](https://sqlite.org/compile.html#enable_stmt_scanstatus), the SQLite3 help says:
>  Those interfaces are normally omitted from the build **because they imposes a performance penalty**, even on statements that do not use the feature. 
1. Query planner improvements: 
1. Make use of [indexed expressions](https://sqlite.org/expridx.html) within an aggregate query that includes a GROUP BY clause. 
2. The query planner has improved awareness of when an index is a [covering index](https://sqlite.org/queryplanner.html#covidx) and adjusts …

Update embedded SQLite to 3.41.1

---

src/dnsmasq/option.c

See title and related Discource topic (link below).
---
6. I have checked that …

Put version.ftl also behind new no-ident config option

---

.github/workflows/build.yml
src/struct_size.c
test/arch_test.sh

Add RISC-V 64-bit support and builds

---

CMakeLists.txt
src/dnsmasq/config.h
src/dnsmasq/dbus.c
src/dnsmasq/dhcp-common.c
src/dnsmasq/dhcp.c
src/dnsmasq/domain-match.c
src/dnsmasq/loop.c
src/dnsmasq/network.c
src/dnsmasq/option.c
src/dnsmasq/rfc1035.c
src/dnsmasq/rfc2131.c
src/dnsmasq/rfc3315.c
src/dnsmasq/tftp.c

Merge bug fixes and improvements
Related changelog:
```
Fix reversion in --rev-server introduced in 2.88 which
caused breakage if the prefix length is not exactly divisible
by 8 (IPv4) or 4 (IPv6).
Fix possible SEGV when there server(s) for a particular
domain are configured, but no server which is not qualified
for a particular domain. Thanks to Daniel Danzberger for
spotting this bug.
Set the default maximum DNS UDP packet sice to 1232. This
has been the recommended value since 2020 because it's the
largest value that avoid fragmentation, and fragmentation
is just not reliable on the modern internet, especially
for IPv6. It's still possible to override this with
--edns-packet-max for special circumstances.
```

Update embedded dnsmasq

---

src/dnsmasq/forward.c
src/dnsmasq_interface.c
src/dnsmasq_interface.h
src/edns0.c
src/edns0.h

---
When the `dnsmasq` option `proxy-dnssec`
> **proxy-dnssec**
> Copy the DNSSEC Authenticated Data bit from upstream servers to downstream clients. This is an alternative to having dnsmasq validate DNSSEC, but it depends on the security of the network between dnsmasq and the upstream servers, and the trustworthiness of the upstream servers. Note that caching the Authenticated Data bit correctly in all cases is not technically possible. If the AD bit is to be relied upon when using this option, then the cache should be disabled using `--cache-size=0`. In most cases, enabling DNSSEC validation within dnsmasq is a better option. See `--dnssec` for details. 
is used, FTL uses the AD …

Use EDE data when "proxy-dnssec" is used

---

src/config.c
src/dnsmasq/forward.c
src/dnsmasq_interface.c

When multiple upstream servers are defined (can also be the case with enabled "conditional forwarding"), it can happen that the upstream destination display for DNSSEC-related queries is incorrect.
This is fixed by this PR in two independent ways:
1. Ensure we are analyzing also the DNSSEC-related replies
2. Ensure we are not invalidating upstream responses after analysis to avoid possible confusion in subsequent queries
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand …

Fix shown upstream for internally generated DNSSEC-queries being wrong in certain configurations

---

src/gc.c

Do not log running out of disk space when the disk occupation is > 100%. We are seeing this with docker deployments on macOS hosts. It is a band-aid fix, however, it also seem to be the only thing we can do given that docker didn't fix this in nearly two years now.
This PR seeks to fix https://github.com/pi-hole/docker-pi-hole/issues/951
--- …

Do not log unrealistic disk usage (docker + macOS bug)

---

src/database/shell.c
src/database/sqlite3.h
test/test_suite.bats

Pi-hole will benefit from points 5, 8, and 14 below.
1. Add the [FTS5 secure-delete command](https://sqlite.org/fts5.html#the_secure_delete_configuration_option). This option causes all forensic traces to be removed from the FTS5 inverted index when content is deleted. 
2. Enhance the [JSON SQL functions](https://sqlite.org/json1.html) to support [JSON5 extensions](https://sqlite.org/json1.html#json5). 
3. The [`SQLITE_CONFIG_LOG`](https://sqlite.org/c3ref/c_config_covering_index_scan.html#sqliteconfiglog) and [`SQLITE_CONFIG_PCACHE_HDRSZ`](https://sqlite.org/c3ref/c_config_covering_index_scan.html#sqliteconfigpcachehdrsz) calls to [sqlite3_config()](https://sqlite.org/c3ref/config.html) are now allowed to occur _after_ [`sqlite3_initialize()`](https://sqlite.org/c3ref/initialize.html). …

Update embedded SQLite to 3.42.0

---

src/tools/dhcp-discover.c

Add capabilities check for feature `pihole-FTL dhcp-discover` in the same way we already have it for `pihole-FTL arp-scan`
---
5. I have …

Add capabilities check for feature dhcp-discover

---

src/CMakeLists.txt
src/args.c
src/args.h
src/gravity-tools.c
src/gravity-tools.h

This PR implements a list parsing feature into FTL that is intended to be used with gravity. Its main advantage is a stream-lined approach directly writing everything directly into the new database during analysis. There is no detour over huge allocated memory blocks or temporary files.
---
3. I am willing to …

Add list parsing feature for gravity

---

deploy.sh
src/syscalls/sendto.c
src/tools/arp-scan.c
src/tools/dhcp-discover.c

This PR improves the `dhcp-discover` feature in three ways:
1. We add locking between the log outputs to ensure only once thread can "talk" at a time to reduce the possibility of intermixing texts for DHCP replies receiving at the same time
2. Add explicit logging for when the call to `sendto()` fails (as has been suggested in a comment of @yubiuser in #1561)
3. Scan all IPv4-capable interfaces. So far, the scan looped over packet-capable interfaces. The list of interfaces overlaps, but is not identical. Looping over `AF_INET` interfaces is more appropriate because we want to make sure they can actually send IPv4 UDP packets to a potential DHCP server.
Furthermore, this PR fixes a small bug in our deployment script that incorrectly assumed some directories already existed when they really …

Tweak dhcp-discover subcommand

---

src/gravity-tools.c

Do not consider false positives as invalid domains

---

src/CMakeLists.txt
src/args.c
src/gravity-tools.c
src/tools/CMakeLists.txt
src/tools/gravity-parseList.c
src/tools/gravity-parseList.h

Fix missing update of `adlist.date_updated`: https://github.com/pi-hole/pi-hole/pull/5275#discussion_r1201019607
--- …

Fix missing update of `adlist.date_updated`

---

src/tools/gravity-parseList.c

With the transition of `parseList()` from `gravity.sh` to FTL realm some code duplication occurred. Duplicated code is from `gravity_ParseFileIntoDomains()`
https://github.com/pi-hole/pi-hole/blob/50d67dce73e122d98026ab2a4b30255efd9b05fc/gravity.sh#L639-L667
No all input modifications were duplicated into FTL so we could not remove `gravity_ParseFileIntoDomains` completely. 
Removes the duplicates
P.S. It would also be possible to move the whole `gravity_ParseFileIntoDomains` also into FTL's realm, however this would require more modifications (in `core` and `FTL`
--- …

Remove code duplication found in gravit.sh gravity_ParseFileIntoDomains()

---

.github/.codespellignore
.github/.codespellignore_lines
.github/workflows/codespell.yml
src/api/api.c
src/api/auth.c
src/api/docs/content/specs/auth.yaml
src/api/docs/content/specs/clients.yaml
src/api/docs/content/specs/domains.yaml
src/api/docs/content/specs/groups.yaml
src/api/docs/content/specs/lists.yaml
src/api/docs/content/specs/search.yaml
src/api/docs/content/specs/stats.yaml
src/api/docs/docs.c
src/api/network.c
src/api/stats.c
src/api/stats_database.c
src/api/teleporter.c
src/config/config.c
src/config/legacy_reader.c
src/config/toml_helper.c
src/database/gravity-db.c
src/database/query-table.c
src/webserver/webserver.c
src/webserver/x509.c
test/api/libs/responseVerifyer.py
test/pihole.toml

Satisfy `codespell` in `FTLv6`.
Fix sepelling and set some external resources to be excluded from checking

Fix spelling in v6

---

src/args.c

The new checkOnly argument should be `false` when parsing lists

---

src/webserver/x509.c

Change generated elliptic curve from secp521r1 to secp384r1 because the former is [not supported](https://boringssl.googlesource.com/boringssl/+/e9fc3e547e557492316932b62881c3386973ceb2) by current Google Chrome (and, presumably, Chromium-based browsers like Edge).
The reason for the removal is that NSA Suite B does not *mention* P-521 in the document, leading to Chrome removing support (even though Firefox keeps support for it, FIPS 140-2 also focuses on P-256 and P-384).
There is nothing wrong about this curve but with no support in Chrome, it doesn't make sense to still keep it for automatic certificate generation in Pi-hole. The reason why we currently have it in the v6.0 code is that I have never tried Chrome + Pi-hole TLS before and don't have a single Windows machine to try Edge. …

Change generated elliptic curve from secp521r1 to secp384r1

---

src/config/toml_helper.c

In case a user calls `sudo pihole --config ...`, the config will will be owned by `root` and editing via the API (unprivileged user `pihole`) becomes impossible. This PR ensures the config file is `chown`ed after writing if the FTL process is executed as `root` (UID == 0).
--- …

Chown config file after writing (if root)

---

.github/workflows/stale.yml

See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only

Fix the Stale workflow

---

src/api/docs/content/index.html
src/api/docs/content/specs/auth.yaml
src/api/docs/content/specs/dns.yaml
src/api/docs/content/specs/main.yaml

See title, no functional change.
**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** This is the documentation change.
--- …

Add OpenAPI Authentication and Authorization details for the API

---

src/datastructure.c
src/enums.h

Add `TRUNCATED` status to enumeration of valid DNSSEC status codes. Truncated answer can't be validated. If this is an answer to a DNSSEC-generated query, we still need to get the client to retry over TCP, so we return an answer with the `TC` bit set, even if the actual answer fits into buffer. All the other code is already there, just the parsing code needs a minor tweak.
I have never seen a truncated DNSSEC message with my local `unbound`, however, I have recently received comments about this status popping up quite often with certain online resolvers (Quad9 or DNS.Watch IIRC) putting too much optional content into the DNSSEC reply causing fragmentation (= truncation). The only way to remedy is retrying over TCP which then does support fragmentation (as said above).
This fix is merely …

Add support for TRUNCATED DNSSEC status

---

src/dnsmasq_interface.c

Add the bit that was missing in https://github.com/pi-hole/FTL/pull/1595: Actually *apply* `TRUNCATED` status when found
---
---
5. I have …

Add support for TRUNCATED DNSSEC status (2)

---

src/api/docs/content/specs/search.yaml
src/api/queries.c
src/api/search.c
src/webserver/http-common.c
src/webserver/http-common.h

---
This PR seeks to fix the `search` and `taillog` API features on 32bit architectures and improve overall API parameter handling:
- Use explicitly sized integers (`u/int64_t`) to avoid overflowing `unsigned int`s not fitting within `long`s on 32bit.
- Log warnings when parameters of invalid type are passed to the API (e.g., a numeric parameter receiving an out-of-bounds or non-numeric argument).
- Include the specified parameters in the `search` response to ease working with the API

Fix API parameter parsing on 32bit architectures

---

src/api/docs/content/specs/queries.yaml
src/webserver/lua_web.c
src/webserver/webserver.c

As a consequence of https://github.com/pi-hole/AdminLTE/pull/2655, redirection from the login page to any other page than the dashboard is broken.
This PR fixes this in the proper way by redirecting from URLs with *trailing slashes* such as `/admin/queries/"` to `/admin/queries` which is where the actual scripts are (they'd have to be in `/admin/queries/index.html` otherwise)
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull …

Slash the slash

---

src/api/action.c
src/api/api.c
src/capabilities.c

---
See title. They should likely never have been added in the first place. This fixes our "mistake".

Remove reboot and poweroff actions from the API

---

src/config/password.c

This PR fixes the upgrade procedure of the "old" double SHA256 hash to the new BALLOON-based hash. Before, the code incorrectly relied on insufficient randomness possibly ending in spurious crashes. After this fix, it uses cryptographically secure random data for generating the hash's salt data.
---
3. I am …

Fix upgrade of the password hash

---

src/args.c

Copies a few missing information from `man pihole-FTL` into `pihole-FTL -h`.
https://github.com/pi-hole/pi-hole/blob/master/manpages/pihole-FTL.8
Man page for FTL is going to get removed for v6:  https://github.com/pi-hole/pi-hole/commit/f7b9d70054758137d60318e6df32ebb0d92987fe

Copy missing information from man pihole-FTL to pihole-FTL -h

---

src/api/config.c

Fix warning printed when an argument should be floating point but is not a number.
--- …

Fix API config value interpretation warning

---

src/api/info.c

GET `/api/info/sensors` should return no error but simply no values when we cannot parse temperature sensors. So far, it returned error `404 Not Found` when FTL could not read `/sys/class/hwmon`. Technically, this does make some sense (`hwmon` could not be found in the end), however, it is not what we expect as we'd rather see a successful return with an empty set of sensors.
This has not been tested so far because the Linux kernel documentation states that `hwmon` is *the* default and go-to sensor management system. However, we've just learned that the Microsoft WSL2 provided kernel does not include this standard feature meaning we have to expect this to be missing. This is what is added in this PR.
Fixes #1614  …

Fix 404 for GET /api/info/sensors when hwmon isn't available

---

src/database/query-table.c
src/database/query-table.h
src/main.c

Fix an incorrect shortcut leading to FTL not being able to store queries in the long-term query database on disk if `database.DBimport` is `false`. The solution is to ensure we always get the `MAX(id)` from the on-disk database and never skip it. Otherwise, uniqueness constraint violations happen on the field `id` during query `INSERT`ion.
Reported and confirmed fixes in https://github.com/pi-hole/FTL/issues/1617 by @regae 
Note: The bug affected only users with `database.DBimport = false` (this option defaults to `true`) 
--- …

Always get max query ID from disk

---

src/api/docs/content/specs/search.yaml

`MAX_SEARCH_RESULTS` for searching the adlists is `10,000`
https://github.com/pi-hole/FTL/blob/9c4e132bd6bf18524a7948c208bec67d776ca28c/src/api/search.c#L19
Documentation is changed accordingly.
--- …

Hard limit for searching the adlists is 10,000

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/config/dnsmasq_config.c
src/files.c
src/files.h
test/hostnames.sh
test/pihole.toml

Add new config option `files.pcap` to expose integrated packet (PCAP) dumping to a file. This PR also fixes a small issue with the hostname test failing in the most recent `ftl-build` containers.
--- …

Add config option to enable packet dumping to PCAP file

---

src/database/shell.c
src/database/sqlite3.h

SQlite3.43.0 has been released about two weeks ago.
CHANGELOG:
1. Add support for [Contentless-Delete FTS5 Indexes](https://sqlite.org/fts5.html#clssdeltab). This is a variety of [FTS5](https://sqlite.org/fts5.html) full-text search index that omits storing the content that is being indexed while also allowing records to be deleted. 
2. Enhancements to the [date and time functions](https://sqlite.org/lang_datefunc.html): 
1. Added new [time shift modifiers](https://sqlite.org/lang_datefunc.html#tmshf) of the form `±YYYY-MM-DD HH:MM:SS.SSS`. 
2. Added the [timediff() SQL function](https://sqlite.org/lang_datefunc.html#tmdif). 
3. Added the [octet_length(X)](https://sqlite.org/lang_corefunc.html#octet_length) SQL function. 
4. Added the …

Update embedded SQLite to 3.43.0

---

src/database/shell.c
src/database/sqlite3.h

---
CHANGELOG:
1. Fix a regression in the way that the [sum()](https://sqlite.org/lang_aggfunc.html#sumunc), [avg()](https://sqlite.org/lang_aggfunc.html#avg), and [total()](https://sqlite.org/lang_aggfunc.html#sumunc) aggregate functions handle infinities. 
2. Fix a bug in the [json_array_length()](https://sqlite.org/json1.html#jarraylen) function that occurs when the argument comes directly from [json_remove()](https://sqlite.org/json1.html#jrm). 
3. Fix the omit-unused-subquery-columns optimization (introduced in in version 3.42.0) so that it works correctly if the subquery is a compound where one arm is DISTINCT and the other is not. 
4. Other minor fixes.

Update embedded SQLite to 3.43.1

---

src/api/auth.c
src/config/cli.c
src/config/config.c
src/gc.c
src/signals.c

Ensure that all web sessions are invalidated when the password hash is changed. This is already the case when the password is changed through the API but it hasn't been done when the hash has been changed on-disk (e.g., by calling `pihole -a -p`) and, subsequently, reread by FTL. This is fixed in this PR.
---
3. …

Clear web session on external password change

---

src/api/docs/content/specs/queries.yaml
src/api/queries.c
src/database/common.c
src/database/query-table.c
src/database/query-table.h
src/datastructure.h
src/dnsmasq/rfc1035.c
src/dnsmasq_interface.c
test/test_suite.bats

---
See title. This was so far missing.

Provide regex ID for API

---

.github/workflows/build.yml

Allow build/deploy workflow to be triggered by workflow_dispatch
---
6. I have …

Allow build/deploy workflow to be triggered by workflow_dispatch

---

src/api/docs/content/specs/lists.yaml
src/api/list.c
src/api/search.c
src/args.c
src/database/gravity-db.c
src/database/gravity-db.h
src/dnsmasq_interface.c
src/enums.h
src/tools/gravity-parseList.c
src/tools/gravity-parseList.h
test/gravity.db.sql
test/pdns/setup.sh
test/test_suite.bats

Add support for new `antigravity` table added in https://github.com/pi-hole/pi-hole/pull/5330
Subscribed allowlists support the exact same syntax as in gravity:
- exact domains, and
- `@@||...^` ABP-style wildcards
Subscribed allowlists can only permit domains from subscribed blocklists. They cannot overwrite manually blocked domains, e.g., by regex or local blocklist domains.
The existing logic is extended such that `gravity` is only checked when there was **no** `antigravity` match (performance optimization). ABP-style domains are only checked when Pi-hole knows there are any in the lists (performance optimization).
Pick your subscribed allowlists wisely, they can easily undo all the adlist-related blocking on your Pi-hole, e.g., when containing something like `@@||com^`, no `*.com` …

Add antigravity (subscribed allowlists with wildcard support)

---

src/api/CMakeLists.txt
src/api/theme.c
src/api/theme.h
src/config/config.c
src/config/config.h
src/datastructure.c
src/datastructure.h
src/enums.h
src/lua/ftl_lua.c

Provide theme details through Lua function `pihole.webtheme()` now returning a full table instead of only a string. Everything concerning theme definition is moved into `api/themes.{c,h}` and simplified to remove duplication as good as possible (the `enum` is defined separately for efficiency reasons, everything else is in `theme.c`).
--- …

Improve web theme handling

---

src/api/auth.c
src/api/config.c
src/api/docs/content/specs/auth.yaml
src/api/docs/content/specs/common.yaml
src/args.c
src/config/cli.c
src/config/password.c
src/config/password.h
test/api/libs/FTLAPI.py
test/api/test-rate-limit.py
test/run.sh

Add `pihole-FTL --perf` suitable to measure both memory- as well as compute-performance in the context of password hashing.
Context (source [Wikipedia EN](https://en.wikipedia.org/wiki/Balloon_hashing)):
> Balloon hashing is a [key derivation function](https://en.wikipedia.org/wiki/Key_derivation_function) presenting proven memory-hard password-hashing and modern design. It was created by [Dan Boneh](https://en.wikipedia.org/wiki/Dan_Boneh), Henry Corrigan-Gibbs (both at [Stanford University](https://en.wikipedia.org/wiki/Stanford_University)) and Stuart Schechter ([Microsoft Research](https://en.wikipedia.org/wiki/Microsoft_Research)) in 2016. It is a recommended function in [NIST password guidelines](https://en.wikipedia.org/wiki/Password_policy#NIST_guidelines).
>
> The authors claim …

Add performance tests and prevent online-brute forcing

---

src/args.c
src/webserver/webserver.c
src/webserver/x509.c
src/webserver/x509.h

Allow generating X.509 TLS certificates for arbitrary domain names.
When auto-generated, FTL uses the config value `webserver.domain` defaulting to `"pi.hole"`.
The generated certificate may be checked using, e.g.
``` bash
openssl x509 -in /etc/pihole/tls.pem -text -noout
```
--- …

Allow generating X.509 TLS certificates for arbitrary domain names

---

src/api/api.c
src/api/api.h
src/api/auth.c
src/api/docs/content/specs/auth.yaml
src/api/docs/content/specs/info.yaml
src/api/docs/content/specs/main.yaml
src/api/info.c
src/webserver/webserver.c
src/webserver/webserver.h
test/test_suite.bats

Add `GET /api/info/login` with a `dns` boolean and a `https_port` integer returning either `0` (no HTTPS port defined or web server not running) or the port number of the first configured HTTPS port.
This is to be used in ~~a future PR~~ https://github.com/pi-hole/web/pull/2730 that makes the "consider using HTTPS" link on the login page conditional on HTTPS being actually enabled (it is by default). It can also be used to redirect to the correct port (in case this is not 443).
This PR supersedes https://github.com/pi-hole/FTL/pull/1652
---
1. I have read and understood the …

Add /api/info/login

---

src/database/shell.c
src/database/sqlite3.h

SQLite3 CHANGELOG:
1. Fix a couple of obscure UAF errors and an obscure memory leak. 
2. Omit the use of the sprintf() function from the standard library in the [CLI](https://sqlite.org/cli.html), as this now generates warnings on some platforms. 
3. Avoid conversion of a double into unsigned long long integer, as some platforms do not do such conversions correctly. 
--- …

Update SQLite3 to 3.43.2

---

src/webserver/webserver.c

Fix wording of info message concerning self-generated TLS certificate. Before this commit, we incorrectly logged that we created a TLS certificate not only when we really did this but also after each restart when simply using it.
--- …

Fix wording of info message concerning self-generated TLS certificate

---

src/database/gravity-db.c

Fix domain type and kind not being added for certain `/api/domains` calls
This is a regression of https://github.com/pi-hole/FTL/pull/1649
--- …

Fix domain type and kind not being added for certain /api/domains calls

---

src/api/queries.c
src/database/query-table.c
src/database/query-table.h

The PR adds the ability to sort the server-side prepared Query Log by all relevant columns. This PR works on its own, no `web` changes are required to get Query Log sorting.
--- …

Implement Query Log sorting (server-side pagination)

---

src/api/api.c
src/api/api.h
src/api/auth.c
src/api/docs/content/specs/config.yaml
src/api/docs/content/specs/search.yaml
src/config/config.c
src/config/config.h
test/pihole.toml

Add new config option `webserver.api.searchAPIauth` defaulting to `false` to aid https://github.com/pi-hole/pi-hole/pull/5361
---
5. I have …

Add new config option webserver.api.searchAPIauth

---

src/config/toml_helper.c

Skip empty elements in config arrays both when reading and writing. This fixes https://github.com/pi-hole/web/issues/2754 and possibly related issues we haven't seen yet.
--- …

Skip empty elements in config arrays both when reading and writing

---

src/webserver/civetweb/mod_mbedtls.inl

We are seeing that the strict commitment of FTL to the [NSA Suite B Cryptography](https://en.wikipedia.org/wiki/NSA_Suite_B_Cryptography) recommendations for improved TLS security are in fact too strict to cover all use cases.
Under Suite B, FTL accepts exactly two possible cipersuites (OpenSSL notation as used by Firefox, etc., too):
- `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256`
- `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384`
Using the "default" ciphersuite, however, allows not only those two but in total 165 ciphersuites:
- `TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256`
- `TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256`
- `TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256`
- `TLS_PSK_WITH_CHACHA20_POLY1305_SHA256`
- `TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256`
- …

Initialize mbedtls with default instead of SuiteB presets

---

src/api/docs/content/specs/search.yaml
src/api/search.c
src/database/gravity-db.c
test/test_suite.bats

During review of https://github.com/pi-hole/pi-hole/pull/5361, I noticed that there is no way for the client to know if their search request reached the given limit of results to return or if there are (possibly many) more entries to retrieve given a higher value of `N`.
The PR adds a new object having total counts not being clipped by the parameter `N`:
Example result for partial match of `doubleclick.net`:
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch …

Add number of matches into /api/search/{domain} results

---

src/api/docs/content/index.css
src/api/docs/content/index.html
src/api/docs/content/specs/main.yaml

Make HTTPS scheme the default case, change the default port from 8080 to 80 for the HTTP case, and make docs index page a Lua page to allow loading of the favicon
--- …

Minor integrated docs changes

---

src/api/config.c
src/config/config.c

This PR fixes three connected issues with the API endpoint `/api/config`:
- Fix detection of unchanged password. This fixes a forced invalidation of all currently active API session on every config change because every saving was misinterpreted as a password change.
- Ensure we are using the same constants everywhere for our enums (this fixes the issue reported on [Discourse](https://discourse.pi-hole.net/t/dns-blocking-mode-does-not-apply/65674))
- Tweak `misc.privacylevel` to also accept numbers formatted as strings. This can happen when using a dropdown select as done, e.g., on the web interface in `System-> Settings -> All Settings`.
--- …

Fix a few API config issues

---

src/api/docs/content/specs/queries.yaml
src/api/queries.c

Add wildcard support for server-side Query Log for the fields `domain`, `client-ip`, `client-by-name`, and `upstream` and fix a minor glitch resulting in showing the total number of queries in the last 24 hours even when the timerange was narrowed down.
Instead of the completely random wildcard matching, we decided to opt for "real" wildcards with the wildcard character `*`. You can get anything ending in `google.com` - for instance, `analytics.google.com` - by searching for `*google.com` (hint: It'd also match `google.com` itself). But the wildcard implementation presented here goes beyond that, you can use a wildcard in any place you want: `*fla*.c*` will match `cloudflare.com`, `flamewar.com` and others. …

Add wildcard support for the server-side Query Log

---

src/webserver/x509.c

Add SAN field into self-generated X.509 TLS certificates. It is mandatory since RFCs 2818 (page 5)
>    If a subjectAltName extension of type dNSName is present, that **MUST**
be used as the identity. Otherwise, the (most specific) Common Name
field in the Subject field of the certificate **MUST** be used. Although
the use of the Common Name is existing practice, it is deprecated and
Certification Authorities are encouraged to use the dNSName instead.
as well as RFC 3280 (4.2.1.7, 1. paragraph)
>    The subject alternative names extension allows additional identities
to be bound to the subject of the certificate.  Defined options
include an Internet electronic mail address, a DNS name, an IP
address, and a uniform resource identifier (URI).  Other options
exist, including completely local …

Add SAN field into self-generated certificates

---

src/api/config.c
src/config/password.c
src/config/password.h
src/config/toml_helper.c
src/config/toml_helper.h
src/config/toml_reader.c
test/run.sh
test/test_suite.bats

Make FTL read and parse `FTLCONF_*` environmental variables. If they exist, they take precedence over config file values. The config file is updated from environmental variables so any changes can be followed therein.
We furthermore add a special environmental variable `FTLCONF_ENV_ONLY`. When set to `true`, *only* environmental variables are used to configure FTL and the config file is ignored. All variables not defined by appropriate env vars are initialized with their defaults (check `/etc/pihole/pihole.toml` for the defaults).
---
1. I have read and understood the …

Add environmental variables support

---

.devcontainer/devcontainer.json
src/database/aliasclients.c
src/database/common.c
src/database/message-table.c
src/database/network-table.c
src/database/query-table.c
src/database/query-table.h
test/test_suite.bats

This PR improves `pihole-FTL.db` handling in two ways:
1. Ensure all database upgrade steps are wrapped into transactions. When the database upgrade is interrupted (FTL is killed, or crashed or power loss, ...), then the rollback journal file is left on disk. The next time another application attempts to open the database file, it notices the presence of the abandoned rollback journal (we call it a "hot journal" in this circumstance) and uses the information in the journal to restore the database to its state prior to the start of the incomplete transaction. This fixes sporadic issues with only partially initialized databases mostly seen on devices with unstable power supply.
So far, it is unclear how the initial database migration happens but it is likely due to the reasons mentioned …

Ensure database upgrades use transactions

---

src/api/docs/content/specs/stats.yaml
src/api/stats.c

Include number of active clients in the response of `GET /api/stats/summary`
Needed for https://github.com/pi-hole/web/pull/2769
---
5. I have …

Include number of active clients in summary

---

src/config/toml_helper.c

A very simple change doing exactly what the title says. Context here: https://github.com/pi-hole/docker-pi-hole/pull/1460#discussion_r1367310040
--- …

Allow both commas and semicolons for separating array env var entries

---

.github/workflows/build.yml

We see sporadic but intermittent failures for FTL jobs in emulated environments (most often, `armv6` or `riscv64` fail). The PR adds a retry action that - well - retries failed jobs up to three times until they are are finally marked as failed.
---
3. I am willing to help maintain this change if there are issues …

Retry failed FTL builds

---

src/api/config.c
src/config/cli.c
src/config/config.h
src/config/toml_reader.c
src/config/toml_writer.c
test/test_suite.bats

Config values set through environmental variables are now considered "read-only" by FTL:
- They cannot be changed via the API (error 400 response with explanation)
- They cannot be changed via `pihole.toml` (change is automatically reverted)
- They cannot be changed via `pihole-FTL --config ...` (error message is shown)
Furthermore, we add a small hint into the config file to the corresponding settings if they are forced by an env var and expose the property via the API
--- …

Config items set via environment variables are read-only

---

src/api/docs/content/specs/auth.yaml

`GET /api/auth` returns `401 Unauthorized` when login is required and the user has no valid session.
This is currently missing in the API docs. Thanks @yubiuser for spotting this. We furthermore tweak the auth-related examples.
--- …

Fix API GET /api/auth documentation

---

src/config/password.c

Fix small logic bug preventing setting an empty (= no) password via API/CLI/file. So far, it was only possible by directly interacting with `.pwhash`
--- …

Fix setting empty password

---

src/config/toml_helper.c

See title, as simple as that. This PR follows an internal discussion because `dns.cnameRecords` uses `,` internally.
--- …

Env var arrays are ;-delimited

---

src/api/config.c

`PUT` and `DELETE` on config items which are forced by env variable should be rejected with `400 Bad Request` + explanation
---
5. I have …

PUT and DELETE on forced config items are errors

---

src/database/query-table.c

Improve warning messages printed during query table parsing (history import). This branch was long forgotten about the change it adds is still worth having.
--- …

Improve query table parsing warnings

---

src/api/docs/content/specs/auth.yaml
src/api/docs/content/specs/clients.yaml
src/api/docs/content/specs/endpoints.yaml
src/api/docs/content/specs/info.yaml
src/api/docs/content/specs/network.yaml
test/api/libs/responseVerifyer.py

This PR originated from https://github.com/pi-hole/FTL/pull/1705#issuecomment-1784234456 but sent me way down the rabbit hole. At first, I only added `.session.X.app` as this was missing in the API specs. This raised the question why our fully-automated API checks didn't unveil this before.
The reason is simple: When we find an object in the API specs, we recurse. Otherwise, we simply check this property. So when we found an array, we checked whether the API specs defined this as array, too, and when this is the case, we say that's correct. However, the *content* of the array - may it be a plain array of `strings` or maybe an array of complex objects, possibly containing further arrays (yes, we have such things...) - was not checked.
This has now been added in this PR and we immediately …

API tests: Implement deep-recursion of arrays

---

src/api/info.c

When test compiling FTL on a machine without swap, we've seen the following result in the tests:
```
GET /api/info/system (BODY auth):
- FTL's reply (<class 'NoneType'>) does not match defined type (number) in system.memory.swap.%used
```
This is caused by a division-by-zero error which lead to a `null` being returned in the JSON. There are two obvious fixes:
1. Change the API specs to accept returning a `null` here, or
2. Ensure that in case of no swap, `0` is returned instead (0% swap used).
The latter seems superior as it needs less logic on the client side to handle this.
Even when we will never see a system with no RAM, the logic is applied here as well - just as a precaution because division-by-zero is never a good thing.
**Pull …

Ensure %used is 0.0 if no swap is used

---

.github/.codespellignore
patch/civetweb.sh
patch/civetweb/0001-Allow-extended-ASCII-characters-in-URIs.patch
src/api/docs/content/specs/search.yaml
src/api/search.c
src/webserver/civetweb/civetweb.c
test/test_suite.bats

Lowercase domains passed to `GET /api/search/{domain}` and convert them to punycode (if applicable), e.g., `GET /api/search/äBC.cOm` (mind the Umlaut `ä`) will now actually trigger a search for `xn--bc-uia.com`
---
4. It is …

/api/search/{domain}: Add IDN compatibility

---

patch/sqlite3/0001-print-FTL-version-in-interactive-shell.patch
src/database/shell.c
src/database/sqlite3.h

Update embedded SQLite3 engine to version 3.44.0. There isn't anything in here that is of immediate use for Pi-hole.
**CHANGELOG**
1. [Aggregate functions](https://sqlite.org/lang_aggfunc.html) can now include an ORDER BY clause after their last parameter. The arguments to the function are processed in the order specified. This can be important for functions like [string_agg()](https://sqlite.org/lang_aggfunc.html#group_concat) and [json_group_array()](https://sqlite.org/json1.html#jgrouparray). 
2. Add support for the [concat()](https://sqlite.org/lang_corefunc.html#concat) and [concat_ws()](https://sqlite.org/lang_corefunc.html#concat_ws) scalar SQL functions, compatible with PostgreSQL, SQLServer, and MySQL. 
3. Add support for the …

Update embedded SQLite3 engine to version 3.44.0

---

src/config/config.c
src/daemon.c
src/daemon.h

Check that IPv6 support is not disabled either via the boot command line or at runtime (via `/etc/sysctl.conf`) before trying to launch the webserver for the first time. This will only set the ports once on the very first start of Pi-hole v6.0 and can be freely edited in `/etc/pihole/pihole.toml` (`webserver.ports`) to whatever the user deems appropriate.
Hint: This will typically disable binding to IPv6 in `docker` containers as they most often have `net.ipv6.conf.all.disable_ipv6 = 1`
--- …

Only use IPv6 in the webserver when available

---

src/api/2fa.c

A very simple change, fixes #1729 
--- …

Use webserver.domain as "account" in the TOTP QR code

---

src/capabilities.h
src/config/cli.c

Suggest using `sudo` if insufficient permissions to edit the config file were detected
---
--- …

Suggest sudo for pihole-FTL --config changes

---

src/api/search.c

Fix `free()` being used in the wrong place. It should only be called here when we have to exit early. Otherwise, it is called at the end of the function because we may want to use it later on:
--- …

Fix free() being used in the wrong page

---

src/FTL.h
src/syscalls/free.c
src/syscalls/syscalls.h

This PR extends `free()` to always set `free`'d pointers to `NULL`. This will effectively avoid future `double free`-related exceptions and prevent crashes like the recently fixed one (#1742).
--- …

NULL after free()

---

src/api/config.c
src/config/config.c
src/config/config.h

Changing `dns.hosts` does not need a full FTL restart but only a cache flush and re-read of `custom.list`
--- …

Changing dns.hosts does not need a restart

---

src/api/2fa.c
src/api/api.h
src/api/auth.c
src/api/auth.h
src/api/docs/content/specs/auth.yaml
src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/database/session-table.c
src/database/session-table.h
test/api/libs/responseVerifyer.py
test/pihole.toml

Make number of maximum concurrent API sessions adjustable via `webserver.api.max_sessions` defaulting to 16 (as before this change). This PR also fixes a small glitch in the API verifier that lost the ability to detect properties returned by FTL but not documented. This bug was introduced when adding the ability to check arrays as we implemented a workaround that had adverse effects. Arrays are not handled as first-class YAML citizens and can hence be checked as well.
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), …

Make number of maximum concurrent API sessions adjustable

---

src/webserver/x509.c

See title, this is the result of https://github.com/pi-hole/FTL/pull/1744#pullrequestreview-1725644799
```
$pihole-FTL --gen-x509 /tmp/test.pem && pihole-FTL --read-x509 /tmp/test.pem
[...]
issued  on        : 2023-11-10 22:17:27
expires on        : 2053-11-10 22:17:27
[...]
```
--- …

Create dynamic validity period when generating X.509 certificate

---

src/database/gravity-db.c

Fix domain modification. The `UNIQUE` key in the `domainlist` table is the combination of `domain,type`, not `domain` alone so you can add the same domain, e.g. once as allowed and once as denied entries and assign them to different clients using appropriate groups.
This PR fixes the error
```
ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint in "INSERT INTO domainlist (domain,type,enabled,comment) VALUES (:item,:type,:enabled,:comment) ON CONFLICT(domain) DO UPDATE SET type = : (1)
```
also shown in https://github.com/pi-hole/web/pull/2808
---
---
1. I have …

Fix domain modification

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/config/dnsmasq_config.c
test/pihole.toml

Add a new config option `misc.etc_dnsmasq_d` to allow setting whether files in `/etc/dnsmasq.d` are loaded as additional config files for Pi-hole.
This resolves two long standing issues
1. with Pi-hole not being compatible with software that installs custom files with conflicting lines in this directory (e.g.,` lxd`, [example reference](https://discourse.pi-hole.net/t/dns-service-is-not-running-ubuntu-19-10/30157/5?u=dl6er)) as well as
2. improving the coexistence of Pi-hole with an already running `dnsmasq` on the host as - by default - we won't share any config files in the future (no reference needed)
This change also goes hand-in-hand with [a recently discovered issue](https://discourse.pi-hole.net/t/ftl-failed-to-start-due-to-duplicate-cname-at-line-1-of-etc-dnsmasq-d-05-pihole-custom …

Make inclusion of /etc/dnsmasq.d/*.conf files configurable

---

src/config/config.c

As per what the title of this PR says. I went through all the 130 config items and found that we were missing this in a few places. The basic rule is that every `dnsmasq`-config related change does need a restart as well as every webserver related change does. I furthermore added `advanced setting` to `misc.dnsmasq_lines` because it really is.
Fixes #1748 
---
---
2. …

Add "requires restart" for config items where it is missing

---

src/config/dnsmasq_config.c

As the title says. Only formatting of the `dnsmasq.conf` file.

Improve readability of `dnsmasq.conf` by adding blank lines to group similar settings

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/config/dnsmasq_config.c
src/config/toml_writer.c
src/setupVars.c
test/pihole.toml

See title. This is to avoid confusion. Even when it is primarily being used when DHCP is enabled, it can also be used by DNS server features like `dns.expandHosts`. It was probably not the idea to move the setting into `[dhcp]` which is why I move it to `[dns]` now.
~~Note that there is no migration strategy here as it would required adding quite a bit of code to FTL (unknown config options are automatically cleaned from the file) and additional PRs in the future to remove this extra code. Seems fine to me during the beta phase and something that should definitely be done before the release.~~
If `dhcp.domain` was set, it will be migrated to `dns.domain`. This code can be removed in some future iteration of the beta (or even after release, if we forget).
**Related issue or feature (if …

Move dhcp.domain -> dns.domain

---

src/config/dnsmasq_config.c

Remove some addtional spaces. No functional changes, only for the eye.

Remove additonal spaces in dnsmasq.conf

---

src/api/config.c
src/config/cli.c
src/config/dnsmasq_config.c
src/config/dnsmasq_config.h

Use `hostsdir` for `custom.list` to avoid cache flushing on changes. When adding a domain into the empty list, the expected output in `pihole.log` is:
```
Nov 13 09:56:00 dnsmasq[1761111]: inotify: /etc/pihole/hosts/custom.list new or modified
Nov 13 09:56:00 dnsmasq[1761111]: read /etc/pihole/hosts/custom.list - 2 names
```
when removing it again:
```
Nov 13 09:56:34 dnsmasq[1761111]: inotify: /etc/pihole/hosts/custom.list new or modified
Nov 13 09:56:34 dnsmasq[1761111]: inotify: flushed 2 names read from /etc/pihole/hosts/custom.list
Nov 13 09:56:34 dnsmasq[1761111]: read /etc/pihole/hosts/custom.list - 0 names
```
The DNS cache stays intact across these events.
It is expected to see two instead of one domain being added above if `dns.expandHosts` is `true` as each HOSTS entry actually …

Use hostsdir for custom.list to avoid cache flushing on changes

---

src/config/config.h
src/config/toml_helper.c
src/config/toml_writer.c
src/daemon.c
src/daemon.h
src/dnsmasq/dnsmasq.c
src/main.c
test/api/libs/responseVerifyer.py
test/pihole.toml
test/test_suite.bats

Declare `pihole.toml` as UTF-8 document. we add a compile-time switch to use ASCII with UTF-8 escaping instead in case this is a necessity for anyone. We are in the third millennium A.C. but we also know people are still using Windows XP on the web...
---
3. I am willing to help maintain this change if there are …

Declare pihole.toml as UTF-8 document

---

src/api/list.c
src/webserver/http-common.c

Don't call `cJSON_free()` unconditionally on errors in `api_list_write()`. This PR fixes the crash reported in https://github.com/pi-hole/web/issues/2834 and can easily be reproduced by adding an invalid regex like
```
google{1
```
The expected error response is:
---
3. I am willing to help maintain this change …

Prevent unconditional free on error reporting

---

src/api/config.c
src/api/docs/content/specs/config.yaml
src/config/cli.c
src/config/config.c
src/config/config.h
src/config/dnsmasq_config.c
src/config/toml_helper.c
test/api/libs/responseVerifyer.py
test/pihole.toml

1. Only add `dhcp.leaseTime` if it is a non-empty string. By default it is non-empty, however we have seen users making it empty.  If empty, the default lease time is one hour for IPv4 and one day for IPv6 (`dnsmasq` defaults, see their man page).
2. Add new option `dhcp.netmask` defaulting to `0.0.0.0` (auto-discovery as before this PR) but freely settable to, e.g. `255.255.0.0` to make a `/16` DHCP network
3. Add API string verification for IPv4 and IPv6 addresses. As `ipv4` and `ipv6` are not standardized `format` properties, we add them as a `x-format` instead. However, since `swagger-api` [supports them](https://github.com/swagger-api/swagger-ui/pull/5033) there is some hope this will end up in a future revision of the OpenAPI standard. Even if not, having the verification using a …

Improve DHCP handling

---

src/config/dnsmasq_config.c
src/config/toml_helper.c
src/config/toml_helper.h
src/config/toml_reader.c
src/config/toml_writer.c
src/files.c
src/files.h
test/run.sh
test/test_suite.bats

Do not rewrite config files if they are unchanged. This PR implements this for
- `/etc/pihole/pihole.toml`
- `/etc/pihole/dnsmasq.conf`
- `/etc/pihole/custom.list`
The goal is to effectively preserve a larger number of config file backups as needless rotations (without any changes) are prevented.
---
3. I am …

Do not rewrite config files if unchanged

---

src/database/gravity-db.c

The group table's column is called "description" but we expose it in the API as "comment". Adjust internally used SQL to translate between them (this was already implemented and working for comment editing).
This has been noticed during internal testing for https://github.com/pi-hole/web/pull/2851
Fixes https://github.com/pi-hole/FTL/issues/1762
---
2. I have …

Fix group comments

---

src/api/docs/content/specs/domains.yaml
src/api/list.c
src/tools/gravity-parseList.c
src/tools/gravity-parseList.h

See title. Fixes #1760 
Current `development-v6` will allow you to add any string as domain, this PR validates domains before adding them.
---
--- …

Validate domains before adding them to the database via /api/list

---

src/api/list.c
src/database/network-table.c
src/database/network-table.h
src/database/sqlite3-ext.c

Add ability to get most recent client hostname from network table if specified by MAC address
Fixes https://github.com/pi-hole/FTL/issues/1768
---
--- …

/api/client: Include hostnames of clients specified by MAC

---

patch/sqlite3/0001-print-FTL-version-in-interactive-shell.patch
src/database/shell.c
src/database/sqlite3.h

Update embedded SQLite3 engine to version 3.44.1 released **today**.
1. Change the [CLI](https://sqlite.org/cli.html) so that it uses UTF-16 for console I/O on Windows. This enables proper display of unicode text on old Windows7 machines. 
2. Other obscure bug fixes. 
---
--- …

Update embedded SQLite3 engine to version 3.44.1

---

src/config/inotify.c
test/test_suite.bats

This is a regression of https://github.com/pi-hole/FTL/pull/1746. Before, we wrote directly to `pihole.toml` triggering a `CLOSE_WRITE` event in `inotify`. Now we, instead, first write to `pihole.toml.tmp`, compare it with `pihole.toml` and either *replace* `pihole.toml` (`MOVE` event) or simply discard `pihole.toml.tmp` not touching `pihole.toml` at all.
The `inotify` watching was configured to *only* monitor writing events but not the replacement due to `move`. I also refined the debug printing to instead log more explicitly:
```
2023-11-22 20:58:50.826 File moved from: /etc/pihole/pihole.toml.tmp
2023-11-22 20:58:50.826 File moved to: /etc/pihole/pihole.toml
```
**Pull request in [docs](https://github.com/pi-hole/docs) with …

Inotify: Watch for config file MOVED_TO

---

src/api/docs/content/specs/logs.yaml
src/api/logs.c

Include PID of the currently running FTL instance in the logs response. This allows clients to easily detect when FTL is restarted to reset their `nextID` to zero.
This is PR is part of a bug fix fixing that no new log lines are shown after FTL restarts as `nextID` was not reset.
---
--- …

Include PID in /api/logs

---

src/api/stats.c

Clients with zero queries should not be returned
---
--- …

API: Clients without queries should not be included

---

src/config/config.c

See title. Rumors are getting louder that a default session validity of only 5 minutes will not be enough for the everyday usage of Pi-hole. Hence, we increase the default to 30 minutes. This will only affect new installations/upgrades after this PR has landed in `development-v6`.
---
--- …

Increase default value of webserver.session.timeout to 30 min

---

src/config/config.c
test/pihole.toml

See title. When you see it, it will be immediately clear. It is a copy-paste error for the setting immediately above (`webserver.api.excludeClients`).
---
--- …

Minor config comment fix

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/config/toml_writer.c
test/pihole.toml

https://github.com/pi-hole/FTL/pull/1739 has been merged > two weeks ago. This PR fixes https://github.com/pi-hole/FTL/issues/1753
---
---
5. I …

Remove deprecated dhcp.domain setting

---

src/database/shell.c
src/database/sqlite3.h

1. Fix a mistake in the [CLI](https://sqlite.org/cli.html) that was introduced by the fix (item 15 above) in 3.44.1. 
2. Fix a problem in FTS5 that was discovered during internal fuzz testing only minutes after the 3.44.1 release was tagged. 
3. Fix incomplete assert() statements that the fuzzer discovered the day after the previous release. 
4. Fix a couple of harmless compiler warnings that appeared in debug builds with GCC 16. 
Note: we are not affected by no. 1 as it only affects native Windows binaries ([commit](https://www.sqlite.org/src/info/ce542fee6f0150bb))
---
1. I …

Update embedded SQLite3 engine to version 3.44.2

---

src/database/message-table.c

Fixes the link from the message table about inaccessible list to the (ad)list table after the file was renamed in https://github.com/pi-hole/web/pull/2756
--- …

Fix link from message table to list table

---

src/config/config.c
src/config/dnsmasq_config.c

Query cache optimizer: If a DNS name exists in the cache, but its time-to-live has expired only recently, the data will be used anyway (a refreshing from upstream is triggered).
Currently, zero means something else in Pi-hole and `dnsmasq`. In the world of `dnsmasq`, it means "serve forever" but Pi-hole does not allow this because it will inevitably lead to issues. In PI-hole's world, a value of zero actually means "disabled". Looking at this choice again, it seems quite confusing that we have deviating behavior from `dnsmasq`.
As solution, we allow negative values for `dns.cache.optimizer` where anything negative will disable the feature. We furthermore extend the text describing this setting to make this clear.
--- …

Disable cache optimizer for any negative TTL

---

.gitignore

This PR adds a few more files I found on my local installation to the `.gitignore` file
---
--- …

Add missing bits to the .gitignore file

---

src/args.c
src/tools/gravity-parseList.c

See title. This PR fixes https://github.com/pi-hole/FTL/issues/1783 by escaping non-printable characters possibly found in user-supplied files. We had to switch from using `strcmp` to `memcmp` as, otherwise, `\0` character contained in the strings would not make their way into the invalid domains display.
Using the [hosts3.csv](https://github.com/pi-hole/web/files/13464821/hosts3.csv) list provided by @Willem60 in https://github.com/pi-hole/FTL/issues/1783 and increasing the shown number of invalid domains from 5 to 10 now shows:
```
[i] Target: https://github.com/pi-hole/web/files/13464821/hosts3.csv
[✓] Status: No changes detected
[✓] Parsed 1136005 exact domains and 0 ABP-style domains (blocking, ignored 156 non-domain entries)
Sample of non-domain entries:
- www..am
- cdn..am
- …
```

Escape invalid domains possibly containing control characters

---

src/gc.c

Never recycle aliasclients. As they are not directly referenced by queries (but only indirectly by other clients), it is not easy to decide if they can be removed. However, since aliasclients are always manually administered through the database, their number should anyway be limited and it is fine to have them life forever.
This is a edge-case regression of https://github.com/pi-hole/FTL/pull/1694
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base …

Never recycle alias-clients

---

src/api/queries.c

Server side sorting of the query log was added by https://github.com/pi-hole/FTL/pull/1660.
Not all options are used right now. However, event the unused should match what we have on `web`. `regex.id` was not used in `ftl` not `web`. Changing it to `regex_id` which is wildly used.
--- …

Use regex_id instead of regex.id for query log sorting

---

src/args.c

This is the v5 backport of #1819. All info therein. We will not add CI tests here but have them in the other PR.
---
--- …

Add pihole-FTL sqlite3 -ni

---

src/database/network-table.c

Fix possible race-collision leading to a theoretical out-of-bounds read
--- …

Fix possible crash with high client activity

---

src/dnsmasq_interface.c

See #1807 - this is a backport of the feature for FTL v5.
Allows for fine grained application of the "special" domains that manage Apple Private Relay and Firefox Canary domains. When you apply them only to one group this effectively disables the special handling for this group while it stays intact for the rest or your network.
---
---
2. I have commented my proposed …

Implement special domains whitelisting

---

src/dnsmasq_interface.c
test/gravity.db.sql
test/test_suite.bats

Change priorities such that special domains (Firefox and Apple at this time) can be explicitly allowed for some clients (per group assignments) while they stay blocked for all others in the network. 
See related [Discourse thread](https://discourse.pi-hole.net/t/icloud-private-relay-problems/66764) for context of this change.
---
---
2. I have commented my proposed …

Implement special domains allowing

---

src/database/gravity-db.c

Do not check errors on `ROLLBACK TRANSACTION` when `gravityDB_delFromTable()` fails. We remove this to avoid overwriting the initial cause of the error. See linked Discourse thread for context.
Additional context from [the SQLite3 documentation](https://www.sqlite.org/lang_transaction.html):
> [!TIP]
> 3. Response To Errors Within A Transaction
>
> If certain kinds of errors occur within a transaction, the transaction may or may not be rolled back automatically. The errors that can cause an automatic rollback include:
>
> *   [SQLITE_FULL](https://www.sqlite.org/rescode.html#full): database or disk full
> *   [SQLITE_IOERR](https://www.sqlite.org/rescode.html#ioerr): disk I/O error
> *   [SQLITE_BUSY](https://www.sqlite.org/rescode.html#busy): database in use by another process
> * …

Do not overwrite errors on ROLLBACK

---

.github/workflows/build.yml

https://github.com/actions/download-artifact v4.10. added the ability to download multiple artifacts by "pattern" and merge them into a single output directory. This simplifies the artifact download step.
---
5. I have …

Simplify artifacts download

---

src/database/query-table.c
src/datastructure.c
src/datastructure.h
src/dnsmasq_interface.c
src/gc.c
src/log.c

This PR completes what was started in #1694 - memory recycling. The issue at hand was caused by adding the facility to recycle DNS cache records but then never actually doing it. The missing bits are added in this PR.
This fixes an issue described on Discourse (see link below): After a certain time has passed, clients and domains may be recycled, however the cache records saying that "clientID=123,domainID=234 -> blocked" remained. This was harmless *until* a new (possibly but not necessarily the old) client/domain combination in exactly this configuration appeared which then lead to a cached reply which was actually intended for something entirely different.
This is fixed by recycling cache records as soon as they are not referenced by any query. This is similar to how we recycle clients …

Implement DNS cache recycling

---

src/api/docs/content/specs/clients.yaml
src/api/docs/content/specs/domains.yaml
src/api/docs/content/specs/groups.yaml
src/api/docs/content/specs/lists.yaml

Fix one-of definition in `clients`, `domains`, `groups`, and `lists` `POST` request payloads.
Exemplary previous/after screenshot:
Fixes #1834
---
--- …

Fix one-of definition in clients, domains, groups, and lists POST

---

src/api/list.c

See title, this adds what is already documented but wasn't actually provided by FTL:
---
--- …

Add Location header for newly created groups/clients/domains/lists

---

src/api/auth.c
test/api/libs/FTLAPI.py

Implement authentication via query string, i.e., like
```
curl http://pi.hole/api/info/version?sid=%2FodNaBgsMlSwAspmw25t0g%3D
```
The `sid` should be URL-encoded for most applications (like `python3 requests` or `curl`).
---
4. It …

Add authentication via query string

---

src/api/auth.c
src/api/config.c
src/api/dhcp.c
src/api/docs/content/specs/auth.yaml
src/api/docs/content/specs/clients.yaml
src/api/docs/content/specs/config.yaml
src/api/docs/content/specs/dhcp.yaml
src/api/docs/content/specs/domains.yaml
src/api/docs/content/specs/groups.yaml
src/api/docs/content/specs/info.yaml
src/api/docs/content/specs/lists.yaml
src/api/docs/content/specs/network.yaml
src/api/info.c
src/api/list.c
src/api/network.c
src/config/cli.c
src/config/password.c
src/config/password.h
src/database/gravity-db.c
src/database/gravity-db.h
src/database/message-table.c
src/database/message-table.h
src/database/network-table.c
src/database/network-table.h
src/dnsmasq_interface.c
src/webserver/json_macros.h

The `DELETE` endpoints should return 204 when something was deleted and 404 is nothing was found at this resource. This PR follows a discussion in #1833 
See here the result of triggering to identical `DELETE` for a blocked domain. The first one got deleted fine (204), the second one errored because the requested resource wasn't there (we delete it before):
---
---
2. …

Fix DELETE API endpoints return codes

---

src/dnsmasq/dnsmasq.c
src/signals.c
src/signals.h

See title. When FTL is restarted using, e.g., `sudo system pihole-FTL restart` the new log looks like:
```
2023-12-23 16:00:47.926 [2260911M] INFO: Asked to terminate by "/lib/systemd/systemd --system --deserialize 56" (PID 1, user root UID 0)
```
---
---
3. I am willing to help maintain this change if there are …

If someone terminates FTL, try to obtain who is the murderer and log it

---

.devcontainer/devcontainer.json
.github/Dockerfile

Use latest `ftl-build` container to pick up both the most recent `Alpine` version as well as the updated `libreadline`
---
---
5. I have …

Update ftl-build container to v2.5

---

src/database/shell.c
src/database/sqlite3.h

Update embedded SQLite3 to 3.45.0. There is nothing of particular interest for Pi-hole itself in this release.
1. Added the [SQLITE_RESULT_SUBTYPE](https://sqlite.org/c3ref/c_deterministic.html#sqliteresultsubtype) property for [application-defined SQL functions](https://sqlite.org/appfunc.html). All application defined SQL functions that invokes [sqlite3_result_subtype()](https://sqlite.org/c3ref/result_subtype.html) must be registered with this new property. Failure to do so might cause the call to sqlite3_result_subtype() to behave as a no-op. Compile with [-DSQLITE_STRICT_SUBTYPE=1](https://sqlite.org/compile.html#strict_subtype) to cause an SQL error to be raised if a function that is not [SQLITE_RESULT_SUBTYPE](https://sqlite.org/c3ref/c_deterministic.html#sqliteresultsubtype) tries …

Update embedded SQLite3 to 3.45.0

---

src/api/api.h
src/api/docs/content/specs/config.yaml
src/api/docs/content/specs/history.yaml
src/api/history.c
src/api/stats.c
src/config/config.c
src/config/config.h
src/datastructure.c
test/pihole.toml

Limit number of clients returned by the `/api/history/clients` endpoint to 20 (default value).
This can be overwritten at compile-time and at run-time using the query parameter `?N=...`
---
--- …

Limit number of clients returned by /api/history/clients

---

src/api/docs/content/specs/dhcp.yaml

Amend description of expiration field in `GET /dhcp/leases`: 0 means "infinite". No functional changes.
Accompanies but also independent of https://github.com/pi-hole/web/pull/2941
---
--- …

Amend description of expiration field in GET /dhcp/leases

---

src/args.c
src/config/config.c
src/daemon.c
src/daemon.h
src/database/network-table.c
src/dnsmasq_interface.c
src/resolve.c
src/resolve.h
test/test_suite.bats

More recent Pi-hole installations may not be using `127.0.0.1` in `/etc/resolv.conf` but something like `192.168.0.1` or even `9.9.9.9`. So far, FTL uses a hack that ensures that - whatever is set in `resolv.conf` - we are always enforcing the use of FTL as DNS resolver when doing internal name lookups.
This is meaningful as external servers would very likely have no idea about the internal network structure and could not provide useful answers. Assuming the router is used in typical at-home deployments, it may still work (partially, locally defined records would not be available, for instance) but if the system is even using an external server such as Quad9, no answer will be available.
When switching from `glibc` to `musl` we lost the hack FTL has been using for years to temporary …

Improve and fix host name resolution

---

src/database/sqlite3.h

CHANGELOG
1. Restore the [JSON BLOB input bug](https://sqlite.org/json1.html#jblobbug), and promise to support the anomaly in subsequent releases, for backward compatibility. 
2. Fix the [PRAGMA integrity_check](https://sqlite.org/pragma.html#pragma_integrity_check) command so that it works on read-only databases that contain FTS3 and FTS5 tables. This resolves an issue introduced in version 3.44.0 but was undiscovered until after the 3.45.0 release. 
3. Fix issues associated with processing corrupt [JSONB](https://sqlite.org/json1.html#jsonbx) inputs: 
1. Prevent exponential runtime when converting a corrupt JSONB into text. 
2. Fix a possible read of one byte past the end of the JSONB blob when converting a corrupt JSONB into text. 
3. Enhanced testing using …

Update embedded SQLite3 to 3.45.1

---

src/api/docs/content/specs/queries.yaml
src/api/queries.c
src/database/common.c
src/database/gravity-db.c
src/database/query-table.c
src/database/query-table.h
src/datastructure.c
src/datastructure.h
src/dnsmasq_interface.c
src/enums.h
src/regex.c
test/gravity.db.sql
test/test_suite.bats

> [!IMPORTANT] 
> This PR needs both core and web branches with the same name to work.
>
> Furthermore, you will have to run `pihole -g` at least once to upgrade your gravity database such that the list IDs become available for FTL. This should be done automatically during `checkout`/`update`.
Rename `query_storage.regex_id` to `query_storage.list_id` as it is already now used to also store exact matching `domainlist` entries by their ID. This commit further extends this to also store the (first) matching `anti-/gravity` list (if available).
---
---
1. I have read and understood …

Make adlist ID available, rename queries.regex_id -> queries.list_id

---

src/config/config.c

DNSSEC validation should not be enabled by default - it wasn't in v5, either. The reason for this is that it may be causing issues on devices with broken/missing RTCs where NTP time synchronization relies on DNS resolution
---
---
4. …

DNSSEC validation should not be enabled by default in v6

---

CMakeLists.txt
src/dnsmasq/forward.c

This PR imports https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commitdiff;h=1ed783b8d7343c42910a61f12a8fc6237eb80417:
> Replies from upstream with a REFUSED rcode can result in log messages stating that a resource limit has been exceeded, which is not the case.
and updates the version of the embedded `dnsmasq` server.
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/pihole-unbound-dnsmasq-validation-failed-resource-limit-exeeded/68388
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand …

Fix spurious "resource limit exceeded" messages

---

CMakeLists.txt
src/dnsmasq/forward.c

Backports https://github.com/pi-hole/FTL/pull/1892 to FTL v5.25 - aiming straight for a bugfix release.
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/pihole-unbound-dnsmasq-validation-failed-resource-limit-exeeded/68388
---
4. It is compatible …

Fix spurious "resource limit exceeded" messages (v5 backport)

---

src/api/docs/content/specs/lists.yaml
src/api/list.c
src/database/gravity-db.c
src/enums.h
test/test_suite.bats

Allow narrowing down the (ad)list type using the (optional) query parameter `?type={allow,block}`.
Accompanying change related to https://github.com/pi-hole/pi-hole/pull/5572. See reasoning therein.
This is a feature request submitted on Discourse (see link below).
> [!NOTE]
> This pull requests requires all three Pi-hole components to be checked out
> ```
> pihole checkout core tweak/allow_adlist_dups
> pihole checkout web tweak/allow_adlist_dups
> pihole checkout ftl tweak/allow_adlist_dups
> ```
> for testing
---
--- …

Allow adlist duplicates

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/database/query-table.c
test/pihole.toml

Add new config option `database.useWAL` defaulting to true making the use of the WAL journal optional for the on-disk query database. Reasons why this might be useful are given in the description of the new config option:
> **Should FTL enable Write-Ahead Log (WAL) mode for the on-disk query database (configured via files.database)?**
> It is recommended to leave this setting enabled for performance reasons. About the only reason to disable WAL mode is if you are experiencing specific issues with it, e.g., when using a database that is accessed from multiple hosts via a network share. When this setting is disabled, FTL will use SQLite3's default journal mode (rollback journal in DELETE mode).
This PR was initially triggered by [this Discourse …

Make WAL mode for pihole-FTL.db optional

---

.github/actions/build-and-test/action.yml
.github/actions/deploy/action.yml
.github/workflows/build.yml

**Extra short summary:** Reduced build time for almost all binaries from ~30 min to ~3 min
---
**Longer description:**
Building FTL binaries using `buildx` slowed down our CI to roughly 16 minutes per build. If builds sporadically fail, they are repeated and the build needs half an hour. This is quite some unfortunate situation as we need to wait half an hour after pushing a fix until a user can try it.
This PR changes how Pi-hole builds binaries on the CI. Before, we built (and tested!) all binaries in parallel using GHA runners (`x86_64`). Only once all of them were finished, the binaries were uploaded:
The new method has three partially independent branches:
1. We build `riscv64` on GHA runners
2. We build `x86_64` and `i386` in parallel on GHA runners
3. We build all `arm` binaries on …

Accelerate CI builds substantially

---

src/config/setupVars.c

Use correct variable when migrating possible `revServer` settings from `setupVars.conf` to the new multiple-servers-aware JSON string formulation
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/docker-pi-hole/issues/1550
--- …

Fix revServer importing from former setupVars.conf

---

src/config/config.c

https://github.com/pi-hole/FTL/pull/1773 recently added config validation enforcing every config option to have a validator assigned to it. After this PR was created, another https://github.com/pi-hole/FTL/pull/1868 added the new option `database.useWAL` which is now lacking such a validator, causing current `development-v6` builds to fail the tests. This PR fixes this.
--- …

Add missing validator for database.useWAL

---

src/api/queries.c

Add searching for domains and clients in the Query Log. Wildcards (*) are supported everywhere in the search string.
>[!NOTE]
> See https://github.com/pi-hole/web/pull/2980 for further details.
We do not add documentation to the API as this PR merely implements yet another piece of the extremely extensive server-side processing specification of [DataTables](https://datatables.net/).
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and …

Add searching for domains and clients in the Query Log

---

src/api/info.c

While testing various branches and avenues in Docker Desktop on windows - I note the message  "Cannot open /sys/class/hwmon..." pops up every now and again and can fill the log.
Suggested change is to move it to DEBUG_API, unless there is a reason that this should fill up the log when not detected?
Before
After
--- …

Demote hwmon warning log to debug

---

src/tools/gravity-parseList.c

Uncomment some previously commented out code that prevents domains from including upper case letters. See https://discourse.pi-hole.net/t/local-dns-settings-x-invalid-value/68985 for details
Before:
After:
--- …

Allow upper case letters in domains/hosts

---

src/config/env.c

Work on a copy of the env vars instead of using `strtok` (modifying the original string) to prevent issues down the line when FTL restarts internally and re-reads them.
---
--- …

Ensure env vars survive restart

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/config/dnsmasq_config.c
test/pihole.toml

See title. Relevant for debugging/tracing down DHCP issues with a much lower entrance barrier compared to running Wireshark capturing on a remote device (when your Pi-hole is a headless system).
This option default to `false` and be activated as any other config option, too, via
- the API, or
- the CLI (like `sudo pihole-FTL --config dhcp.logging true`), or
- direct interaction with `/etc/pihole/pihole.toml`, or
- by importing a teleporter file where this is already active.
---
**Related issue or feature (if applicable):** See Discourse thread mentioned below.
--- …

Add new dhcp.logging option

---

test/test_suite.bats

**No functional change**
This PR slightly simplifies the CI tests causing the RISCV64 builds to fail quite frequently. The reason for this is that a few character get lost on their way through the pipe between the testing fork and the controlling process. So far, I do not know why this is happening and first attempts to fix this have failed. When I can find more time to get a proper fix, we will restore this. Until then, this PR ensures we do not have to restart the CI tests a dozen times until they finally succeed by pure luck (because said bytes do not get lost).
This doesn't happen on any other architecture so it may even be a problem with our `qemu` emulation of the processor screwing something up.
--- …

Slightly simplify the CI tests

---

src/dnsmasq_interface.c

Mark query as allowed when antigravity matches to prevent further checks such as CNAME inspection. This ensures antigravity matches have similar effects than explicitly allowed domains.
---
--- …

Fix antigravity not preventing further checks on queries

---

src/api/auth.c
src/api/config.c
src/api/dns.c
src/api/list.c
src/api/search.c
src/api/teleporter.c
src/config/cli.c
src/database/gravity-db.h
src/database/message-table.c
src/dnsmasq/config.h
src/enums.h
src/webserver/http-common.c
src/webserver/http-common.h
src/webserver/json_macros.h
test/test_suite.bats

Ensure `cJSON` is used in a thread-safe manner and add CI tests ensuring this. Also ensure every JSON parsing is performing error checking and reduce some code duplication. No functional change.
---
--- …

Ensure thread-safety for cJSON engine

---

src/api/docs/content/specs/teleporter.yaml
src/api/teleporter.c
src/config/cli.c
src/webserver/http-common.c
src/webserver/json_macros.h
src/zip/teleporter.c
src/zip/teleporter.h

Add optional JSON object `.import` to `POST /api/teleporter` that allows the user to pick what is to be restored.
Fixes #1802
---
---
5. I have …

 Implement selective Teleporter restoring

---

src/api/docs/content/specs/teleporter.yaml
src/zip/teleporter.c
test/api/libs/responseVerifyer.py
test/test_suite.bats

See title.
---
---
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with- …

Be more verbose in which tables are imported during teleporter importing

---

src/database/message-table.c
src/files.c
src/log.c
src/log.h

Reintroduce a workaround for docker on macOS accidentally removed in bd266d6 and install proper safeguards around HTML escape code during message generation.
---
**Related issue or feature (if applicable):** #1925 
--- …

Fix disk space checking on macOS hosts

---

src/database/shell.c
src/database/sqlite3.h

This is a bug-fix patch release. Changelog below:
1. Fix a long-standing bug (going back to version 3.24.0) that might (rarely) cause the "old.*" values of an [UPDATE trigger](https://sqlite.org/lang_createtrigger.html) to be incorrect if that trigger fires in response to an [UPSERT](https://sqlite.org/lang_upsert.html). [Forum post 284955a3cd454a15](https://sqlite.org/forum/forumpost/284955a3cd454a15). 
2. Fix a bug in [sum()](https://sqlite.org/lang_aggfunc.html#sumunc) that could cause it to return NULL when it should return Infinity. [Forum post 23b8688ef4](https://sqlite.org/forum/forumpost/23b8688ef4). 
3. Other trifling corrections and compiler warning fixes that have come up since the previous patch release. See the [timeline](https://sqlite.org/src/timeline?from=version-3.45.2&to= …

Update embedded SQLite3 to 3.45.3

---

src/database/message-table.c

Fix a crash resulting from a bad interaction between PRs #1928 and #1930. The fix is very simple: #1928 made it unnecessary to specify the number of following arguments. Unfortunately, current `development-v6` misinterprets this causing a crash as reported in #1935 
**Related issue or feature (if applicable):** fixes #1935 
--- …

Fix a crash resulting from a bad interaction between PRs #1928 and #1930

---

src/api/api.c
src/api/auth.c
src/api/docs/content/specs/auth.yaml
src/webserver/http-common.h
src/webserver/lua_web.c
test/test_suite.bats

Improve debugging for users developing third-party applications/interfaces that need to authenticate with the Pi-hole API.
---
---
5. I have …

Provide human-readable message for session status

---

src/dnsmasq_interface.c

See title. This fixes an issue reported on Discourse (see below).
**Related issue or feature (if applicable):** [Discourse topic](https://discourse.pi-hole.net/t/periodic-connection-errors-in-diagnostics-failed-to-send-tcp-read-write-to-127-0-0-1-5335/69961/)
---
4. It is compatible …

Improve error logging when TCP connections are prematurely closed by remote server

---

src/api/docs/content/specs/clients.yaml

Documentation-only change for API `/clients`: Add note that `{client}` needs to be URI-encoded (if specified) and add documentation of read-only optional `{name}` field.
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/1943
---
4. It is …

Improve API /clients documentation

---

src/dnsmasq/log.c

Fixes a bug introduced in https://github.com/pi-hole/FTL/pull/1881 where fatal `dnsmasq` config line errors can lead to FTL crashing after logging that there is a fatal event. The expected behavior is to cleanly return an error code instead of crashing which is restored by this PR.
This small fix is meant to go out as **FTL v5.25.2**
---
**Related issue or feature (if applicable):** Fixes #1942 
---
2. I have …

Exit after fatal dnsmasq errors

---

src/database/common.c
test/test_suite.bats

See title. Fixes https://github.com/pi-hole/pi-hole/issues/5569
---
**Related issue or feature (if applicable):** https://github.com/pi-hole/pi-hole/issues/5569
--- …

Change database permissions to -rw-r----- (640)

---

src/webserver/cJSON/cJSON.c
src/webserver/cJSON/cJSON.h

Update bundled cJSON from 1.7.17 -> 1.7.18 released [earlier today](https://github.com/DaveGamble/cJSON/releases/tag/v1.7.18)
Changelog:
- Add `NULL` check to `cJSON_SetValuestring()` (CVE-2024-31755)
- Fix heap buffer overflow
- Set free'd pointers to `NULL` whenever they are not reassigned immediately after
----
---
2. I have commented my proposed changes within the …

Update bundled cJSON

---

src/FTL.h
src/database/query-table.c

Improve query storing algorithm to better cope with bursts of queries of arbitrary size and frequency. See related Discourse bug chasing for further details.
This is overall an improvement as the new strategy guarantees that no queries can be lost on one hand and drastically reduces the workload on the other hand by using persistent prepared statements instead of compiling them once per second.
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my …

Fix spilled queries in database

---

src/zip/teleporter.c

While browsing through the code I noticed this:
```c
// Add /etc/pihole/dhcp.lease to the ZIP archive if it exists
file_comment = "DHCP leases file";
file_path = "/etc/pihole/dhcp.leases";
if(file_exists(file_path) && !mz_zip_writer_add_file(zip, file_path+1, file_path, file_comment, (uint16_t)strlen(file_comment), MZ_BEST_COMPRESSION))
{
mz_zip_writer_end(zip);
return "Failed to add /etc/hosts to heap ZIP archive!"; // <--- definitely should not mention /etc/hosts here
}
```
This might lead to user confusion one day so it's better to correct it.
---
Corrects error message mentioning `/etc/hosts` instead of `/etc/pihole/dhcp.leases` in [teleporter.c:184](https://github.com/pi-hole/FTL/blob/development-v6/src/zip/teleporter.c#L184).
**How does this …

Fix error message mentioning wrong file

---

src/CMakeLists.txt
src/lua/ftl_lua.c

Readline detection/guarding has two small bugs. This merge request tries to fix them. No actual code was changed. This prevents compile errors when no readline was detected but `readline.h` is included.
--- …

Readline detection

---

.github/actions/build-and-test/action.yml
.github/workflows/build.yml

Creating a tamper-proof papertrail for all FTL binaries we build on Github Actions:
```
$ gh attestation verify pihole-FTL-amd64 -o pi-hole
Loaded digest sha256:67e7d2451a29ff3cd21c4a7c489ac4b1d43993f4a69bf9fbe989dda47f24685e for file://pihole-FTL-amd64
Loaded 1 attestation from GitHub API
✓ Verification succeeded!
sha256:67e7d2451a29ff3cd21c4a7c489ac4b1d43993f4a69bf9fbe989dda47f24685e was attested by:
REPO         PREDICATE_TYPE                  WORKFLOW                                                        
pi-hole/FTL  https://slsa.dev/provenance/v1  .github/workflows/build.yml@refs/heads/new/artifact_attestations
```
tested using `gh 2.49.2` on Ubuntu 24.04 LTS
---
**Pull request in [docs](https://github.com/pi-hole/docs) with …

Add artifact attestation

---

CMakeLists.txt
src/dnsmasq/dnsmasq.c

This PR adds a commit submitted to the `dnsmasq-discuss` mailing list. It has been verified by users to prevent use-after-free bugs possibly even resulting in a crash when names for meanwhile expired DHCP leases are queried via DNS PTR.
In case this patch is not accepted 1:1 for `dnsmasq` upstream, we can easily revert this PR later.
---
--- …

Update DNS records after pruning DHCP leases

---

src/CMakeLists.txt
src/args.c
src/lua/CMakeLists.txt
src/lua/ftl_lua.c
src/webserver/civetweb/CMakeLists.txt
src/webserver/webserver.c
src/webserver/x509.c
src/webserver/x509.h

- Properly guard X.509 functions to allow compiling FTL when `mbedTLS` library is **not** available on the host
- Enforce minimum version of mbedTLS (3.5.0)
Note: This PR fixes a harmless warning concerning `READLINE` introduced in #1956 
---
**Related issue or feature (if applicable):** #1966 
---
3. I am willing to help maintain this change if there are …

Fix compiling without mbedTLS

---

.github/.codespellignore
src/dnsmasq_interface.c

Always try to `chown` auxiliary database files, not only when `chown` of the database files itself failed. I simplified and re-arranged the code to reduce the nesting depth by up to two levels, making such issues easier to detect visually.
---
---
3. I am willing to help maintain this change if there are issues …

Fix chown of aux. database files

---

src/database/shell.c
src/database/sqlite3.h

Update embedded SQLite3 to 3.46.0 released earlier today.
*  Enhancements to the "`PRAGMA optimize`" command.
*  New capabilities in the date and time functions.
*  Added the `json_pretty()` SQL function.
*  Allow `_` separators in numeric literals, for human readability.
*  Query planner improvements
*  JSON processing improvements
1. Enhance [PRAGMA optimize](https://sqlite.org/pragma.html#pragma_optimize) in multiple ways, to make it [simpler to use](https://sqlite.org/lang_analyze.html#pragopt): 
1. PRAGMA optimize automatically implements a temporary [analysis limit](https://sqlite.org/pragma.html#pragma_analysis_limit) to prevent excess runtime on large databases. 
2. Added the new 0x10000 bitmask option to check for updates on all tables. 
3. Automatically re-analyze tables that do …

Update embedded SQLite3 to 3.46.0

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/config/dnsmasq_config.c
test/pihole.toml
test/run.sh
test/test_suite.bats

Add new `dhcp.ignoreUnknownClients` option which has been requested on Discourse. It works as follows:
This PR also features a second commit updating forgotten changes into `test/pihole.toml` and adds a CI test to prevent forgetting to update this file in the future.
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/add-checkbox-to-block-dhcp-for-unknown-hosts/70485
---
2. I have …

Add option to ignore unknown DHCP clients

---

src/args.c
src/database/network-table.c
src/resolve.c
src/resolve.h

This is a follow-up PR improving #1976 for edge-cases where upstream servers (can be local routers, especially in the context of conditional forwarding) are not capable to doing DNS over TCP. The PR changes the internal name resolver use UDP by default, but actively detect UDP DNS truncation (commonly seen in conjunction with DNSSEC) and appropriately fall back to TCP for corresponding queries.
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my …

Internal name resolution over UDP with fallback to TCP

---

src/database/message-table.c
src/regex.c

Current `development-v6` singles out regex warnings by the warning itself rather than the regex itself. This leads to the defect that multiple warnings get incorrectly summarized together when they are affected by the same warning.
How to reproduce:
Add domains via the `sqlite3` CLI to the `gravity.db` database, e.g.
``` sql
INSERT INTO domainlist (type,domain) VALUES (3,'[[[');
INSERT INTO domainlist (type,domain) VALUES (3,'[[[[');
INSERT INTO domainlist (type,domain) VALUES (3,'[[[[[');
INSERT INTO domainlist (type,domain) VALUES (3,'[[[[[[');
```
On `development-v6`: Only one entry is created in the diagnosis system
On this branch: All warnings are shown, e.g.,
We don't need to update anything in any other repo as FTL is now the only responsible player in generating messages. 
---- …

Fix incorrect unification of regex warnings

---

src/resolve.c

Fix very long DNS names (>64 bytes) potentially crashing the internal name resolving mechanism, the new limit is 256 bytes with proper boundary checking. No user reports are known. This came up during my regular [`valgrind`](https://docs.pi-hole.net/ftldns/valgrind/) checking of the `pihole-FTL` process. Looking at the `git blame` for this code, the broken code has been in there for half a year seemingly without anyone noticing it. Note that this bug affects only internal name resolution used by FTL to infer host names for clients and upstream servers. It is completely separated from normal DNS operation used by the clients in your network.
Heap overflows are exploitable in a different manner to that of stack-based overflows. Intentional exploitation is unlikely given ASLR ([Address Space …

Fix possible heap-corruption bug

---

src/webserver/webserver.c

Skip certificate domain check when TLS is not actually used even if a certificate is available
---
--- …

Skip certificate domain check when TLS is not actually used

---

src/database/gravity-db.c

Add checking of return status of `sqlite3_open_v2()` to ensure we are not trying to use the database when it failed to open (e.g., when it does not exist).
Errors on `development-v6`:
```
2024-06-06 06:48:34.042 CEST [2901888/T2901896] ERROR: SQLite3: cannot open file at line 44775 of [96c92aba00] (14)
2024-06-06 06:48:34.042 CEST [2901888/T2901896] ERROR: SQLite3: os_unix.c:44775: (0) open(/etc/pihole/gravity.db) -  (14)
2024-06-06 06:48:34.042 CEST [2901888/T2901896] ERROR: SQLite3: API call with unopened database connection pointer (21)
2024-06-06 06:48:34.042 CEST [2901888/T2901896] ERROR: SQLite3: misuse at line 142653 of [96c92aba00] (21)
2024-06-06 06:48:34.042 CEST [2901888/T2901896] WARNING: gravity_updated(): SELECT value FROM info WHERE property = 'updated'; - SQL error …
```

Fix non-existing gravity.db issue

---

src/zip/gzip.c

Re-add support for Pogoplug by making the definition of `__USE_MISC` conditional (as it should always have been)
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/pi-hole-beta-6-0-on-pogoplug-pro/70643
--- …

(Re-)Add support for Pogoplug

---

src/config/password.c

This is especially worth adding in the context of forced passwords (via env var) as the password is always "set" on each config change. This PR effectively prevents FTL from wiping all sessions and forcing the user to re-login when changing even settings which are 100% unrelated to the API.
---
---
3. I am …

Check if the newly set password is the same as the old one

---

src/api/config.c

Fix the API hint as `/config/dnsmasq` does not exist anymore.
---
6. I have checked …

Fix API hint

---

src/api/config.c
src/api/docs/content/specs/config.yaml
src/config/cli.c
src/config/config.c
src/config/config.h
src/config/toml_writer.c
test/pihole.toml

Add new `misc.readOnly` config option to force the configuration to be read-only. It can only be modified through the config file but neither the API nor the CLI as long as read-only mode is enabled.
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/support-writing-to-pihole-toml-directly/70522/
--- …

 Add read-only config option

---

src/api/config.c
src/api/list.c
src/api/teleporter.c
src/webserver/http-common.c
src/webserver/http-common.h
src/webserver/lua_web.c

Log API Unauthorized warnings caused by `send_json_error()` only if `debug.api` is `true`.
---
--- …

Show Unauthorized warnings only in debug mode

---

src/config/dnsmasq_config.c
src/dnsmasq/option.c

Fix crash caused by double `free()` corruption encountered with `rev-server` addresses with prefix lengths `!= {8,16,24,32}`.
The patch submitted upstream is tracked here: https://github.com/pi-hole/dnsmasq/pull/15
We decide to merge this change now as nothing at all has happened on the mailing list for months by now and users came and asked for the status of our bug fix.
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/todays-update-kills-pihole-v6/70739
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire …

Fix rev-server crash

---

test/test_suite.bats

`fail*.dnssec.works` changed its configuration from being `BOGUS` to `ABANDONNED` and cannot be used any longer for `BOGUS` testing
---
---
5. …

Fix CI DNSSEC tests

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/config/dnsmasq_config.c
src/config/toml_helper.c
src/daemon.c
src/database/database-thread.c
src/database/message-table.c
src/database/query-table.c
src/database/query-table.h
src/dnsmasq/dnsmasq.c
src/dnsmasq_interface.c
src/enums.h
src/files.c
src/files.h
src/gc.c
src/ntp/client.c
src/ntp/ntp.h
src/ntp/rtc.c
src/ntp/server.c
src/resolve.c
src/shmem.c
src/signals.c
src/signals.h
src/timers.c
test/pihole.toml
test/test_suite.bats

Start NTP server thread(s) only after the first successful NTP time sync. This ensures the time we offer is correct. As a by-product this also gives some time for alternative NTP servers (e.g., `crony`) to finish their startup so we don't take the port before they can do it. Also, disable DNSSEC time-windows validation until first sync succeeded to avoid DNSSEC-related issues during NTP sync.
If the time is updated by a large amount, restart FTL to ensure we load the correct history window.
---
--- …

Improve NTP implementation

---

src/api/dns.c

Restart timer if set even if no blocking mode change was requested. This allows users to extend a temporary state, e.g. by running another "pihole disable 5m" shortly before the previous call reaches timeout. Previously, calling "pihole disable 1m" would make the change permanent which seems undesirable.
This has been discovered while testing https://github.com/pi-hole/pi-hole/pull/5689/commits/897e23089c10a6ac8c7c51dbfe5c897c7051c22c (part of https://github.com/pi-hole/pi-hole/pull/5689)
---
--- …

Fix blocking timer

---

test/pdns/pdns.conf
test/pdns/recursor.conf
test/pdns/setup.sh
test/test_suite.bats

See title. This is implemented by defining two internal DNSSEC zones in our CI tests - one for which we add the trust-anchor (`SECURE`) and one were not (`BOGUS`). This is a final solution to the recurring issues we have every now and then with external DNSSEC providers. The entire code is dynamic, i.e., the zones are always newly created so there are no problems with expiry, etc.
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and …

Self-contained DNSSEC CI tests

---

src/config/dnsmasq_config.c

Earlier today, the IANA published the 2024 KSK:
[![grafik](https://github.com/user-attachments/assets/5b039be6-a3c5-48e7-95a7-aed2d825e41a)](https://www.iana.org/reports/2024/root-ksk-2024.pdf)
https://www.iana.org/reports/2024/root-ksk-2024.pdf
The currently used root key `20326` has no expiry, however, there are unconfirmed rumors that the currently used key will be rolled over late 2025 or 2026.
We should definitely add it already now, cfm. the DNS KSK procedures:
> Key distribution is REQUIRED to occur promptly after each Key Generation Ceremony. It MUST be completed before any key is taken into its Operational Period.
---
---
**By …

Add new 2024 DNS root trust anchor

---

src/database/common.c
src/database/network-table.c
src/database/query-table.c
src/dnsmasq/dhcp.c
src/dnsmasq/dnsmasq.c
src/dnsmasq/dnsmasq.h
src/dnsmasq/forward.c
src/dnsmasq/rfc1035.c
src/dnsmasq_interface.c

This PR improves the automagic PTR generation code. So far, we ensures that there is always a certain PTR in the cache we can set to whatever we deem appropriate to ensure Pi-hole replies with "`pi.hole`" (or whatever the user wants - there is a configuration setting for controlling this) on all interface addresses the machine running Pi-hole has.
For three years we have been reusing always the same PTR record and replaced in during runtime with whatever we needed, e.g., `PTR 1.0.168.192.in-addr.arpa -> pi.hole`, then on the next query to the another address, we freed this and inserted `PTR 1.0.0.10.in-addr.arpa -> pi.hole` instead.
The new way of doing this is simply adding suitable PTR records whenever they are needed in a linked list and *not* free previous entries. This has the …

Improve automatic PTR handling code

---

src/api/stats.c

Fix value overflow (`2^16 - 1 = 65535`) in `get_top_upstreams()` due to `in_port_t` being an unsigned 16 bit integer where we need a signed data type. This is a regression of #2001
---
**Related issue or feature (if applicable):** See linked Discourse discussion
---
4. It is …

Fix port 65535 for virtual cache and blocklist upstreams

---

src/config/toml_reader.c
src/daemon.c
src/dnsmasq/util.c
src/log.c
src/main.c
src/procps.c
src/procps.h
src/shmem.c
src/shmem.h
test/test_suite.bats

FTL is trying hard to prevent you from starting another instance of itself. It does so by creating a PID file in `/run/pihole-FTL.pid` and checking for its existence. If the file is present, FTL assumes that another instance is already running and exits. It also checks for the existence of the shared memory objects `/dev/shm/FTL-*` and exits if they are present.
These checks can be fooled by manually removing the PID file or shared memory objects (needs `root` privileges). This can lead to multiple instances of FTL running at the same time, which can cause various issues. The most commonly seen issue is that, when the first process needs more memory, its original shared memory objects are already gone. Hence, it actually tries to resize the shared memory objects of the second instance …

Improve pihole-FTL process concurrency

---

src/ntp/client.c

Directly specify NTP port instead of service by name. Having checked the actual implementation of `getaddrinfo()`, we see that this avoids iterating over /etc/services ensuring we don't get "Unknown service" errors on systems that - for any reason - either lack the file or somehow lack the particular NTP service line.
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/cannot-resolve-ntp-server-address-unrecognized-service/71653
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to …

 Fix NTP synchronization on devices not knowing the NTP service type

---

patch/sqlite3/0001-print-FTL-version-in-interactive-shell.patch
src/database/shell.c
src/database/sqlite3.h

Update embedded SQLite3 engine to 3.46.1 released today. None of the mentioned points in the changelog apply to how Pi-hole uses SQLite3 but we may still benefit from "other minor fixes".
--- …

Update embedded SQLite3 engine to 3.46.1

---

src/config/config.c
src/config/toml_helper.c

Improve behavior on systems where mandatory config file locations aren't present (initial install interrupted/not completed)
---
5. I have …

Improve incomplete installations support

---

src/procps.c

Do not refuse to (re)start if there is another pihole-FTL process already running *inside* a docker container on the same host.
Currently, (re)starting on the host is prevented when FTL detects during startup that another process is running on the machine (the one inside the container) even when they can obviously run alongside perfectly fine. This is caused by the host being able to see *all* processes, not only the one in its own container, i.e., in [its own `cgroup`](https://docs.kernel.org/admin-guide/cgroup-v1/cgroups.html)*. This actually hinders development/testing natively on the host. 
This commit fixes this by not considering `pihole-FTL` processes running in downstream (!) docker containers as duplicate instances.
How can this be reproduced? After installing Pi-hole natively on …

Allow other FTL process inside docker

---

src/api/config.c
src/config/cli.c
src/config/config.c
src/config/config.h
src/config/legacy_reader.c
src/config/password.c
src/config/setupVars.c
src/resolve.c

This PR fixes a possible double `free`s that can crash FTL. It can happen when a client hostname contains invalid characters (e.g., spaces), reported and confirmed [here](https://discourse.pi-hole.net/t/pihole-6-0-beta-and-sqlite-issue/71586/26).
The issue we are dealing with here is ensuring that the `allocated = yes/no` for config strings has been checked at every location where memory is allocated and free'd. In some places, we had to change things to avoid memory being leaked.
---
**Related issue or feature (if applicable):** see above
--- …

Fix possible double-free and avoid memory leaking

---

.github/.codespellignore
src/api/docs/content/specs/config.yaml
src/api/padd.c
src/api/stats.c
src/config/config.c
src/config/config.h
src/datastructure.c
src/datastructure.h
src/dnsmasq/forward.c
src/dnsmasq/rfc1035.c
src/dnsmasq_interface.c
src/dnsmasq_interface.h
src/enums.h
src/gc.c
src/shmem.c
test/pdns/setup.sh
test/pihole.toml
test/test_suite.bats

Implement DNS caching for queries blocked upstream (`NXDOMAIN + no RA bit, `0.0.0.0/::`, and known Umbrella IP blocking pages) accompanied with suitable CI testing. This change improves handling of externally blocked queries in two ways:
1. Once we know the domain is externally blocked, we don't forward it again for the same client (it is currently forwarded each time)
2. We can recognize cache content with the specified addresses/flags as being upstream blocked and don't return them as "OK (cached)" through the API/in the database
---
---
1. I have read and understood the …

Implement DNS caching for queries blocked upstream

---

.github/Dockerfile

This PR updates GHA to the most recent container. This includes two major upgrades affecting the generated FTL builds:
1. Alpine Linux 3.19 -> 3.20.2 (`alpine:latest` as of today)
Nothing special in this release, however, v3.19 already stopped receiving bug fixes. v3.20 will be reach end-of-life at 2026-04-01. Individual points relevant for Pi-hole:
- LLVM 17 -> [18](https://releases.llvm.org/18.1.0/docs/ReleaseNotes.html) (only affecting the `clang` build), GCC stays at [13.2.1](https://gcc.gnu.org/gcc-13/changes.html)
- Python 3.11 -> [3.12](https://www.python.org/downloads/release/python-3120/) (only used during building Mbed TLS and for the Pi-hole API CI tests)
- 64 bit RISC-V is now supported in stable branches (we had use `:edge` for `riscv64` before)
3. Mbed TLS 3.5.0 -> 3.6.1 …

Use ftl-build:v2.7 builder for Actions

---

src/config/config.c
src/config/password.c

Very simple PR, fixes #2040
---
--- …

Restart FTL on change of webserver.api.cli_pw

---

src/api/docs/content/specs/stats.yaml
src/api/stats.c
src/database/gravity-db.c
src/database/gravity-db.h

Add `GET /api/stats/summary -> .gravity.last_update` timestamp exposing the last gravity update via the API.
This re-adds a functionality that was [implemented in PHP](https://github.com/pi-hole/web/blob/be05b0f61d3fcf796dae4cc3f89f8540b2359325/scripts/pi-hole/php/gravity.php) and - apparently - forgotten when porting all the functions over into the new v6 API.
```
d@r:~$ pihole api stats/summary
```
```
Requesting: GET http://localhost:80/api/stats/summary
Status: 200
Data:
{
"queries": {
"total": 83371,
"blocked": 2079,
"percent_blocked": 2.4936728477478027,
"unique_domains": 2077,
"forwarded": 61486,
"cached": 19594,
"types": {
"A": 44317,
"AAAA": 6610,
"ANY": 0,
"SRV": 15,
"SOA": 0,
"PTR": 452,
"TXT": 12,
"NAPTR": 0,
"MX": 0,
"DS": 1010,
"RRSIG": 0,
"DNSKEY": 29391,
"NS": 0,
"SVCB": …
```

Add GET /api/stats/summary -> .gravity.last_update

---

src/api/info.c
src/gc.c
src/webserver/webserver.c

Use total number of *configured* (= existing) cores rather then the number of available (= online and assigned) cores when computing the CPU utilization of the system. This fixes the displayed CPU % in case a container got fewer cores assigned to it than are available on the host system.
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/cpu-usage-is-wrong-shown-calculated-on-lxc-debian-container/71999
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and …

Fix CPU % calculation

---

src/api/history.c
src/config/setupVars.c

Make v5 -> v6 migration verbose by default (not only when `debug.config = true`). This will happen only once and may greatly ease debugging in case unintended side-effects (most often it will by typos in the old `setupVars.conf`).
---
---
3. I am willing to help maintain this change if there are issues with it …

Make v5 -> v6 migration verbose

---

src/config/config.c
src/config/dnsmasq_config.c
src/config/dnsmasq_config.h
src/config/setupVars.c

Migrate legacy files (`setupVars.conf`, `pihole-FTL.conf` and `custom.list`) into `/etc/pihole/migration_backup_v6` instead of leaving them inside `/etc/pihole` merely renaming them.
--- …

Migrate legacy files into /etc/pihole/migration_backup_v6

---

src/FTL.h
src/api/docs/content/specs/info.yaml
src/api/docs/content/specs/stats.yaml
src/api/info.c
src/api/stats.c
src/dnsmasq_interface.c
src/shmem.c
src/shmem.h

Add queries per second (QPS) metric exposed via `GET /api/stats/summary` as `.queries.frequency` and `GET /api/info/ftl` as `.query_frequency`. The QPS value is averaged over 30 seconds.
--- …

Add queries per second (QPS) metric

---

src/FTL.h
src/config/password.c
src/config/setupVars.c
src/config/toml_helper.c
src/signals.c
src/syscalls/free.c
src/syscalls/syscalls.h
src/webserver/webserver.c

Fix incorrect parsing when importing `REV_SERVER` from legacy `setupVars.conf` files.
--- …

Fix possible crash due to incorrect setupVars.conf import

---

src/api/action.c
src/api/api.c
src/api/config.c
src/api/teleporter.c
src/config/config.c
src/config/setupVars.c
src/daemon.c
src/main.c
src/ntp/client.c
src/signals.c
src/signals.h
src/webserver/http-common.h
src/zip/teleporter.c
test/test_suite.bats

Add missing import instruction for CNAME records file (if present in the archive)
**Related issue or feature (if applicable):** https://github.com/pi-hole/web/issues/2964
---
5. I have squashed …

Ensure v6 imports CNAME records when reading v5 archives

---

src/api/teleporter.c
src/config/config.c
src/config/config.h
src/config/dnsmasq_config.h
src/config/setupVars.c

Check and create v6 migration directory before trying to move/write files there. This involves config migrations but also Teleporter importing
---
**Related issue or feature (if applicable):** https://github.com/pi-hole/pi-hole/pull/5766
--- …

Check and create v6 migration directory if not exists

---

src/args.c
src/args.h

The previously described flags `--compress` and `--uncompress` never existed.
New help text:
---
--- …

Fix gzip help text

---

src/dnsmasq_interface.c

Move global cache status message into `debug.queries` mode instead of being a general `INFO` message.
--- …

Move debug message behind debug flag

---

.devcontainer/devcontainer.json
patch/lua.sh
patch/lua/0001-Add-bundled-script-loading-into-luaL_openlibs-to-mak.patch
patch/lua/0001-Increase-LUA_IDSIZE-so-that-long-script-filenames-as.patch
src/lua/ftl_lua.h
src/lua/linit.c
src/lua/lua.c
src/lua/luaconf.h
src/webserver/civetweb/mod_lua.inl
src/webserver/lua_web.c
test/broken_lua.lp
test/broken_lua_2.lp
test/run.sh
test/test_suite.bats

This PR is largely analogous to https://github.com/civetweb/civetweb/pull/1296. It adds the following extras specific to FTL:
- Increase LUA string buffer size from 60 to 256 characters. This is necessary as most standard Pi-hole scripts (in the already lengths path "/var/www/admin/scripts/pi-hole/") would otherwise exceed the buffer size and be printed in an abbreviated form in stack tracebacks.
- Load bundled scripts (to date, only `inspect`) in a better (more central) place where it is also imported for the web Lua environment.
---
**Related issue or feature (if applicable):** Fixes the issue discussed in https://github.com/pi-hole/web/pull/3143
---
**By submitting this pull request, I …

Fix Civetweb Lua error reporting issue

---

src/api/docs/content/specs/info.yaml
src/api/info.c
src/database/gravity-db.c
src/datastructure.c
src/enums.h
src/shmem.h

See title. Splits the currently existing `ftl.database.domains` (sums of exact and regex entries) into `ftl.database.domains` (domains only) and the newly added `ftl.database.regex` object.
---
--- …

Disentangle info/ftl database domain numbers

---

src/config/config.c
test/pihole.toml

See title. This fixes a regression of https://github.com/pi-hole/FTL/commit/e942301897840c5b9df19196d72c62ef87f17645 which needs a manual cache flushing after changing this setting.
---
--- …

Restart FTL to enforce flushing the cache when dns.piholePTR is changed

---

src/gc.c
src/shmem.c
src/shmem.h

Outsource counter resetting into a dedicated function periodically run by the GC thread to make the average computation independent from external trigger sources. This solves the problem of artificially high QPS values when no queries are processed by FTL.
---
---
3. I am willing to help maintain this change if …

Improve QPS calculation

---

src/vector.c

Triggered by #2078  and #2079. Even though it may not be the final solution returning an error when no memory could be allocated is still a useful thing to do rather than proceeding anyway and (most likely) ending up in a crash.
---
---
3. I am willing to help maintain this change if there are issues with it …

Do not try to access vector items if (re)allocation failed

---

src/CMakeLists.txt

Update source fortification from level 2 to 3:
> This new level detects more buffer overflows and bugs which mitigates security issues in applications at run time.
Furthermore, fix compilation support on recent Ubuntu: I upgraded my development Pi-hole to Ubuntu 24.04.1 LTS yesterday evening. Much to my surprise, I had to find out this morning that compiling FTL is no longer possible with these cryptic error messages being there even when running `./build.sh clean`:
This is caused by several Linux distributions (e.g. [Fedora](https://fedoraproject.org/wiki/Changes/Add_FORTIFY_SOURCE%3D3_to_distribution_build_flags)) and then [`gcc-13`](https://bugs.launchpad.net/ubuntu/+source/gcc-13/+bug/2012440) and [Ubuntu 24.04](https://wiki.ubuntu.com/ToolChain/CompilerFlags#A-D_FORTIFY_SOURCE.3D2) …

Fix compilation support on Ubuntu 24.04.1 LTS

---

src/dnsmasq/forward.c
src/dnsmasq_interface.c
src/dnsmasq_interface.h

Only consider NXDOMAIN replies as indication of external blocking if both the RA and AA bit are unset. This fixes #2085.
When analyzing the DNS packet header we now also check for the absence of the AA bit in addition to the absence of the RA bit.
N/A
--- …

Fix external block detection on NXDOMAIN replies from authoritative upstreams

---

.github/actions/build-and-test/action.yml

See title. See here: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions
Emphasis on:
and
> When you use expressions in an `if` conditional, you can, optionally, omit the `${{ }}` expression syntax because GitHub Actions automatically evaluates the `if` conditional as an expression. However, this exception does not apply everywhere.
from here: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idif
---
**Related issue or feature (if applicable):** Recent fork-based PRs failing the build steps related to deployment.
---
**By submitting this pull request, I confirm the …

Fix Github Actions if statement

---

src/config/config.c
test/pihole.toml

Change default value of `ntp.sync.rtc.set` to `false`. The motivation of this change was a recent discussion with @Bucking-Horn that brought to light that there are systems where the RTC is expected to be set to local time (instead of UTC) for coexistence with other operating systems (such as Windows).
This is not *really* a problem here as we also have `ntp.sync.rtc.utc` to control whether the RTC should be set to, well, UTC (`true`) or local time (`false`), however, there exists no standardized way to obtain if the RTC *is meant* to be set in local time or not. The RTC itself doesn't know this and, hence, cannot be queried. To avoid such conflicts, we decide to not set the RTC by default but only if users specifically want it. If they do, they can also set the UTC/localtime option.
--- …

Don't set RTC time by default

---

src/args.c

Adds description for optional `[domain]`:
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/fix-pihole-ftl-help-output-for-gen-x509-option-with-domain-parameter/73622
--- …

Update --gen-x509 help text

---

src/database/query-table.c
src/datastructure.c
src/dnsmasq_interface.c
src/gc.c
src/shmem.c
src/shmem.h
src/signals.c

Following up on #2084, this PR seeks to improve creation speed of new records (domains, clients, and DNS cache records). Previously, we used linear scanning whenever a new entry is to be added. Usually, there are some "holes" poked in the tables by preceding recycling activity but nothing guarantees us that (a) something has been recycled at all or (b) that such records are "early" in the table. Hence, linear searching through the tables usually scans *the entire table* just to find that there are no gaps and we have to create a new record at the very end of the table.
This PR improves this by adding a new shared memory object which memorizes if there are any recycled entries in these tables. If so, we use them right away without having to search for this. If there are none, we know that …

Improve insertion of clients, domains and DNS cache records

---

src/api/network.c
src/api/stats_database.c
src/database/network-table.c
src/database/network-table.h

Go through network-table.c and ensure error handling is uniform, there were some cases in which an early returning caused by an error could have left prepared SQLite3 statements un-finalized. Whether this is the cause for occasional database locking we are seeing is unclear. However, the change
is specifically tailored to fix the cause of recently reported `ERROR: add_netDB_network_address(-1, "192.168.0.168"): Failed to step (error 19): constraint failed` messages.
---
--- …

Improve network table error handling

---

src/config/config.c
test/pihole.toml

Improve the help text  of the `webserver.tls.cert` config.
Fixes https://discourse.pi-hole.net/t/v6-self-signed-certificate-issues/73640
--- …

Amend the help text of the TLS certificate

---

build.sh
src/CMakeLists.txt
src/args.c
src/enums.h
src/files.c
src/files.h

Fixes #2101, there is much detail in this issue ticket so I won't duplicate it here. Short story is that CMake modifies the binary's run time path information during the first build and strips this away during install. This obviously modifies the checksum and the verification failed rightfully.
This PR disables modifying run time path information altogether as this is not needed for building FTL. Furthermore, it adds two checks during `./build.sh` to ensure this does not happen again in the future without us noticing immediately and hardening the entire `verify` procedure to skip verification when FTL was somehow built without the checksum actually being appended to the binary.
---
**Related issue or feature (if applicable):** Fixes #2101  …

Fix binary verification with modern cmake

---

src/datastructure.c

Fixes https://github.com/pi-hole/FTL/issues/2106
---
**Related issue or feature (if applicable):** https://github.com/pi-hole/FTL/issues/2106
--- …

Upstream lookups should always check for the magic byte while searching

---

src/config/config.c
src/config/validator.c
src/config/validator.h

Fix the #2111 issue, where an empty string is not accepted as value for `dns.domain` option.
Adding a new validation function.
none
---
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase …

Changes the `dns.domain` validation to accept an empty string as value

---

src/tools/netlink.c

Fix a slow but progressing exhaustion of file descriptors when heavily using https://pi.hole/admin/interfaces by ensuring that each `socket` is closed after we're done with it.
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/error-500-internal-server-error-error-cannot-open-script-file-var-www-html-admin-login-lp/73698/
---
3. …

Ensure we close netlink sockets

---

src/database/shell.c
src/database/sqlite3.h

SQLite3.47.1 has been released earlier today.
Parts of the CHANGELOG that apply to us:
- Fix incorrect answers to certain obscure IN queries caused by new query optimizations added in the 3.47.0 release.
- Other minor bug fixes. 
---
---
3. I am willing to help maintain this change if there are issues with it …

Update embedded SQLite3 to 3.47.1

---

src/FTL.h
src/gc.c
src/gc.h
src/ntp/client.c
src/overTime.c

Dynamically lower the GC interval from ten minutes to one minute when the user explicitly requests `webserver.api.maxHistory = 0.0`. This should help with #2126 and https://discourse.pi-hole.net/t/pihole-crash-reason-shared-memory-tmpfs-dev-shm-100/74204
---
**Related issue or feature (if applicable):** see above
---
3. I am willing to help maintain this change …

Dynamically lower the GC interval

---

src/api/api.c
src/database/database-thread.c

Remove duplicated code (alias-client importing has already been done a few lines above) and silence a harmless warning.
---
---
5. I have …

Remove duplicated code and silence a harmless warning

---

src/database/shell.c
src/database/sqlite3.h

CHANGELOG
1. Fix a problem in text-to-floating-point conversion for SQLite that can cause values between '1.8446744073709550592eNNN' and '1.8446744073709551609eNNN' for any exponent NNN to be rendered incorrectly. In other words, some numeric text values where the first 16 significant digits are '1844674407370955' might be converted into the wrong floating-point value. See [forum thread 569a7209179a7f5e](https://sqlite.org/forum/forumpost/569a7209179a7f5e). This problem only arises on x64 and i386 hardware. The problem was introduced in 3.47.0.
2. Other minor bug fixes.
---
--- …

Update embedded SQLite3 to 3.47.2

---

.github/Dockerfile
src/capabilities.c
test/arch_test.sh

A few changes without functional changes needed to get compatible with Alpine 3.21 (GCC 14.2 and Linux 6.12).
Opening as draft right now as we can update the building container only when it has been tagged.
---
**Related issue or feature (if applicable):** https://github.com/pi-hole/docker-base-images/pull/100
---
3. I am willing to help maintain this change if …

GCC 14.2.0 support

---

src/FTL.h
src/api/docs/content/specs/queries.yaml
src/api/queries.c
src/database/common.c
src/database/query-table.c
src/database/query-table.h
src/dnsmasq/dnsmasq.h
src/dnsmasq/dnssec.c
test/api/libs/responseVerifyer.py
test/test_suite.bats

Expose extended DNS error codes (and human-readable textual interpretation if available) via the`queries` API. This is especially useful in the vicinity of DNSSEC issues like `BOGUS` as it can provide further reasoning such as `DNSSEC signature expired`:
---
---
3. I am willing to help maintain this change if …

Expose EDE information via API if available

---

src/dnsmasq/forward.c

Fixes #2140 by moving callback for multiple replies into the loop. This was recently broken in #2136 where some code refactoring by Simon Kelley unintentionally kicked a bit of FTL code out of the loop into a region where it shouldn't have been. Testing didn't reveal this as rather specific conditions need to be met to trigger a crash.
---
**Related issue or feature (if applicable):** #2140
--- …

Fix crash on multiple replies

---

src/api/list.c

Fixes a bug reported on Discourse:
---
--- …

Allow spaces also in PUT /api/groups

---

src/webserver/x509.c

Fix leap year check when creating x509 certificate. tm_mon is zero-based, see [man page](https://www.man7.org/linux//man-pages/man3/tm.3type.html).
Replace tm->tm_mon _== 2_ with tm->tm_mon _== 1_.
N/A
--- …

Fix leap year check

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/webserver/webserver.c
src/webserver/webserver.h
test/pihole.toml

See title. On second thought, this seems like a meaningful addition. We reduce the default to always leave at least one core unoccupied in case issues like described in #2129 appear (which is still unresolved due to us still waiting for feedback). Still, this PR seems meaningful to avoid this from preventing others to other users as well.
---
---
2. I have commented …

Make maximum number of threads used by web server configurable

---

test/test_suite.bats

This PR removes the NTP test from FTL's CI testing suite. The reason for this is that this test is failing > 75% of the time, triggering automatic retries unnecessarily lengthening the overall build process and wasting resources.
But it is actually not only wasting resources but also causes more than 80% of the `docker-base-images/ftl-build` to fail at least one of the jobs, preventing updating the build container altogether.
There simply seems to be no reliable way to get this working. The underlying issue is somewhat hard to analyze, however, it seems that the NTP server simply is firewalled away on most (but not all) GHA runners.
---
--- …

CI: Remove NTP test

---

.github/Dockerfile
src/args.c
src/config/dnsmasq_config.c

Retry to wait for result of dnsmasq syntax test if interrupted by a signal
---
**Related issue or feature (if applicable):** #2149 
--- …

Harden dnsmasq syntax checking against signals

---

.devcontainer/devcontainer.json

This should still work on any linux distro too!
Annoyingly MacOS uses `/Users/` rather than `/home/` - but all distros should have `$HOME`
https://apple.stackexchange.com/a/86415
--- …

Allow .ssh directory to be mounted on MacOS host

---

src/config/cli.c

When calling _pihole-FTL --config_ one gets dozens of errors
```
Trying to compare a NULL (R) string in get_config_from_CLI()
```
If no specific key is given when reading the configuration, the key parameter to get_config_from_CLI() is passed as NULL, thus causing strcmp() to croak. This PR avoids these errors.
Run the first pass to detect an exact key match only if the key parameter is not NULL.
N/A
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base …

Prevent calling strcmp with NULL pointer

---

CMakeLists.txt
src/dnsmasq/dnsmasq.c
src/dnsmasq/dnsmasq.h
src/dnsmasq/edns0.c
src/dnsmasq/forward.c
src/dnsmasq/rfc1035.c
src/dnsmasq/rrfilter.c
src/dnsmasq/util.c
test/dnsmasq_warnings

Changelog:
>  Handle queries with EDNS client subnet fields better. If dnsmasq is configured to add an EDNS client subnet to a query, it is careful to suppress use of the cache, since a cached answer may not be valid for a query with a different client subnet. Extend this behaviour to queries which arrive a dnsmasq already carrying an EDNS client subnet.
---
---
2. I …

Update dnsmasq to v2.91test6

---

src/api/auth.c
src/api/teleporter.c
src/args.c
src/config/config.c
src/config/config.h
src/database/common.c
src/database/gravity-db.c
src/database/query-table.c
src/database/query-table.h
src/dnsmasq_interface.c
src/files.c
src/zip/teleporter.c

`pihole-FTL migrate v6` is intentionally not included in the help output as it is solely meant to be used internally by the installer script once from v5 -> v6
Related to https://github.com/pi-hole/pi-hole/pull/5830
---
4. It is …

Add new explicit migration command

---

src/FTL.h
src/resolve.c

This PR is an attempt to fix #2124 
The described issue is that some IPv6 clients don't show a host name in the Query Log even when the network table has one.
The reason for this is timing. When a client issues a query over IPv6 quickly after it got this address, the first query arrived
the Pi-hole *before* the client is known to the network table. When FTL now tries to resolve this address's name, it cannot find a name. A few moments later, when the ARP cache is parsed for the next time, FTL may be able to correlate this new address through an identical MAC address to an existing address having a host name. However, as the default value of `resolver.refreshNames` is `IPV4_ONLY`, FTL actually never tries to resolve the address so it never gets to know the IPv6 client's host name.
The …

Delay IPv6 client name lookups

---

.github/workflows/build.yml

Fix workflow for self-hosted runners. The issue with using `runs-on: self-hosted` is that GHA may decide to run the jobs on *any* available self-hosted runner. This wasn't an issue before as we had only ARM64 runners, however, when experimenting with a native RISCV64 runner, GHA tried to build the ARM packages on this one. We need to be architecture-specific here.
This PR comes with no functional change.
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch …

Use different tag for self-hosted runners

---

src/config/config.c
src/webserver/webserver.c
test/pihole.toml
test/test_suite.bats

See title. Related to ongoing Discourse discussion.
Exemplary additional `FTL.log` output:
```
2024-12-20 09:57:19.691 CET [1902269M] INFO: Web server ports:
2024-12-20 09:57:19.691 CET [1902269M] INFO:   - 80 (HTTP, IPv4, redirecting)
2024-12-20 09:57:19.691 CET [1902269M] INFO:   - 80 (HTTP, IPv6, redirecting)
2024-12-20 09:57:19.691 CET [1902269M] INFO:   - 443 (HTTPS, IPv4)
2024-12-20 09:57:19.691 CET [1902269M] INFO:   - 443 (HTTPS, IPv6)
```
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/why-ca-i-not-access-dev-releases-on-new-setup/74613/7
--- …

Make webserver ports optional by default

---

src/database/message-table.c
src/gc.c
src/gc.h

Fix a value overflow in the rate-limiting diagnosis message reported on Discourse.
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/client-has-been-rate-limited-for-at-least-3217188-seconds/75091
--- …

Fix possible turnaround overflow

---

CMakeLists.txt
src/dnsmasq/cache.c
src/dnsmasq/config.h
src/dnsmasq/dnsmasq.c
src/dnsmasq/forward.c
test/dnsmasq_warnings

Update to the most recent `dnsmasq` tag `v2.91test7` published earlier today. It fixes a few issues with the new UDP->TCP automatism.
---
--- …

Update dnsmasq to latest v2.91test7

---

src/dnsmasq/dnsmasq.c
src/dnsmasq_interface.c

Do not try to use `find_mac()` if `netlink` socket is closed.
Fix #2154 
---
--- …

Avoid endless spinning in UDP->TCP path

---

patch/sqlite3/0001-print-FTL-version-in-interactive-shell.patch
patch/sqlite3/0002-make-sqlite3ErrName-public.patch
src/database/shell.c
src/database/sqlite3.h

SQLite Release 3.48.0 On 2025-01-14
Mostly, this release modies the build process of SQLite3: Refactor the "configure" script used to help build SQLite from canonical sources, to fix bugs, improve performance, and make the code more maintainable. We are not affected as we use the source code amalgamation.
The only point interesting for us is the last one: Various obscure bug fixes. 
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and …

Update SQLite3 to 3.48.0 released earlier today

---

src/resolve.c

Fixing a glitch reported on Discourse. See link below.
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/shm-errors-in-ftl-log-for-v6-development/75131/3?u=dl6er
--- …

Remove surplus SHM unlocking in IPv6 name resolution deceleration code

---

.github/workflows/build.yml

The GHA provided machines have 4 cores assigned each and are, accordingly almost 2x as fast as our own runners (featuring two cores, each).
Related Github blog post: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview
Comparison:
---
---
2. I have commented my proposed changes within the …

Use arm64 machines provided by GHA

---

CMakeLists.txt
src/dnsmasq/auth.c
src/dnsmasq/config.h
src/dnsmasq/forward.c
src/dnsmasq/rfc1035.c

Add most recent `dnsmasq` commits. They are mostly concerned with mixing a local unsigned authoritative zone (e.g., `home.example.com`) with a DNSSEC signed upstream zone (`e.g. `example.com`). The first commit improves handling of duplicate DNS answers via UDP avoiding sending duplicate information to the client downstream in edge-cases. As the client would have anyway ignored it, this is just a tweak, not a fix for anything.
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I …

Update embedded dnsmasq to v2.91test8

---

CMakeLists.txt
src/database/query-table.c
src/datastructure.c
src/dnsmasq/auth.c
src/dnsmasq/cache.c
src/dnsmasq/dnsmasq.h
src/dnsmasq/dnssec.c
src/dnsmasq/forward.c
src/dnsmasq/option.c
src/dnsmasq/rfc1035.c
src/dnsmasq_interface.c
src/enums.h
test/run.sh
test/test_suite.bats
test/zone_update.py

Change compared to last tagged version:
This provides extra protection against reply-spoof attacks.
Since DNS queries are case-insensitive, it's possible to randomly flip the case of letters in a query and still get the correct answer back. This adds an extra dimension for a cache-poisoning attacker to guess when sending replies in-the-blind since it's expected that the legitimate answer will have the same pattern of upper and lower case as the query, so any replies which don't can be ignored as malicious.
The amount of extra entropy clearly depends on the number
of a-z and A-Z characters in the query, and this implementation puts a hard limit of 32 bits to make rescource allocation easy. This about doubles entropy over the standard random ID and random port combination.
**Related issue …

Update dnsmasq to v2.91test9 

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/enums.h
src/log.c
src/tools/netlink.c
src/tools/netlink.h
test/pihole.toml

Following an issue report on Discourse, mentioning that not all interfaces were shown, I dived deeply into both the Netlink documentation as well as the kernel source code realizing that they are not always congruent. I modified our Netlink code in a way that would be consistent with how the kernel does it but still work if the way the kernel does it would be modified to behave as documented (I know this sounds a bit weird). In addition, we now have a lot of additional code that handles warning the user in case anything unexpected (most worth noticing would be Netlink packet truncation).
This PR adds the new config option `debug.netlink` obviously defaulting to `false`.
Extensively tested on three x86_64, a Raspberry Pi 1 B+, 4 and a 5 running the `aarch64` kernel. On the latter, the …

Netlink tweaks

---

src/dnsmasq/forward.c
src/dnsmasq_interface.c
src/dnsmasq_interface.h

Reducing the number of TCP connection warning by not logging an error on the first retry issued to a server. Only log warnings if the issue persists.
---
--- …

Improve FTL connection error logging

---

src/api/teleporter.c

Add restoring of static DHCP leases from pre-v6 `tar.gz` Teleporter archives
---
--- …

Restore static DHCP leases from v5 tar.gz Teleporter archives

---

src/dnsmasq_interface.c
test/test_suite.bats

Queries blocked upstream with a known blocking page IP should not be short-circuited locally as this will cause FTL to reply with the locally defined blocking mode instead of the IP address of the upstream DNS server's blocking page
The tests have been adjusted to test for the new behavior. The now succeeding tests verify it is working as expected. Local testing is possible by specifying the Cisco Umbrella `208.67.222.123, 208.67.220.123` servers as upstream servers and then testing a blocked domain (which is not on your gravity!), e.g., http://www.internetbadguys.com/.
**Related issue or feature (if applicable):** This is a regression of https://github.com/pi-hole/FTL/pull/2030 and fixes https://github.com/pi-hole/FTL/issues/2175
**Pull request in [docs](https://github.com/pi-hole/docs) …

 Fix blocked upstream (IP) handling

---

CMakeLists.txt
src/args.c
src/dnsmasq/forward.c

This PR contains only one commit to resolve a bug reported through our Discourse forum:
A retry to upstream DNS servers triggered by the following conditions
1) A query asking for the same data as a previous query which has not yet been answered.
2) The second query arrives more than two seconds after the first.
3) Either the source of the second query or the id field differs from the first.
fails to set the case of the retry to the same pattern as the first attempt.
However `dnsmasq` expects the reply from upstream to have the case pattern of the first attempt.
If the answer to the retry arrives before the answer to the first query, dnsmasq will notice the case mismatch, log an error, and ignore the answer.
The worst case scenario would be the first upstream query or reply is lost and …

Update dnsmasq to 2.91rc3

---

CMakeLists.txt
src/dnsmasq/bpf.c
src/dnsmasq/forward.c

Yet another 0x20 fix.
To complement the previous one, which fixed the retry path
when the query is retried from a different id/source address, this
fixes retries from the same id/source address.
---
--- …

Update dnsmasq to 2.91rc4

---

src/config/toml_writer.c
src/daemon.c
src/daemon.h
src/dnsmasq_interface.c
src/main.c
src/procps.c
src/shmem.c
src/shmem.h

So far, FTL tried to prevent multiple processes from being started on the same machine. However, as the `pihole-FTL` binary became kind of a Swiss-army-knife offering integrated features such as `sqlite3`, `sqlite3_rsync`, `sha256sum`, `gzip`, `lua`, `dhcp-discover`, and others (like a small TLS certificate managing tool set), it becomes more and more likely that there are long-lived interactive `pihole-FTL` instances on the machine. They may coexist without any issues, however, once such an interactive process is running, restarting the original `pihole-FTL` may be prevented under certain circumstances.
An earlier attempt was made in https://github.com/pi-hole/FTL/pull/2183 to allow full concurrent FTL processes but it had its own pitfalls and this PR proposes a different, much simpler …

Fix duplicate process detection

---

src/tools/dhcp-discover.c
src/tools/dhcp-discover.h
src/tools/dhcpv6-discover.c

See title. In addition, we fix a locking issues which could have caused error messages to appear in the middle of other content.
---
---
5. I …

Add proper timeout handling to dhcp-dicsover feature

---

src/database/sqlite3.h

This is a rather small hotfix. The SQLite3 forum says:
> This patch fixes a bug discovered two days ago in the `concat_ws()` SQL function.  Malicious inputs to that function might lead to a memory error.  For that reason, you are encouraged to upgrade.  The problem has existed since the `concat_ws()` SQL function was first added to SQLite with version 3.44.0 on 2023-11-01.
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull …

Update embedded SQLite3 to 3.49.1

---

.github/workflows/build.yml

We use https://github.com/softprops/action-gh-release to attach files to the release. They always needed `content: write` [permission](https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions). So far this was not an issue, but the scope of the default GH token seems to have changed (https://github.com/softprops/action-gh-release/issues/572#issuecomment-2586651697).
This PR grants the necessary permissions.
See a failing action trigged by a release tag here: https://github.com/pi-hole/FTL/actions/runs/13396405826
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I …

Allow default GH token to write content in the build script

---

src/config/env.c

Ensure we do not split too often at '=' while processing environment variables. This is an issue with multiple `=` being present in environment variables.
---
--- …

 Fix parsing of envvars with more than one =

---

src/config/legacy_reader.c

See title and related Discourse discussion (with `backtrace` information)
---
--- …

Fix legacy parsing of DEBUG_ALL option

---

.github/dependabot.yml

We use `npm` to install packages to validate the API. This should be monitored by dependabot.
Replaces https://github.com/pi-hole/FTL/pull/2190
--- …

Add dependabot for npm

---

src/webserver/lua_web.c

See title and #2202 for details.
---
**Related issue or feature (if applicable):** Fixes #2202 
--- …

Do not redirect to login page for ACME challenges

---

src/config/config.c
test/pihole.toml
test/test_suite.bats

Change default value of `webserver.port` to comply with auto-generated config string. We do this to avoid the generated string to be flagged as `CHANGED` in `pihole.toml`. No functional change in this PR!
---
---
4. It is compatible …

Rearrange webserver.port default value

---

CMakeLists.txt
src/dnsmasq/forward.c

`dnsmasq 2.91rc5` has just been tagged. It fixes a few issues around 0x20 encoding so it is rather likely that they can be the cause for the crashes we are seeing.
--- …

Update embedded dnsmasq to 2.91rc5

---

src/config/dnsmasq_config.c

Some time ago (in https://github.com/pi-hole/FTL/pull/2116), we fixed the config validator to accept `revServer` lines without `<domain>`, however, there was another check at the point where this configuration is written into `dnsmasq.conf` as users may have edited `pihole.toml` directly without going through the API (so, effectively, bypassing the validators). This last check still enforced `<domain>` which is relaxed herein.
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2216
--- …

Make <domain> in revServer *really* optional

---

src/config/setupVars.c

Return early if no setupVars.conf is found, currently this is producing unnecessarily verbose output during installation, cfm. https://github.com/pi-hole/FTL/issues/2217
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2217
---
4. It is …

Do not try to migrate setupVars.conf if it does not exist.

---

src/webserver/webserver.c
test/test_suite.bats

In the corner-case of a user explicitly having configured Pi-hole to NOT listen on lo (because there may be another webserver, etc.), the `pihole` CLI command may be unable to communicate with the API due to the hard-coded path "localhost". Change this to use the special "pi.hole" host name where interface-dependent replying is already implemented
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2192
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my …

Fix CLI command for non-local API configuration

---

src/api/2fa.c
src/api/auth.c
src/config/password.c
src/config/password.h

Improve secure randomness generator by ensuring it retries automatically if interrupted by a signal plus printing a warning if the process will be blocking due to not enough entropy being available (this may delay FTL's startup for currently not externally visible reasons)
---
**Related issue or feature (if applicable):** Context here https://discourse.pi-hole.net/t/unable-to-login-after-v6-update-getrandom-error/76269
--- …

Improve secure randomness generation

---

src/config/config.c
test/pihole.toml

Follow-up on https://github.com/pi-hole/FTL/pull/2209 - all details there.

Fix typo in dns.showDNSSEC text description

---

patch/civetweb.sh
patch/civetweb/0001-Expose-bound-to-addresses-from-CivetWeb-to-the-front.patch
src/webserver/civetweb/civetweb.c
src/webserver/civetweb/civetweb.h
src/webserver/webserver.c
test/test_suite.bats

Rather recently, https://github.com/pi-hole/FTL/pull/2233 changed the response to `dig +short CHAOS TXT local.api.ftl` from `localhost` as hard-coded host name to `pi.hole`. However, on systems which do not use FTL as their DNS resolver, the later does actually not resolve. The initial trigger for said change was https://github.com/pi-hole/FTL/issues/2192 where a user described that they cannot use the API because they configured their web server to NOT listen on `127.0.0.1` at all.
The PR revisits the initial issue altogether and, instead of using any fixed host name, gets the actual IPs the webserver was bound to and reports this, e.g.
```
$ sudo pihole-FTL --config webserver.port
80,[::]:80,443s,[::]:443s,127.0.0.67:445s
$ dig CHAOS TXT local.api.ftl +short
"http://127.0.0.1:80/api/" …
```

Tweak CHAOS TXT local.api.ftl

---

src/ntp/server.c

Do not allow more than 10 NTP requests per second to be served.
---
--- …

Rate-limit internal NTP server

---

src/config/dnsmasq_config.c

Wipe out possibly existing entries in dns.hosts, dns.cnameRecords, and dhcp.hosts when importing from a v5 Teleporter file having the corresponding files
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2257
--- …

Prevent duplicated entries on successive v5 Teleporter importing

---

src/api/auth.c
src/api/config.c
src/api/info.c
src/webserver/http-common.c
src/webserver/json_macros.h

See title and the referenced issue ticket for further context.
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2266
--- …

We should not send any content for HTTP codes 1xx, 204 and 304

---

src/config/setupVars.c

Assume `DHCP_LEASETIME` is in hours when imported from `setupVars.conf` (e.g., via Teleporter or during v5 -> v6 migration)
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2268
--- …

Fix DHCP_LEASETIME migration

---

src/FTL.h
src/api/history.c
src/database/aliasclients.c
src/datastructure.c
src/gc.c
src/gc.h
src/overTime.c

Data returned by the API for over-time statistics should not return more than specified in `webserver.api.maxHistory`
----
**Related issue or feature (if applicable):** https://github.com/pi-hole/web/issues/3255
--- …

Fix webserver.api.maxHistory usage in API

---

src/config/config.c
test/pihole.toml

Fix typo in descriptions of dns.specialDomains.mozillaCanary and dns.specialDomains.iCloudPrivateRelay
Reported at [https://discourse.pi-hole.net/t/typos-in-menu-settings/76935](https://discourse.pi-hole.net/t/typos-in-menu-settings/76935)
Deleting the word replies and substituting reply.
Tests updated to reflect this change.
---
3. I am willing to …

Fix typo in dns option descriptions

---

src/config/config.c
src/config/validator.c
src/config/validator.h

Add specific validator for `webserver.paths.webhome` ensuring there are slashes both at the beginning and the end of the string
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2274
--- …

Add webhome validator

---

src/config/env.c
test/run.sh
test/test_suite.bats

Currently, FTL validates config values only if being asked to change them *interactively* either via the API or the CLI where
the validator's feedback reaches the user *immediately*. This PR extends validation of config values also to checking ENVVARS.
In case of invalid ENVVARS, whatever is configured in `pihole.toml` will be used for the value (so it will simply not be overwritten).
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits …

Also validate env variables

---

patch/civetweb/0001-Expose-bound-to-addresses-from-CivetWeb-to-the-front.patch
src/webserver/civetweb/civetweb.c
src/webserver/civetweb/civetweb.h
src/webserver/webserver.c

Sync embedded CivetWeb to their latest `master` state and implement displaying of the boundness state of ports in the startup log of FTL. The related CivetWeb change has recently been created by us: https://github.com/civetweb/civetweb/pull/1323
---
---
3. I am willing to help maintain this change if there are …

Update embedded CivetWeb

---

src/webserver/civetweb/civetweb.c
src/webserver/webserver.c

Do not try to start API if no ports succeeded binding. This circumvents a bug resulting in a crash in CivetWeb. See upstream issue report at https://github.com/civetweb/civetweb/issues/1327
Should be merged after #2312 as it is based on it to know when we bound to ports (and when not).
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2250
--- …

Avoid CivetWeb crash if no optional port could be bound

---

src/config/config.c
src/config/dnsmasq_config.c
src/config/dnsmasq_config.h

Fixes two issues reported on Discourse:
- Always provide `errbuf`, even it was are not going to use it outside of `write_dnsmasq_conf()`. Add `nonnull` attribute that ensures this cannot be forgotten again in the future.
- Make identical DHCP start and end addresses a valid configuration as users may be using `dhcp-host` lines to assign only static addresses which can be outside this range
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/upgrade-to-v6-breaks-installer-and-dns-resolution-on-config-error/77089
--- …

Empty DHCP range is valid

---

src/resolve.c

Exclude new IPv6 clients from skipping due to the setting of `resolver.refreshNames` as we are not refreshing but resolving for the first time here.
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2292
--- …

Fix first-time IPv6 client name resolution

---

src/config/config.c
src/config/dnsmasq_config.c
test/pihole.toml

- Load only files with suffix `*.conf files` from `/etc/dnsmasq.d` when `misc.etc_dnsmasq_d == true` (not arbitrary files)
- Add warning about the possible causes of conflicting config files in `/etc/dnsmasq.d/` to the help text of `misc.etc_dnsmasq_d`
---
**Related issue or feature (if applicable):** Relates to https://github.com/pi-hole/FTL/issues/2270
---
3. …

Tweak misc.etc_dnsmasq_d help text and scope - only read *.conf files

---

patch/civetweb.sh
patch/civetweb/0001-Increase-niceness-of-all-civetweb-threads-as-DNS-ope.patch
src/webserver/civetweb/civetweb.c

Increase niceness of all CivetWeb threads as DNS operation is more important than the API and dashboard. This is a follow-up on #2305 to ensure the webserver workers cannot take over the system on heavy load.
---
---
4. It is …

Increase niceness of CivetWeb threads

---

src/api/docs/content/specs/info.yaml
src/api/info.c
src/api/padd.c
src/daemon.c
src/daemon.h
src/procps.c
src/procps.h

Calculate and expose total CPU % for the web interface, see related PR.
---
**Related issue or feature (if applicable):** Related to https://github.com/pi-hole/web/issues/3261
---
5. I have …

Add total CPU % to /info/system endpoint

---

src/signals.c

Signal to the main process to shut down if a crash happens in a thread instead of trying to shut down cleanly from within this thread. Ensures that the non-success exit code is returned at the end, allowing `systemd` to try automatically restarting FTL.
---
**Related issue or feature (if applicable):** Reported as part of #2307 
--- …

Ensure proper shutdown when crashing in a thread

---

src/config/env.c

Add newline as additionally allowed separator (next to ";") for string arrays defined through env vars
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2339
--- …

Allow newlines in env vars as separator

---

src/api/history.c

Do not try to unlock when there is no lock. Only affects `/api/history/clients` when the user has `misc.privacylevel >= 2`.
I checked similar code regions depending where similar `misc.privacylevel` code exists but this seems to have been the only place where this was done wrong.
---
**Related issue or feature (if applicable):** Fixes #2350 
---
3. I am willing …

Fix unlocking warning in /api/history/clients

---

src/api/teleporter.c

`POST /api/teleporter` should be rejected when app password is used but `webserver.api.app_sudo == false`.
---
**Related issue or feature (if applicable):** Fixes #2347 
---
5. I have squashed …

Increase restrictions on POST /api/teleporter

---

src/webserver/webserver.c

Use HTTP/1.1 keep-alive to allows clients to reuse TCP connection for subsequent HTTP requests, which **can improve performance dramatically** as no further TLS handshakes and connection opening/closing are required. This reduces pressure especially on low-end hardware lacking hardware-crypto for TLS.
This is disabled by default in CivetWeb as it puts additional compliance constraints on the request handlers. However, Pi-hole's API already fully complies with these additional constraints so no other changes than enabling this are needed.
We set a default timeout of 5 seconds after which the server closes the ready-to-be-used-again connections to free them for other requests. We intentionally keep such a long timeout so that requests being fired on the background (e.g. the regular update …

Use keep-alive

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/webserver/lua_web.c
src/webserver/webserver.c
test/pihole.toml
test/test_suite.bats

Add new `webserver.serve_all` option defaulting to `false`, controlling if we should serve any content outside `/admin` and `/api`.
---
**Related issue or feature (if applicable):** Fixes #2349 
--- …

Change default file serving behavior **possibly breaking**

---

src/api/docs/content/specs/queries.yaml
src/api/queries.c
src/datastructure.c
src/datastructure.h

Add new special `?upstream=permitted` filter for Query Log much like the already existing "blocklist" and "cache" options.
---
---
5. I have …

Add new special permitted upstream filter for Query Log

---

src/webserver/json_macros.h

Check for correct HTTP code range. Codes of 1XX, 204, and 304 should send an empty body. The check was for less than 100 (e.g. 99, 98, ...) instead of less than 200 (e.g. 199, 198, ...)
4. File a …

Fix typo in json_macros.h for HTTP Status Code body return check

---

.gitignore
CMakeLists.txt
src/dnsmasq/dnsmasq.h
src/dnsmasq/forward.c
src/dnsmasq/option.c

Default-off 0x20 encoding and provide `do-0x20-encode` config option to enable. For now, this causes too many problems to default on.
We keep the `no-0x20-encode` config option as to not break user systems complaining about an unknown/invalid config option. You now have to have `do-0x20-encode` and **not** `no-0x20-encode` for the feature to be active. In case you have `no-0x20-encode`, it always wins and the feature stays off even when `do-0x20-encode` is set. This seems to be the best compromise to ensure backwards compatibility...
---
**Related issue or feature (if applicable):** Many reported issues, most
---
1. I have read …

Default-off 0x20 encoding

---

src/database/database-thread.c
src/database/query-table.c
src/database/query-table.h
src/main.c

Do not store queries when `database.maxDBdays is == 0`, however, we still want to store the remaining meta-tables for the network table to work
--- …

Still save clients when database.maxDBdays is 0

---

src/config/toml_reader.c
src/webserver/webserver.c

This fixes FTL restarting for every (!) config change when webserver.threads = 0 and *any* other config setting is changed, e.g., any of the debug flags out of which none should be triggering a full restart of FTL.
This bug is part of v6.0.4. It is a regression of https://github.com/pi-hole/FTL/commit/2aeccfbe126c29f94bb1dc7e3ea261bd38a20b3f. I'm not aware of any reports out in the wild. I furthermore added logging for the particular reason a restart was necessary.
---
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), …

Do not update webserver.threads in-place

---

CMakeLists.txt
src/dnsmasq/forward.c
src/dnsmasq/rfc1035.c

Update embedded dnsmasq to v2.91rc6

---

src/CMakeLists.txt
src/api/auth.h

Also set `Expires=` property when the server tries to delete the SID cookie. RFC 6265, section 5.3 says:
> The user agent **MUST** evict all expired cookies from the cookie store if, at any time, an expired cookie exists in the cookie store.
---
**Related issue or feature (if applicable):** Fixes #2322
---
3. I am willing to help maintain this change if there …

Also set Expires= property for deleted cookies

---

src/api/docs/content/specs/lists.yaml

Fix documentation for the lists `batchDelete` endpoint. It was incorrectly referring to the `POST /lists` semantics.
---
**Related issue or feature (if applicable):** Fixes #2377 
---
5. I have …

Fix docs for lists batchDelete

---

CMakeLists.txt

This is just a tag change. All "real" changes are already in `development`.
> [!IMPORTANT]
> Merge only after `dnsmasq` v2.91 has actually been released (expected today).
---
--- …

Update dnsmasq tag to 2.91

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/lua/ftl_lua.c
src/webserver/lua_web.c
src/webserver/lua_web.h
src/webserver/webserver.c
src/webserver/webserver.h
test/pihole.toml

Add new config option `webserver.paths.prefix` allowing Pi-hole's dashboard and API to be used behind a reverse proxy with path prefix multiplexing. This was already possible in Pi-hole v5.0 without having been added intentionally at any point. It is debatable whether this is a new feature or a bug (because it used to work like this pre-v6.0).
A self-contained `docker-compose.yml` suitable for testing this can be found in #2298 
> [!NOTE]
> You will need the related web branch `new/web_prefix` for this to work as expected.
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2298
---
1. I …

Allow prefix multiplexing behind reverse proxy

---

src/api/docs/content/specs/auth.yaml

CSRF token is not always presence.

fix: incorrect session field requirements

---

src/webserver/webserver.c

Stops this from happening:
```
pihole  | 2025-04-02 17:27:37.400 BST [52M] INFO: Web server ports:
pihole  | 2025-04-02 17:27:37.400 BST [52M] INFO:   - 0.0.0.0:80 (HTTP, IPv4, optional, OK)
pihole  | 2025-04-02 17:27:37.400 BST [52M] INFO:   - 0.0.0.0:443 (HTTPS, IPv4, optional, OK)
pihole  | 2025-04-02 17:27:37.400 BST [52M] INFO:   - [::]:80 (HTTP, IPv6, optional, OK)
pihole  | 2025-04-02 17:27:37.400 BST [52M] INFO:   - [::]:443 (HTTPS, IPv6, optional, OK)
pihole  | 2025-04-02 17:27:37.400 BST [52M] INFO: Web server ports:
pihole  | 2025-04-02 17:27:37.400 BST [52M] INFO:   - 0.0.0.0:80 (HTTP, IPv4, optional, OK)
pihole  | 2025-04-02 17:27:37.400 BST [52M] INFO:   - 0.0.0.0:443 (HTTPS, IPv4, optional, OK)
pihole  | 2025-04-02 17:27:37.400 BST [52M] INFO:   - [::]:80 (HTTP, IPv6, …
```

Fix duplicate web port information output in FTL startup

---

src/dnsmasq_interface.c

Allow the logging of 5 digit port numbers in logfile warning swithout truncation. Bug #2408, as reported on discourse.pi-hole.net
Increases the size of the string that will store the combined server ip & port number.
N/A
--- …

Fix logfile warning port length truncation (bug #2408)

---

src/api/api.h
src/webserver/lua_web.c
src/webserver/webserver.c
src/webserver/webserver.h

User proper redirection functions instead of messing about with HTTP headers ourselves. Yes, simply adding `Content-Length: 0` would have been a equally working fix, but doing it like this is more future-proof.
**Related issue or feature (if applicable):** Fixes #2412 
---
4. It is …

Fix redirecting when redirecting from /admin/ to /admin/login and back

---

src/ntp/ntp.h
src/ntp/server.c

Fix un-/signed error in the total round-trip delay to the reference clock stemming from an unclear definition in RFC 5905
---
**Related issue or feature (if applicable):** Fixes #2418 
---
5. I …

Fix signedness error in the NTP total round-trip delay calculation

---

src/tools/netlink.c

Report addresses within the RFC6598 shared address space as Carrier-Grade NAT
Issue raised in #2422 of these addresses being misidentified as "public"
Adds detection for addresses falling within 100.64.0.0/8 to the address type logic, instead of them falling through to the "public" catch-all.
n/a
---
2. I have commented my proposed changes within the code and I have …

Report RFC6598 shared address space as "Carrier-Grade NAT"

---

src/ntp/client.c
src/procps.c
src/procps.h

> What does this PR aim to accomplish?:
> 
> Prevent Pi-hole's ntp sync from disrupting clock disciplining ntp clients already installed and active.
> 
> Fixes Pi-hole #6139 - https://discourse.pi-hole.net/t/built-in-ntp-server/78404
>
> How does this PR accomplish the above?:
>
> Tests for presence of a daemon process related to chrony, the ntp family (ntp, ntpsec and openntpd), or ntpd-rs.
> If any of these are identified, do not synchronise the time.
This PR is an alternative implementation of #2414 
---
--- …

Check for existing NTP client when starting FTL

---

src/api/docs/CMakeLists.txt
src/api/docs/docs.h

Modify how we use `xxd` to compile assets into the FTL binary. This addresses the CodeQL concern that only valid header files should be included using `#include` pre-processor directives. In the end, it doesn't really matter but - as the same complaint is coming up on each addition/change of related files - we can modify the `xxd` compilation step to generate "proper" header files
---
**Related issue or feature (if applicable):** https://github.com/pi-hole/FTL/pull/2445#discussion_r2075906032
---
1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire …

Modify how we use xxd to compile assets into the FTL binary

---

src/config/config.c
test/pihole.toml

Set `dns.interface` to `eth0?` by default. We already use `eth0` if no interface is set, but this PR makes this more obvious to the users.
https://github.com/pi-hole/FTL/blob/e0f96fee53413ce32cc0c95878d14de85cddda38/src/config/dnsmasq_config.c#L445-L448
Accompanies: https://github.com/pi-hole/pi-hole/pull/6216 and https://github.com/pi-hole/web/pull/3436
--- …

Set dns.interface to eth0 by default

---

src/database/message-table.c

Fix the display of invalid hostname information in Pi-hole diagnosis.
The issue is noted in # 2452 , and has been mentioned on discourse.
Example:
Upon encountering an invalid host name (eg `in$valid.host.name`)
The correct offset is written to FTL.log 
```
2025-06-03 08:52:01.364 AEST [209227/T209230] WARNING: Host name of client "192.168.1.130" => "in$valid.host.name" contains (at least) one invalid character (hex 24) at position 2
```
And records it correctly to Pihole-FTL.db
However when the same incident is viewed in Pi-hole diagnosis, it lists an incorrect offset, and the character present at that offset rather than identifying the actual problem.:
```
2025-06-02 22:52:01 HOSTNAME Host name of client 192.168.1.130 => "in$valid.host.name" …
```

Display invalid character and offset correctly in hostname diagnosis

---

src/ntp/server.c

Send an ntp response to any client, no matter the version the client is identifying as.
Some clients (such as win32tm shipping with Microsoft Windows 11, and apparently some IOT devices described in #2504) send their client packet with an unspecified version number, or set to version 1. 
I have confirmed that in the case of Microsoft Windows, it is able to accept and correctly interpret a valid ntp v4 packet in response. 
The RFCs for the earlier versions are from 1992 (v3), 1989 (v2) and 1985 (v1), so it seems unlikely that these clients are actually expecting data to be returned in any of these older formats, but this PR does return the onus of correct interpretation to the clients.
Delete the version …

ntp : ignore client version, always return a v4 packet

---

.github/workflows/build.yml

Merge the `build-and-test` workflows into one to largely reduce code duplication. Before this, we had two identical workflows with the only difference being the `runner` string. However, the `runner` can be part of the matrix, simplifying the entire process and reducing any unnecessary code duplication.
##Now
---
**Related issue or feature (if applicable):** https://github.com/pi-hole/FTL/pull/2501#issuecomment-2953657938
--- …

Simplify CI build process

---

test/hostnames.sh

Make the test for PTR lookups run correctly.
Before this the test is not running but fails silently.
The call in test_suite.bats checks for the absence of "ERROR" in the output, but due to the syntax error hostnames.sh was not returning anything at all.
``` bash
$ shellcheck hostnames.sh
[Line 17:]
if [[ $addr == "127.0.0.1" && $dig_result == "localhost." ]] || [[ $addr == "::1" && [[ $dig_result == "localhost." || $dig_result == "ip6-localhost." ]] ]] || [[ $dig_result == "pi.hole." ]]; then
^-- [SC1009](https://www.shellcheck.net/wiki/SC1009) (info): The mentioned syntax error was in this if expression.
>>                                                                          ^-- [SC1073](https://www.shellcheck.net/wiki/SC1073) (error): …
```

Tests - fix PTR test

---

src/log.c
src/tools/dhcp-discover.c

Fixes the string handling for `pihole-FTL dhcp-discover`
There are several issues with the string output handling of `pihole-FTL discover-dhcp` for wpad, BOOTP server, and BOOTP file.
Text truncates at four characters (if the characters are printable), eg if the dhcp option 252 (wpad host) is "nowpadhere", the output is `wpad-server: "nowa"`. In the case of a string beginning with a low unprintable character (ASCII ≤15), it prints only three characters in the output, as it is only outputting one hex character for the unprintable byte.
Examples :
`sudo Pihole-FTL dhcp-discover` to a server set with `dhcp-option=lan,252,"nowpadhere"` results in:
`wpad-server: "nowp"` rather than `wpad-server: "nowpadhere"`
Similarly to a server set with …

dhcp-discover: Fix string processing

---

src/config/dnsmasq_config.c

Hi :wave:,
after seeing https://github.com/pi-hole/FTL/pull/2405 in the latest release notes, I figured I hand this change in for RFC.
The draft [draft-davies-internal-tld-03](https://datatracker.ietf.org/doc/html/draft-davies-internal-tld-03) defines  `.internal` as  special use domain for local DNS in a home network.
These are not globally resolvable and should not be sent upstream.
Unsure, if you want to upstream this right now as it is still in draft and no RFC published yet. Let me know what you think about this.
I also held back on refactoring the two similar cases. First, because of the rule of three and second because of the RFC character of this PR.
Prevent queries for .internal domains being sent to upstream services.
**How does this PR …

[RFC] Prevent .internal queries from being upstreamed. Draft draft-davies-internal-tld-03

---

src/webserver/webserver.c

Allow users to set webhome to root "/", to serve the admin interface on the bare domain.
Prevents the redirect loop noted by @averyvigolo in #2518.
Tests if webhome is root and if so does not redirect from root.
Logs a warning if the blockingmode is IP and webhome is root on webserver startup.
N/A
---
2. I have commented my proposed changes within the code and I have …

Webserver: Allow webhome to be root

---

src/api/network.c

Avoids the logspam noted on discourse and #2525 on some static routes.
Adds an additional check against NULL string before the string comparison.
N/A
--- …

api/network Avoid NULL string comparison logspam

---

src/api/action.c
src/args.c

Show color in CLI output of FTL when `FORCE_COLOR` env var is set and set this env var when running the gravity streaming action via the API.
For reference, see https://github.com/pi-hole/web/pull/3530
---
---
4. It is compatible …

Allow forcing color in CLI output

---

.github/Dockerfile
.github/workflows/build.yml
src/api/config.c
src/args.c
src/config/cli.c
src/config/config.c
src/config/config.h
src/config/password.c
src/config/toml_writer.c
src/config/toml_writer.h
src/main.c
src/zip/teleporter.c

Add new undocumented flag `pihole-FTL create-default-config <file.toml>` which will generate a default config file without starting FTL. This `pihole.toml` is then uploaded during the build process to ftl.pi-hole.net for later use (e.g. in https://github.com/pi-hole/docs/pull/1215)
Supersedes https://github.com/pi-hole/FTL/pull/2537 
---
3. I am willing to help maintain this change if there …

Add `pihole-FTL create-default-config` option and use it to upload `pihole.toml` to `ftl.pi-hole.net`

---

src/config/config.c
src/config/dnsmasq_config.c
test/pihole.toml

Fixes the help text of the `domainNeeded` option. Discussion from https://github.com/pi-hole/FTL/issues/2563#issuecomment-3053552328
--- …

Remove domain type from domainNeeded help text

---

src/api/action.c
src/api/api.c
src/api/api.h
src/api/docs/content/specs/action.yaml
src/api/docs/content/specs/main.yaml

Removes some remaining hints to ARP flush that were forgotten in https://github.com/pi-hole/FTL/pull/2541
---
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-com …

Remove remaining traces of ARP flush

---

src/config/dnsmasq_config.c
src/dnsmasq_interface.c
test/pihole.toml
test/test_suite.bats

This PR improves the behavior of the special hostname `pi.hole` when encountered throughout deep CNAME inspection. This ensures that any defined custom CNAME rules that eventually end up in `pi.hole` get the correct interface-dependent IP addresses both for IPv4 (`A`) and IPv6 (`AAAA`). 
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2581
--- …

Improve CNAME behavior of pi.hole

---

src/args.c
src/args.h
src/config/cli.c

Add colorful output to CLI if running in an interactive terminal. Config items changed from their default value are now shown in red, similarly to how we do it in the debug log. This makes reading settings much easier, especially if you want to see which `debug` flags are enabled, e.g.
---
---
3. I am willing to …

Add colors to the --config output

---

src/database/sqlite3.h

See title. This is a maintenance patch release, the only CHANGELOG entry is:
>  Fix two long-standings cases of the use of uninitialized variables in obscure circumstances. 
---
--- …

Update embedded SQLite3 to 3.50.4

---

src/webserver/lua_web.c
src/webserver/webserver.c

As the prefix is stripped away by the proxy, we shouldn't check for it when deciding if we need to authenticate.
---
**Related issue or feature (if applicable):** https://github.com/pi-hole/FTL/issues/2596
--- …

Fix FTL running behing reverse-proxy with prefix

---

src/config/dnsmasq_config.c

There is a 50:50 chance to do boolean logic right. We chose the wrong half of it in `development`. This PR makes us use the right one (only auto-suggest the interface when the setting is *empty*). This bug has not been released but found by a very helpful `development` tester @jacklul .
For reference: The bug was introduced three weeks ago in https://github.com/pi-hole/FTL/commit/f14bf6ad2b06dcd7425e02ec96d07e031dd92cf7 (part of https://github.com/pi-hole/FTL/pull/2456).
---
**Related issue or feature (if applicable):** Fixes #2606 
--- …

Fix logic in automatic interface determination (when dns.interface = "")

---

src/args.c

Currently, `pihole-FTL --config dns.domain <Tab>` leads to `pihole-FTL --config dns.domain '"lan"'` which is incorrect due to the extra single-quotes. This PR fixes that by ensuring single-quotes are not added for ordinary strings (as double-quotes are already added by `cJSON_PrintUnformatted()`), but only for JSON arrays (like `dns.upstreams`) where they are still needed, e.g., `--config webserver.headers`.
Hence, on this branch, the autocomplete suggestion above: `pihole-FTL --config dns.domain <Tab>` now correctly leads to `pihole-FTL --config dns.domain "lan"` (mind the missing extra `''`).
The second commit furthermore adds the special escaping needed for single quotes `'"'"'` as (`ba`)`sh` do not support escaping single quotes in the C-like style `\'`.
---
**Related issue or feature …

Fix default value autocomplete suggestions

---

src/dnsmasq_interface.c

Ignore subsequent forwarding when a query has already been replied to. We do not want to show the "latest" status in the query log but the one that was responsible for the particular reply sent to the client. This fixes incorrectly shown query status for some cache-optimizer queries.
No functional change in DNS operation.
---
**Related issue or feature (if applicable):** Fixes https://github.com/pi-hole/FTL/issues/2608
--- …

Fix cache-optimizer queries in Query Log

---

src/daemon.c

See title.
---
**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** https://discourse.pi-hole.net/t/host-name-of-client-203-0-113-41-dns-vm-1-none-contains-at-least-one-invalid-character-hex-28-at-position-10/82042
--- …

Do not set domainname when the kernel replies with "(none)"

---

src/config/config.c
test/pihole.toml

`dns.hosts` uses hosts file format.
This PR adjusts the text to show `dns.hosts` option also allows more than one host name per IP.
---
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase …

Fix `dns.hosts` help text to show multiple hostnames per IP are allowed

---

src/config/toml_writer.c
src/config/validator.c
src/config/validator.h
test/test_suite.bats

Allow users to pass data into `dns.hosts` more gracefully. It will now accept also lines with leading spaces and spaces between `IP` and the first `HOSTNAME`.
Note: multiple spaces between `HOSTNAME1` and `HOSTNAME2` were already tolerated.
It's a compromise between strictly adhering to HOSTS format and usability for users copy&pasting the data into the field.
Should fix https://github.com/pi-hole/FTL/issues/2625
---
2. I have commented my proposed changes within the code and …

Be more gracefully when validating dns_hosts

---

src/api/config.c
src/api/docs/content/specs/config.yaml

Add new optional `?restart={true,false}` boolean to the `PATCH`, `PUT`, and `DELETE` `/config` endpoints for array-valued items (e.g. `dns.upstreams`, `dns.hosts` or `dns.cnameRecords`). This is the necessary change in FTL to support what we requested in https://github.com/pi-hole/pi-hole/issues/6176.
---
**Related issue or feature (if applicable):** https://github.com/pi-hole/pi-hole/issues/6176
---
2. I have …

Make restarting optional in API config endpoints

---

src/config/config.c
src/config/config.h
src/config/toml_helper.c
src/daemon.c
src/database/message-table.c
test/run.sh
test/test_suite.bats

Ensure `FTL.log` location is available until the *really* very end. Otherwise, as soon as it is `free`d, logging stops as the logging routines don't know where to they'd need to write the log lines.
While I was at it, I wondered why the `FTL.log` location was actually allocated memory, because I have not changed it from the default on my testing system. This brought me to making another commit ensuring we do not duplicate/allocate memory for values that do not differ from the current value (initialized from the default value) when ingesting the TOML config.
---
**Related issue or feature (if applicable):** Noticed in https://github.com/pi-hole/docker-pi-hole/pull/1898#issuecomment-3330179883
**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** …

Ensure we can log until the very end

---

src/api/docs/content/specs/config.yaml
src/config/config.c
src/config/config.h
src/log.c
src/log.h
src/webserver/webserver.c
test/pihole.toml
test/test_suite.bats

Add `webserver.advancedOpts` to allow specifying arbitrary CivetWeb options. This feature has been requested on Discourse.
Using this feature, it is possible to overwrite all options set by Pi-hole as CivetWeb will use only the last value of options given more than once.
As this may cause conflicts with the options Pi-hole, we log the actually passed options (a) on error and (b) always when `debug.webserver == true` to `FTL.log`.
Example of how to use:
``` bash
sudo pihole-FTL --config webserver.advancedOpts '[ "ssl_protocol_version=4", "ssl_cipher_list=AES128:!MD5" ]'
```
---
**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/custom-ssl-hsts/81930
---
**By …

Add webserver.advancedOpts

---

src/api/teleporter.c
src/database/common.c
src/database/common.h
src/database/database-thread.c
src/database/gravity-db.c
src/database/message-table.c
src/database/network-table.c
src/database/query-table.c
src/zip/teleporter.c

Adds an exponentially backing off busy handler giving us control (and debugging capabilities) of what happens while the database is busy. This has already proven to be useful in the context of researching a database deadlock, see PR #2600 
The actual implementation has been heavily inspired by the default busy handler defined in `database/sqlite3.c`.
---
---
2. I have …

Add custom SQLite busy callback

---

src/api/docs/content/specs/info.yaml
src/api/info.c
src/daemon.c

See title. Motivated by internal discussions about the updating interval of the CPU usage on the settings page.
Example:
---
---
5. I have …

Add %MEM and %CPU of FTL to GET info/system

---

src/gc.c

Try to load system load averages from /proc/loadavg first. This should prevent reporting the load averages being too high on Proxmox LXC installations.
4. File a pull request for any change that …

Try to load system load averages from /proc/loadavg first

---

src/api/docs/content/specs/lists.yaml

The list type needs to be specified as path parameter instead of payload item for `POST /lists`. This has recently been changed, however, we missed to update the example, too.
This is now fixed:
---
**Related issue or feature (if applicable):** #2648 
--- …

Fix POST /lists example
