pi-hole/FTL

setupVars.c
---
Avoid double-`free` issues by first checking if a pointer can actually be `free`d. To be able to do this, we set all pointers to `NULL` after they have been `free`d to avoid dangling behavior. Although this is the general strategy throughout the code, it was missing here in this rather old part of the entire project.
=> Check pointer values to avoid double-free issues

setupVars.c
=> FTL v2.6.2

request.c
Restructure code such that cast is not necessary for qsort comparison function
---
Should fix the issues seen with `musl` in #38 
=> Improve qsort related code

FTL.h, args.c, main.c
---
Add "no-daemon" resp. "-f" option to prevent FTL forking itself into background. Connected to #35 
=> Add "no-daemon" option

parser.c, setupVars.c
---
`strncat()` NULL-terminates the copied string while `strncpy()` doesn't!
=> Use strncat() instead of strncpy()

setupVars.c, socket.c
---
Multiple client threads at the same time might want to access/modify the same memory at the same time. This leads to undefined behavior and can result in crashs with mysterious messages.
=> Fix concurrent client threads accessing the same memory

README.md
---
See title. We do this for consistency with the `service` file in the Pi-hole core repository.
=> Use pidof pihole-FTL instead of the .pid file in the simplified debugging instructions

.gitignore, Makefile, obj/.gitignore
**How familiar are you with the codebase?:** 7
---
This adds a step in the Makefile to create the `obj` directory before making the object files. The empty `obj` directory currently in the repo is now not needed.
=> Remove need for empty obj directory in repo

FTL.h, main.c, routines.h, socket.c
---
See title. This happens in the preparation for the investigations of an `FTL` powered `API`, but does not introduce any functional change nor new code. However, it makes it easier to bind to additional ports in future versions of the code.
=> Revamp socket routines

.travis.yml, FTL.h, Makefile, README.md, args.c, config.c, database.c, flush.c, main.c, parser.c, request.c, routines.h, sqlite3.h, structs.c, test/run.sh, test/test_suite.sh
---
- Add FTL SQLite3 implementation
- We compile SQLite3 on-the-fly to become independent of installed libraries
- Limit DB file size, configurable via config file, if set to zero, the DB functionality is disabled altogether
- Add `>dbstats` to the telnet interface
=> Long-term database backend implementation

.travis.yml, README.md
**How familiar are you with the codebase?:** 1
---
Add powerpc arch to the build scripts.
=> Add powerpc arch

FTL.h, README.md, config.c, database.c, main.c
---
Instead of limiting the database by its file size, we allow setting a maximum age of the stored queries.
This limit defaults to 365 days and can be changed in the `FTL` config file (see `README` for further details).
=> Specify fixed age of queries until they get deleted

FTL.h, Makefile, database.c, main.c, request.c, routines.h
---
Refactor DB thread to run exclusively either saving queries into the DB *or* deleting old queries (i.e. every hour at minute 59 (e.g. 14:59) no queries will be saved to the DB, but instead, the remaining amount of data (14:58:01 - 14:59:59) will be saved at the next full minute (15:00)). In addition, we introduce `mutex` locks for the database handle, such that it is ensured that the database handle cannot be used more than once at the same time (that won't be needed, but an additional layer of "being sure" cannot hurt).
Fixes …
=> Refactor database thread

database.c
Reverts pi-hole/FTL#95
With new method that ensures that DB cleaning and DB insertion cannot run at the same time, this function should be safe, again.
However, it will require more extensive testing.
=> Revert "Fix SQLite3 function that is crashing"

parser.c
---
Assume a user has configured his `/var/log` using `ramfs` or some other mechanism that results in an *empty* log folder on startup.
If, by chance, `FTL` is getting started before `dnsmasq` has created its log file, `FTL` will exit with status `FAILURE`.
With these proposed changes, we pause for 15 seconds if we cannot find `pihole.log` and then test again. If the log file is there, `FTL` will continue as usual. If the file can still not be opened in the second attempt, it will exit …
=> Try again to open pihole.log if necessary

main.c, routines.h, threads.c
---
Use low-level mutual exclusive (`mutex`) locks to ensure FTLs main datastructure can only be accessed by one thread at a time. In contrast to what we use now we pass the responsibility to the scheduler of the operating system to be sure that two threads cannot run at the same time by coincidence. 
=> Use low-level mutual exclusive locks

test/test_suite.sh
---
According to https://github.com/travis-ci/travis-ci/issues/8082, there is a subsential bug on Travis CI since at least four days that has not been resolved, so far. Tests fail despite that everything is green when **all** those three points are met:
- The job runs on EC2 (we have no influence on that)
- The job contains secrets (we have them for deployment of binaries)
- The job invokes a process that goes into the background (`pihole-FTL` does that during testing)
We explicitly kill …
=> Fix Travis test suite (work around a Travis bug)

database.c
---
Currently, we log the error for each failed database transaction to `pihole.FTL.log`. This can, however, lead to extraordinary log growth as see e.g. [here](https://discourse.pi-hole.net/t/pihole-ftl-log-sql-error-attempt-to-write-a-readonly-database/3761).
Assume permissions are wrong (e.g. `pihole-FTL.db` is owned by `root` with no `w` permissions for `a`):
```
[2017-08-02 17:36:00.104] save_to_DB() - SQL error (8): attempt to write a readonly database
[2017-08-02 17:36:00.105] …
```
=> Limit maximum number of logged errors

README.md, request.c, test/test_suite.sh
---
Currently, `unique_clients` (in the output of `>stats`) returns the number of clients that `FTL` has *ever* seen in its runtime. However, this is inconsistent with the data returned by `>top-clients` which only contains clients that are active, i.e. have made *at least* one query in the most recent 24 hours.
This PR makes the behavior more consistent:
- `>stats` will return `unique_clients` that is consistent with the `>top-lists` output (count only active clients). We add a new …
=> Some tweaks for stats and top-clients

gc.c, main.c, parser.c, routines.h
---
With this modification, `FTL` tries to re-resolve the client's host names after each GC run (each full hour).
This tackles two issues:
- Host names that couldn't be (for whatever reason) resolved when `FTL` first encountered a new client (see https://github.com/pi-hole/pi-hole/issues/1507 )
- Host names that changed during the run time of `FTL`
=> Re-resolve client host names in regular intervals

README.md, request.c, test/test_suite.sh
---
Properly normalize the percentages computed from the raw statistics. This is a bug fix PR.
Very briefly summarized what went wrong: When `dnsmasq` receives a query that cannot be answered from cache, it may be forwarded to more than one forward destination. Int his case we would count e.g. four forwarded queries although we only made one request to `dnsmasq`. Hence, the count of forwarded requests has to be normalized by the number of queries that required a forwarding. The wrong …
=> Bugfix: Compute properly normalized percentages

request.c
---
Always send `EOM` at end of transmission (if connection is still alive).
I found that when we implement new features on the web interface (e.g. the Clients over time graph) but don't have the according functionality already in the background (i.e. `FTL` running on a matching branch), then the `PHP API` will hang. The reason is that it continues to wait for additional data as long as it didn't see the end of transmission (`EOM`) indicator. However - so far - the return for an unknown …
=> Always send EOM at end of transmission

parser.c
---
Assume non-contiguous entries in `pihole.log(.1)` (however they are created) like:
<pre>
Oct  3 00:00:05 dnsmasq[27516]: query[A] api.nixstats.com from 127.0.0.1
Oct  3 00:00:13 dnsmasq[27516]: query[A] checkip.dyndns.org from 127.0.0.1
<b>Oct  2 19:00:05</b> dnsmasq[27516]: query[AAAA] api.nixstats.com from 127.0.0.1
Oct  3 00:00:19 dnsmasq[27516]: query[A] checkip.dyndns.org from 127.0.0.1
</pre>
This may lead to a crash of `FTL` which assumes that time can only go in a forward …
=> Detect and skip queries older than the ones before in the same log file

FTL.h, README.md, config.c, parser.c
---
Add config flag `RESOLVEIPV6=yes|no` to specify whether `FTL` should try to resolve IPv6 addresses to host names or not. Several users (like @WaLLy3K ) have seen issues with IPv6 addresses being resolved to extremely cumbersome generic ISP host names.
=> Add RESOLVEIPV6 config flag

FTL.h, parser.c, request.c, routines.h
---
See https://github.com/pi-hole/AdminLTE/pull/583
=> Add clients over time data structure

parser.c
---
Currently, `FTL` will fail to interpret dates when restarted on Jan 01.
The problem is that `dnsmasq`'s log lacks the year which is probably being done as a filesize reduction measure. That is irrelevant most of the year. However, every year we come to the point where a year ends and a new year starts. Here, the lack of the year *can* become problematic as we have to assume a year when converting dates into times tamps. Before this commit, `FTL` always assumed the current year to be …
=> New year's issue

FTL.h, grep.c, request.c, routines.h, structs.c, test/test_suite.sh
---
Detect Pi-hole blocking status and return this on API request:
Enabled:
<pre>
echo ">stats" | nc pi.hole 4711
<b>domains_being_blocked 113207</b>
dns_queries_today 13248
ads_blocked_today 302
ads_percentage_today 2.279589
unique_domains 584
queries_forwarded 4725
queries_cached 8221
clients_ever_seen 6
unique_clients 6
<b>status enabled</b>
---EOM---
</pre>
Disabled:
<pre>
echo ">stats" | nc pi.hole 4711
<b>domains_being_blocked N/A</b>
dns_queries_today 13248
ads_blocked_today 302 …
=> Detect pihole blocking status

FTL.h, main.c, parser.c, signals.c
---
Commit https://github.com/pi-hole/pi-hole/commit/a2825be81961cee4ddbb37f9e984fe6a27faa99a in the core code base changed the standard behavior of `pihole -g` (and some others) to not restart `dnsmasq` any longer, but only instruct it to re-read its config files. Unfortunately, there is no reliable way for `FTL` to detect the latter.
Hence, https://github.com/pi-hole/pi-hole/pull/1751 will make the corresponding code send the `SIGHUP` not only to `dnsmasq` but also to `FTL`. This PR …
=> Re-parse gravity data when receiving SIGHUP

Makefile, args.c, request.c
---
On branch `master`:
```
$ pihole-FTL version
v2.9.1
```
on any other branch we use `vDev`:
```
$ pihole-FTL version
vDev-86d370e
```
=> Return special version if compiled on a branch != master

parser.c, test/test_suite.sh
---
This fixes an issue reported on [Discourse](https://discourse.pi-hole.net/t/pi-hole-dns-server-should-be-case-insensitive-but-it-isnt/5583).
Replace `strcmp` by `strcasecmp`, see e.g.
https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/rtref/strcasecmp.htm
=> Use case insensitive string comparison for wildcards

FTL.h, parser.c
---
This PR is the logical continuation of #162 
For consistency, we convert all domains, clients, and forward destinations to lower case before we use and analyze them. Before this PR, e.g., `Domain.com` was handled differently than `domain.com`.
=> Convert forward destinations, clients and domains to lower case

database.c
---
Disable FTL's database functionality on all errors except `SQLITE_BUSY`. I'm not sure if other [errors](https://sqlite.org/c3ref/c_abort.html) should be (temporarily) allowed as well, but I don't think so.
> "Error codes" are a subset of "result codes" that indicate that something has gone wrong. There are only a few non-error result codes: `SQLITE_OK`, `SQLITE_ROW`, and `SQLITE_DONE`. The term "error code" means any result code other than these three.
_This template was created …
=> Disable FTL's DB functionality on errors

args.c, log.c, request.c
---
Improve version display, fixes https://github.com/pi-hole/AdminLTE/issues/626
`GIT_BRANCH` will either be a hash (like `437af07`) or a tag (like `v2.12`). Since  `.` can never be part of a commit hash, we detect if the version is either of the format `vX.YYY` or `vXX.YYY`.
=> Improve version display

FTL.h, README.md, args.c, config.c, database.c, structs.c, test/run.sh
---
Make path and file name of FTL's long-term database adjustable via FTL's config file
=> Make long-term database location adjustable

FTL.h, README.md, config.c, database.c, main.c
---
Make interval in which FTL stores queries in the long term database easily adjustable via the config file. 
It defaults to `1.0` (once per minute).
It cannot be lower than `0.1` (every six seconds).
It cannot be larger than `1440.0` (once a day).
Related to https://github.com/pi-hole/pi-hole/issues/1839
=> Make DB interval adjustable

grep.c
---
Accept lines like `*.spot.com` as wildcard audits for domains.
One note about this:
- `*spot.com` will audit `spot.com`, `some.spot.com`, etc. but also `spotspot.com` or `totalldifferentspot.com`
- `*.spot.com` will audit `some.spot.com`, etc. but neither `spot.com` nor `spotspot.com` nor `totalldifferentspot.com`
=> Wildcard auditing

FTL.h, database.c, gc.c, log.c, main.c, parser.c, request.c, test/run.sh
---
Complete re-write of `FTL` log file parser to use `dnsmasq`'s UUIDs present in the log if option `log-queries=extra` is set. This will ensure 100% correctness of the interpreted log files.
One particular difficulty with `dnsmasq`'s `extra` logging is that it resets the UUID counter to 0 when being restarted. This poisons the whole idea of having UUIDs. A proper failsafe condition (using the idea of UUID generations) has been implemented in the new parser.
Note that this is a …
=> Handle dnsmasq "extra" logging

database.c
---
Close database after initial check so we don't keep it open forever and thereby lock it.
This may or not be related to issues some user have been seeing with `lighttpd` errors like
```
PHP Warning:  SQLite3::query(): Unable to prepare statement: 5, database is locked
```
=> Close database file after initialization

database.c
---
Imagine the following situation: A user queries some extensive data on the log term dashboard. This will cause the database to be locked for maybe up to 30 seconds. If `FTL` wants to write in this time window to the database, it is actually allowed to open and use it as `PHP` is explicitly requesting only read-only access to the database. We can even prepare all queries we want to add to the database in a `TRANSACTION`, however, at the end of the transaction, we won't be able to …
=> SQLite3: Have to finalize statements before closing database handle

.travis.yml, args.c, log.c, request.c
---
This pull request fixes the issues with versioning once and for all. Instead of using a hacky solution like detecting `(no branch)` and crossing our fingers that it means we are currently building a tagged release, we use the proper Travis environment variables and show `vDev-...` as version for **all** builds except tagged releases.
This has been tested on a private fork.
Output on branch `fix_versioning`
```
./pihole-FTL tag: 
./pihole-FTL version: vDev-4cf31d
./pihole-FTL branch: …
```
=> Final fix for Travis versioning and all the cosmetic issues we have seen

parser.c
---
Ensure that host name returned by `char *resolveHostname(const char *addr)` is always lower case. This is an issue as we currently convert the host name to lower case on the initial reading of the log (when a client is newly added) but we didn't do it again later when we ran `void reresolveHostnames(void)` which is periodically called to recognize updated host names. …
=> Ensure that host names are always lower case

request.c, test/test_suite.sh
---
-  Implement improved algorithm in `getTopDomains()`. Instead of assuming how many lines of data we have sent, we can also explicitly count them.
- Implement improved algorithm in `getTopClients()`. As a by-product this also adds the optional `desc` feature to the top clients requests where it wasn't available before.
Note that I completely removed the `skip` variable as it is not important how many lines we have already skipped when now directly count the number of returned …
=> Improve sorting and displaying algorithms for top-clients and top-domains

FTL.h, config.c, main.c, routines.h, socket.c, test/test_suite.sh
---
This pull request adds full dual-stack support for `FTL`'s `telnet`-like socket. Previously, we bound only to an IPv4 port, now we bind to both the IPv4 and IPv6 port spaces.
In case no IPv6 interface is available (e.g. in `docker`), `FTL` will bind only to the IPv4 port - just as it did before.
=> Add dual-stack socket support for FTL

request.c, routines.h, socket.c
---
This is a security fix, cherry-picking `19c54b0` from branch `new/API`. Originally I thought this could go to `development` much earlier, but now the `new/API` branch is still in progress.
Short summary of what this PR achieves: We currently use fixed buffers of length 1024 in the `request.c` results. It may happen that unexceptionally long result lines /which are not expected to happen, but may appear when e.g. the DNS resolver is malfunctioning (there are always many ways things …
=> Use dynamic instead of fixed buffers

FTL.h, main.c, routines.h, signals.c
---
Save remaining queries to the long-term database on graceful shutdown (after receiving `SIGTERM`). Experiments revealed that storing even thousands of queries does not take longer than half a second on real Raspberry Pi hardware so it can be considered safe to delay shutdown by a few millisecond. The benefit is that the long-term database will be up-to-date and there will be no missing queries that have not yet been stored in the database due to the finite database update intervals. …
=> Save queries to long-term database on exit

FTL.h, database.c, main.c, parser.c, routines.h, structs.c, test/test_suite.sh
---
This pull requests implements some general improvements for `FTL`.
Changes:
- Instead of completely parsing the log files `pihole.log` and `pihole.log.1` each time `FTL` starts up, we read the already analyzed and categorized data from the long term database. We only read those queries from `pihole.log` that are not already present in the database. This enhances the startup speed of `FTL` as well as provides some functionality we will be using with `FTL` in the future.
- Instead of …
=> Import data from long-term database

database.c, flush.c
---
According to the `queries` table schema:
```
sqlite> .schema queries
CREATE TABLE queries ( id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp INTEGER NOT NULL, type INTEGER NOT NULL, status INTEGER NOT NULL, domain TEXT NOT NULL, client TEXT NOT NULL, forward TEXT );
```
`forward` can be `NULL`, but this was not taken into account in `database.c`, causing a segfault when loading queries from the database.
**EDIT by DL6ER**: We add validation for *all* database fields in this PR to avoid importing data with impossible values. `forward` is a required field for forwarded queries (`status == 2`) but can …
=> Validate database entries on import

FTL.h, README.md, config.c, main.c, parser.c, routines.h, structs.c
---
Since the new way of getting historic data is to import them from the long-term database, there is no need for interpreting (and skipping!) each line of `pihole.log.1` any longer. If users disabled the long-term database, he will notice that some historic data is missing. This is intended as we want to encourage users to re-enable the database at least for the most recent two days (this is something we want to mention in the next blog post @jacobsalmela ) in planing for a future …
=> Don't read pihole.log.1

parser.c
---
This is a minor fix for a bug introduced in 2443b231e194acbb2e34c8e3fa912dad5ef798bb
Although harmless, it could cause wrong negative `Unknown DNS Queries` displays.
=> Mark queries we mark as not completed again as unknown

parser.c
---
Fixes #216 
When reading from `dnsmasq`'s log we always only got the IP address. We used internal name resolution to obtain a possible host name and stored both data in `FTL`'s internal data structure. However, when saving to `FTL`'s database, we only ever save the highest available level of data (that is we store the host name if it is available as host names <-> IP address correlations may change over time and having host names in the database seems to be the better choice in …
=> Fix missing information bug in findClientID()

msgpack.c
---
This fixes the issue of a too large number in our msgpack implementation on 32bit systems.
```
msgpack.c: In function ‘pack_str32’:
msgpack.c:99:2: warning: this decimal constant is unsigned only in ISO C90
if(length >= 2147483648) {
^
```
=> Fix signedness of integer constant

database.c
---
Always store client IP in the database (never the host name). We do this for consistency as we will always have IP addresses but not always host names so the current situation can actually be messy in the database. Furthermore, it should be noted that we also only ever store IP addresses (and never host names!) for the forward destinations.
=> Always store client IP in the database (never the host name)

api.c
---
Don't show queries with status `5` (blocked by black.list) when
```
API_QUERY_LOG_SHOW=permittedonly
```
or
```
API_QUERY_LOG_SHOW=nothing
```
is set in `setupVars.conf`.
=> Bugfix for API_QUERY_LOG_SHOW option

flush.c
---
`forwarddata` is set to `NULL` on lines 79 and 1357 of parser.c, and so it could be null when flush is called.
=> Fix accidentally trying to free NULL

memory.c
---
Previously, we relied on that the `strdup()` function is given by `__strdup()` on all operating systems. However, that doesn't seem to be the case. We now define our own `strdup()` function to avoid this problem.
=> Define our own strdup()

flush.c, test/test_suite.sh
---
- Check for `wildcarddomains != NULL` before trying to free them in `pihole_log_flush()`
- Extend tests to verify that no `FATAL` lines are present in `pihole-FTL.log`
=> Test for wildcarddomains == NULL in flush.c

database.c, test/test_suite.sh
---
See title. We create a new table in which we store the number of total and blocked queries since the beginning of this integration. On new systems, the tables are created from the beginning and set the DB version to 2. On existing installations (FTL DB version 1), we add the table and initialize it and set the DB version to 2 to signal that the counters table has been created.
We also store the time stamp of when this new table has been created so that we can later respond with …
=> Create new table "counters" and store integrated counters therein

sqlite3.h
---
SQLite version 3.23.0 is a maintenance release. There seems to be nothing of ultimate importance for `FTL`, but we update nevertheless as this release includes quite a large number of bug fixes.
See the change log (https://sqlite.org/releaselog/3_23_0.html) for a complete list of changes.
=> Update SQLite from 3.22.0 to 3.23.0

FTL.h, api.c, database.c, datastructure.c, dnsmasq/cache.c, dnsmasq/forward.c, dnsmasq/rfc1035.c, dnsmasq_interface.c, dnsmasq_interface.h, gc.c
---
Major improvement:
Change `reply` type and `dnssec` status to per-query instead of per-domain for more accurate data. We didn't do this in the past as we were afraid that the memory consumption would not be worth it. However, I was able to implement it with only requiring two additional bytes per query, i.e. even for millions of queries in memory, this will only attribute with a few MB of memory.
This leads to a few changes that you might notice in the Query Log:
- The DNSSEC and …
=> Several FTLDNS improvements

sqlite3.h
---
SQLite 3.23.1 is a bug-fix release that fixes some new issues mostly introduced in the recent release 3.23.0.
Although we're not affected by these new bugs (we don't use `LEFT JOIN`), there are also some nice performance enhancements in the parser so we should update nonetheless.
=> Update SQLite to 3.23.1

FTL.h, Makefile, api.c, database.c, datastructure.c, gc.c, resolve.c, routines.h, setupVars.c
---
This re-implements lots of already extensively tested code that was present in pre-FTLDNS for over a year. This implementation is only slightly different by ensuring that name resolution is done in a specific non-blocking way.
Before saving to the database (every minute by default), FTLDNS tries to obtain host names for clients and forward destinations that first appeared within this minute.
After garbage collection (once per hour by default), FTLDNS tries to re-obtain the host names …
=> Internal name resolving functionality

FTL.h, README.md, config.c, database.c, dnsmasq_interface.c
---
This solves https://github.com/pi-hole/AdminLTE/issues/719
Note that queries from `localhost` will not just be hidden but completely ignored. This will impact the generated statistics and might hide information!
=> Add IGNORE_LOCALHOST config option

dnsmasq/rfc1035.c, dnsmasq_interface.c
---
This fixes two bugs:
- IPv6 blocking doesn't work as the test for if the conversion of the IPv6 address from text to binary form worked was incorrect (`inet_pton` returns `1` on success and `0` on failure, I mixed that up due to how `bash` does it...).
- When switching on NXDOMAIN blocking, FTLDNS wasn't aware of if a domain was blocked from gravity.list or black.list as a necessary parameter for the determination of this wasn't passed through.
_This template was created based on …
=> Fix IPv6 blocking and blocking reason detection

main.c
---
Don't terminate FTL when invoked from a user != `pihole`. It seems we might want to run `pihole-FTL` as `root` on OSes that (for whatever reason) cannot use `setcap`. This is currently prevented by the code. This PR removes this restriction.
While we're at it, we add some comments in the vicinity.
=> Allow starting FTLDNS as any user

FTL.h, api.c, database.c, datastructure.c, dnsmasq_interface.c, gc.c
---
This adds a new counter for blocked queries *per client*. This duplicates the functionality we already have for domains (either total or blocked count).
The new info can be queried from the API by specifying the keyword `blocked` in addition to `>top-clients`. This option is in agreement with other available options, e.g. `>top-clients withzero blocked (29)` will work as expected. …
=> Add blocked per client counter

datastructure.c
---
Return early if no wildcard domains are defined to avoid warning to be printed although for-loop will anyhow be skipped.
This fixes a bug reported on [Discourse](https://discourse.pi-hole.net/t/fltdns-fatal-errors/9470/).
While I was working on this function, I also replaced the fixed values for the query status by their `enum` equivalents (`QUERY_CACHE == 3`, `QUERY_WILDCARD == 4`) and removed some old commented out code. …
=> Suppress wrong warning

signals.c
---
Try to obtain and log a simple backtrace on `SIGSEGV`. Although this is much less powerful than the backtrace we get from a debugger (e.g., it cannot give precise line numbers) it should at least be able to show in which function the crash happened.
As an experiment, I included this code at the very end of the function `FTL_reply()`:
```c
int *foo = (int*)-1; // makes a bad pointer
printf("%d\n", *foo); // causes the segfault 
```
On the next query that triggers this FTL hook …
=> Include backtrace on SIGSEGV

request.c
---
Add new ">reresolve" API endpoint that triggers PTR queries for all clients *FTL*DNS is aware of. This may come in handy if host names have been changed and you want FTL to acknowledge that already now instead of waiting until the next routinely re-resolving happens (at the end of GC, typically once an hour).
Example for usage:
```
$ echo ">reresolve" | nc pi.hole 4711
done
---EOM---
```
It will create a log entry in `pihole-FTL.log`:
```
[2018-05-31 11:50:46.759] Received API …
```
=> Add new ">reresolve" API endpoint

request.c
---
Add an API command to recompile the blocking regex. This will be used by the API instead of sending SIGHUP because that would require more possibly sudo-level permissions.
API command: `>recompile-regex`
The `done` message was removed from the `>reresolve` command to avoid issues with the msgpack API, and there is already an EOM sent at the end.
=> Recompile Regex API Command

regex.c
---
Previously every regex evaluation would be logged even if they took very little time:
```
[2018-06-02 00:59:14.450] Regex evaluation took 0.036 msec
[2018-06-02 00:59:15.553] Regex evaluation took 0.006 msec
[2018-06-02 00:59:16.602] Regex evaluation took 0.007 msec
[2018-06-02 00:59:18.110] Regex evaluation took 0.009 msec
[2018-06-02 00:59:18.589] Regex evaluation took 0.006 msec
[2018-06-02 00:59:19.437] Regex evaluation took 0.007 msec
```
Now they will only be logged if they go over 100ms (up for debate if we want this lower).
=> Limit Regex Logging

sqlite3.h
---
Update SQLite from 3.23.1 to 3.24.0. Although we don't use any of the new features, we can potentially benefit from **performance improvements** in this release.
Quoting relevant parts from the SQLite CHANGELOG:
- **`UPDATE` avoids writing database pages that do not actually change.** For example, "`UPDATE t1 SET x=25 WHERE y=?`" becomes a no-op if the value in column x is already 25. Similarly, when doing `UPDATE` on records that span multiple pages, only write the subset of pages …
=> Update SQLite from 3.23.1 to 3.24.0

api.c
---
Always sends the commit hash. In release builds, the commit hash was not being sent.
Example:
```
version v3.0
tag v3.0
branch v3.0
date 2018-02-14 12:45:47 -0800
```
=> Always send the commit hash

api.c
---
See title. Although this situation is unlikely to occur, it ensures that both the queries over time and clients over time start at the same time and there is no offset between the two.
=> Ensure that we do never send data that is older than maxlogtime

api.c
---
When the privacy level restricted domains or clients, the socket API would not send any data at all, while it should have sent a zero length indicator.
=> Send zero length indicator for socket clients if the privacy level prevents real data

api.c
---
Include counters for reply types (NODATA, NXDOMAIN, CNAME, IP) within the most 24 hours.
Note: This data only covers the time where *FTL*DNS actually ran. It cannot be derived from historic information in the database.
=> Include counters for individual reply types in ">stats"

config.c
---
See title.
Changing the default blocking mode to `NULL` should resolve all known issues with HTTPS requests resulting in time-outs even without users having to install custom firewall rules.
Furthermore, it will resolve issues with non-static IPv6 prefixes as handed out by several ISPs.
It will suppress the blocking page.
Users may overwrite this at any point through `/etc/pihole/pihole-FTL.conf`. …
=> Change default blocking mode to NULL

FTL.h, dnsmasq_interface.c
---
Use reverse iterations when searching for `queryID` matches. This greatly increases computational efficiency of several subroutines critical for the performance of *FTL*DNS.
This renders #306 obsolete as queries will most likely be found in the first iteration. However, if this is not the case, then we will do at most 1000 iterations to avoid expensive looping for queries that have not been stored in FTL's data structure.
=> Use reverse iterations for searching queryIDs

api.c
The word «allocated» was repeated in the telnet response to >memory.
=> Fix typo in >memory telnet response

FTL.h, api.c, api.h, datastructure.c, log.c, memory.c, request.c
---
This PR removes the `memory` sub-structure. It has been there since the very early days of FTL and was only meant for debugging reasons. As we have never used it (and cannot account for the memory used by the DNS resolver), it should be removed as more and more features make it less and less 
accurate (read as: wrong).
This PR has no negative effects besides removal of the telnet endpoint `>memory` which is, however, also not exposed through the API so only a few (or no) users should …
=> Remove memory sub-structure

regex.c
---
Empty regex filters (` `) match *anything anywhere*. Hence, they would match **all** incoming domains. Empty lines in regex.list are probably not expected to have such an effect and hence we should explicitly ignore empty lines.
A user can still decide to block everything using an explicit `.*`, however empty lines should probably not do this.
Because empty lines still ask for memory (these filters just aren't initialized), we log a warning, like:
```
[2018-06-30 13:57:29.260] …
```
=> Skip empty regex.list lines

gc.c
---
FTL includes a facility to automatically delete database entries older than a configurable time (defaulting to [365 days](https://docs.pi-hole.net/ftldns/configfile/#maxdbdays)).
However, due to a incomplete migration when reorganizing threads some months ago, this function was not triggered any longer. This is now reinstated.
=> Run DB cleaning once GC is finished

regex.c
---
In `log_regex_error()`, the `logg()` routing was given the arguments in the wrong order. Further, we should not call `free_regex()` when a single regex compilation fails as this will `free` all regex filters (incl. the correct ones).
=> Fix incorrect log_regex_error() subroutine

.circleci/config.yml
This fixes the v4.0 version issue, where a build was not triggered by the v4.0 tag.
After this is merged, tag v4.0
=> Run CI on version tags

dnsmasq_interface.c
---
Locally defined addresses, like
```
address=/my.home.device/192.168.1.123
```
are shown as "OK (cached)" in the Query Log page.
However, users may want to use advanced configurations to implement wildcard blocking behavior using config files and do not want to see these queries being denoted as "OK (cached)" but rather "Pi-holed (wildcard)".
This PR adds support for such blocking configurations where we add support for two ways of blocking through config files:
1. `server=/domain/` …
=> Add user-defined wildcard blocking support

dnsmasq/cache.c, dnsmasq/dnsmasq.h, dnsmasq_interface.c
---
Show "regex.list" as source of regex blocked queries instead of `unknown`. Exemplary log lines are now:
```plain
Aug 12 21:31:30 dnsmasq[14331]: 1507 127.0.0.1/47018 query[A] twitter.com from 127.0.0.1
Aug 12 21:31:30 dnsmasq[14331]: 1507 127.0.0.1/47018 /etc/pihole/regex.list twitter.com is 0.0.0.0
```
=> Show "regex.list" as source of regex blocked queries

.circleci/config.yml
---
This fixes the missing branch issue from #344. A tag build does not have a branch because tags are separate from branches, so if there is a tag the branch is assumed to be master.
Tag builds are also uploaded to a folder named after the tag, instead of master.
=> Fix missing branch tag build

dnsmasq_interface.c
---
With #353, we introduced a new blocking type that is shown in the Query Log (`Blocked (external)`). This PR introduced this for Quad9 (blocking signaled by returning NXDOMAIN with set AD bit). This PR adds support for a different type of blocking that is used by OpenDNS. OpenDNS uses Cisco Umbrella which is a cloud security platform that blocks certain domains. Blocking is signaled by returning one of the IP addresses listed …
=> Detect externally blocked based on returned IP address (e.g., for OpenDNS)

FTL.h, config.c, main.c
---
Add `DBIMPORT` config boolean that allows skipping the initial import of historic information from the database.
This may come in handy on very large networks where the startup of FTL is large delayed when it imports millions of queries.
It provides an alternative fix for problems like https://github.com/pi-hole/pi-hole/issues/2374, retaining the possibility to use the long-term database for subsequent queries.
=> Add DBIMPORT config boolean

FTL.h, api.c, config.c, main.c
---
This PR speeds-up the specialized `>getallqueries` subquery types as we outsource the client / domain detection.
Previously, we compared the domain name / client host name / client IP address in each query to the requested address. Instead, we do now determine the ID of the requested domain / client in front of the large loop. The comparison in the expensive loop itself reduces to an integer comparison, speeding up the code.
There is no functional change involved with this PR.
_This …
=> Tweaks for ">getallqueries"

dnsmasq/dnsmasq.c, dnsmasq_interface.c, dnsmasq_interface.h
---
When started as `root`, e.g., because capabilities are not available on the current system, we drop from `root` to some unprivileged user as soon as we did everything we needed to do as `root` (open privileged ports, etc.).
Unfortunately, the log and database files were still owned by `root` in this case and hence no further logging was possible, neither to the database nor to the `pihole-FTL.log` file.
This PR fixes a bug discussed on …
=> Ensure proper file ownerships if pihole-FTL is started as root

dnsmasq_interface.c
---
Fix usage of wrong variable in `query_externally_blocked()`. This bug is only present in the `development` version of FTL.
Due to this error, *FTL*DNS may get instable when seeing externally (OpenDNS, Quad9) blocked queries.
The previously used counter (`counters.forwarded`) count the number of known forward destinations and should not have been changed here. The correct counter for the number of forwarded queries is `counters.forwardedqueries`.
This PR also fixes some random typos …
=> Fix usage of wrong variable in query_externally_blocked()

grep.c
---
Let `FTL` determine the blocking status using the new variable `BLOCKING` introduced in https://github.com/pi-hole/pi-hole/pull/2356
=> Determine blocking status enabled/disabled by reading setupVars.conf

dnsmasq/option.c
---
Apply a [patch](http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=dd33e98da09c487a58b6cb6693b8628c0b234a3b) streamlined for `dnsmasq v2.80`.
This problem was introduced in [2.79](http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=6b2b564ac34cb3c862f168e6b1457f9f0b9ca69c). This fixes #367.
This patch would also be part of `dnsmasq v2.80`, however, it is unclear if 2.80 will be stable before we release Pi-hole v4.1. It won't be an issue to upgrade the internal `dnsmasq` …
=> Apply patch: Fix crash parsing a --synth-domain with no prefix.

dnsmasq/rfc1035.c
---
Fixes compilation warning
```
dnsmasq/rfc1035.c: In function ‘answer_request’:
dnsmasq/rfc1035.c:1484:10: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
if (!dryrun)
^~
dnsmasq/rfc1035.c:1486:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
FTL_cache(crecp->flags & ~F_FORWARD, name, &addr, NULL, daemon->log_display_id);
^~~~~~~~~
```
Fortunately, this error
- is only in `development` not in `master`
- should …
=> Add guarding {} around if statement

resolve.c
---
The "new" flag on the client struct seems to indicate if the name has not been resolved. It is true when the client is created, and then set to false when the name is resolved. There was one place where the name was resolved and the flag was not updated though, which this fixes.
=> Don't forget to reset "new" flag on client struct when name is resolved

dnsmasq_interface.c
---
Previously the externally blocked query check only considered the answer IP address, so it marked queries blocked by gravity.list and regex.list as externally blocked. Now it will skip locally resolved queries (with the `F_HOSTS` flag).
=> Don't count locally blocked queries as externally blocked

main.c
---
The exit timer was not started, so now it is started when FTL logs that it has started.
Bug symptom:
```
########## FTL terminated after 1536432013312.0 ms! ##########
```
Fixed output:
```
########## FTL terminated after 23132.3 ms! ##########
```
=> Fix exit message showing invalid program run time

sqlite3.h
---
Changelog: https://sqlite.org/releaselog/3_25_0.html
It doesn't seem like this update will bring any particularly new feature we could use but we should nevertheless keep on track with the regular releases of SQLite as those are the best supported ones.
We may want to use (at some point):
- Add support for renaming columns within a table using `ALTER TABLE table RENAME COLUMN oldname TO newname`
which is added in this version of SQLite. …
=> Update SQLite to 3.25.0

FTL.h, api.c, database.c, datastructure.c, dnsmasq_interface.c, gc.c, memory.c, routines.h, shmem.c
---
The array of overTime structs is separate from the client data, because the client data is dynamically sized. Each client has a separate shared memory block named `/FTL-client-ID` where `ID` is the numerical ID of the client. The client data is an array of ints, which is indexed using
the overTime time indexes.
Before, the code referenced the client data via
```
overTime[timeIndex].clientdata[clientID]
```
Now, the code references the data via
```
overTimeClientData[clientID][timeIndex]
```
The client data is updated whenever a new client or overTime slot is added, so referencing the client data should always be valid. …
=> Put overTime data into shared memory

regex.c
---
- Don't return -1 as number of read whitelist domains if there is no whitelist file.
- Also, don't try to free the array of whitelist domains if there are none.
Both "bugs" are harmless, I have just seen them on a fresh install.
=> Fix behavior when no whitelist file is present

request.c, test/test_suite.sh
---
FTL now hosts the DNS server for the network, so allowing anyone to kill it is a security issue.
Replaces #394
=> Kill the >kill command

FTL.h, database.c, dnsmasq_interface.c
This DB ID will be available through shmem to the API to support transparent overlap with the SQlite3 database. It is marked `[WIP]` as it needs to be further tested (e.g. when no database is present on the system).
=> Store database ID in queries struct

FTL.h, database.c, dnsmasq_interface.c, gc.c, request.c, resolve.c, routines.h
---
Move resolution of client and upstream host names to a dedicated thread. This PR fixes #404 
=> Move resolution of client and upstream host names to a dedicated thread

dnsmasq_interface.c
---
Modify the correct corresponding counters for user-defined dnsmasq config file blocking rules (may it be `NXDOMAIN` or `NULL` based). Thanks to @jpgpi250 for pointing out negative blocked numbers (private communication).
=> Properly account for user-defined wildcards

dnsmasq/dnsmasq.h
---
Fix interchanged indices in `dnsmasq.h`. This bug resulted in sometimes having displayed `regex.list` even though the blocking was done due to a `gravity.list` entry. Although being of only cosmetic nature, this bug showed up every now and then and was never really traceable.
The problem appeared when more than one additional hosts file was loaded (e.g. `gravity.list` + `black.list`). As the first file would have gotten index `3` and the second `4`, and `record_source(4)` returned …
=> Fix record_source() sometimes incorrectly returning regex.list

config.c
---
This fixes the incorrect parsing of the blacklist and "bad address" errors printed to the dnsmasq log. This was a regression from stable, and appeared after #416.
=> Revert blacklist file path to the original

api.c
---
Simplify upstream percentage computation.
The way we compute the forward destination percentage is a leftover from pre-v3.0 times. Back then we counted each `forwarded to ...` line as one forwarded query. With v3.0, we started to skip duplicated `forwarded to ...` lines as we had now the query IDs and were able to rule out what was a duplicate.
This check is now here:
https://github.com/pi-hole/FTL/blob/da8c2765a58fcd701bdbcb0f7a4528990f554dea/dnsmasq_interface.c#L275-L286
Hence, …
=> Simplify upstream percentage computation

dnsmasq_interface.c
---
Fix query status if forwarded query was partially replied to from cache. This may happen if we were able to answer a CNAME from cache but need to ask the upstream server for details concering one of its components. This PR ensures that the query status is set to forwarded only *after* the check if it has been replied to from cache as the latter is a null-op otherwise.
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE). …
=> Fix query status if forwarded query was partially replied to from cache

gc.c
1
---
This PR modifies the type of lastGCrun in gc.c from `int` to `time_t`. 
The reason is as follows:
- time() returns a 64bit integer in recent c libraries
- the previous implementation implicitly casted 64 bit value to 32 bit value in the following code segment
`lastGCrun = time(NULL) - time(NULL) % GCinterval;`
- if the subtraction returns a value that overflows int value, …
=> Modify type of lastGCrun to avoid overflow

dnsmasq_interface.c
---
This PR changes the default blocking mode to use a combined cache entry that is valid for both, `A` and `AAAA` entries. This will lead to a memory saving of exactly 50% concerning the blocked domains DNS cache. Almost all users will immediately benefit from a lowered memory footprint of `pihole-FTL`. Furthermore, it will make `NULL` blocking mode usable for those who have hit memory limitations with millions of blocked domains on low-end periphery like Raspberry Pi Zero devices. …
=> Half memory usage of NULL blocking mode

args.c, dnsmasq_interface.c, log.c
---
no-daemon mode operates just like debug mode, but without the debug output, and dnsmasq is not in debug mode.
Note that there is an issue in no-daemon mode where Ctrl-C and other such signals do not stop FTL like in debug mode. However, I could only fix this by putting dnsmasq in debug mode...
=> Fix no-daemon mode forking dnsmasq and not logging

dnsmasq_interface.c
**By submitting this pull request, I confirm the following (please check boxes, eg [X])**:
---
Make sure to zero initialize the `all_addr` structs we are using for the IPv4 and IPv6 target addresses.
This should resolve a bug that was reported on [Discourse](https://discourse.pi-hole.net/t/very-strange-ipv6-blocking-addresses/15197/9).
Furthermore, this zero initialization allows a great simplification of `prepare_blocking_mode()` as `inet_pton("0.0.0.0")` resp. `inet_pton("::")` do nothing else than filling the corresponding structs with zeroes.
=> Zero initialize all_addr structs

request.c, resolve.c, shmem.c, shmem.h, socket.c
---
This bug does only exist in `development` and is not contained in any release code.
This PR want to merge three improvements/bugfixes concerning out internal locks:
- **Name resolution is broken in `development`.** This PR ensures that the lock is released when resolving host names. This is necessary as we otherwise block the main thread which is supposed to do the resolving.
- Add debugging output for locks. Although it increases the verbosity of the debug mode, this information …
=> Fix: Deadlock situation in resolving subroutines

shmem.c
---
If an empty string is being added, reuse the one at position zero. This makes sure all empty strings used elsewhere in shared memory have a position of zero.
This fixes a slight bug in API, which assumes that all empty strings have position zero.
=> Reuse the empty string at position 0 in string shared memory

.circleci/config.yml, Makefile, capabilities.c, docker/aarch64/Dockerfile, docker/arm/Dockerfile, docker/armhf/Dockerfile, docker/x86_32/Dockerfile, docker/x86_64/Dockerfile, main.c, routines.h
---
Add check for required Linux capabilities. Complain loudly when the required capabilities are missing.
Initially, I wanted the check to be fatal, but I know there are many users out there that run `pihole-FTL` on marginally supported platforms which (partially) don't even support capabilities. Since I don't want them to be unable to start FTL at all, we only log missing capabilities instead of failing hard.
Fixes #432  …
=> Add check for required Linux capabilities

dnsmasq_interface.c
---
Blocked domains should not have the `REVERSE` flag set, i.e., they should never be the answer to reverse lookups to the IPs they are assigned to (0.0.0.0, RPi's IP address, ...)
This fixes a bug reported on [Discourse](https://discourse.pi-hole.net/t/very-strange-ipv6-blocking-addresses/15197/56?u=dl6er).
Example: With FTL v4.1.2:
```
$ dig +short ptr 0.0.0.0.in-addr.arpa
facebook.com.
```
(can be any blocked domain)
With this PR:
```
$ dig +short ptr 0.0.0.0.in-addr.arpa
``` …
=> Gravity domains should not have REVERSE set

database.c
---
Queries imported from the database now have the "unknown" DNSSEC type. This also explicitly marks the queries with an unknown reply type. However, this was already happening before, because `REPLY_UNKNOWN` equals 0, and the struct is zero-initialized.
=> Mark queries imported from the database as having an unknown DNSSEC type

networktable.c
---
Fixes #462 
The problem was that when any SQL error happened (including `macvendor.db` not present), we returned a static string. A subsequent call to `free()` tried to release this static string which failed.
We fix this by always ensuring that we return a `free`-able pointer.
This PR does not need to be mentioned in the Release notes as if fixes a bug that is only present in the `development` branch. …
=> Always allocate also empty strings in getMACVendor()

FTL.h, shmem.c
---
The SHM settings currently contain the version of shared memory that FTL is exposing. The current version of shared memory is 1. Whenever a change is made to structures stored in shared memory, or the layout of shared memory, the version should be incremented (like how the database version is
incremented when the database changes).
This version number will be used by the API to verify it is using the same version of shared memory as FTL.
Note that when the API adds the version verification, it will not be compatible with FTL v4.2, due to that branch not having this change. …
=> Add an "/FTL-settings" shared memory block

config.c, routines.h, setupVars.c
---
The config file parser is too sensitive towards possibly existing extra characters that may be in a line but are invisible to the user. This includes that lines terminated in CR-LF (e.g., config file stored by a non-Unix system) and ones including spaces at the end of the string have not been recognized and skipped. This PR implements trimming of the config file values by using the inbuilt `isspace()` function which will remove any of the following characters from both, the head and …
=> Trim any whitespace characters around config keys

dnsmasq_interface.c
---
Ensure that the loop in `findQueryID()` cannot start with negative indices. This was the case when there where zero queries in the memory.
=> findQueryID(): Ensure indices are non-negative

docker/arm/Dockerfile
---
There have been a few issues trying to support armv6 hard-float, notably nettle crashes even when not using DNSSEC. This change will also increase the amount of devices able to run FTL by supporting armv6 devices without hard-float. The performance impact is expected to be low.
=> Use armv6 soft-float for the arm build

datastructure.c, routines.h, shmem.c
---
Explicitly use `clientID` for `newOverTimeClient()` instead of using the private variable `overTimeClientCount` to avoid (possibly) error-prone double-entry bookkeeping.
=> Explicitly use clientID for newOverTimeClient()

dnsmasq/dhcp6.c, dnsmasq/inotify.c, dnsmasq/network.c, dnsmasq/rfc1035.c, dnsmasq/util.c
---
I repeated the merging procedure for dnsmasq v2.79 -> v2.80 and slowly went through all code lines over the past few hours. There are a few differences including one fatal error (a logic inversion!) concerning DHCP + IPv6 which was causing crashes in IPv6 enabled networks when the Pi-hole DHCP server was enabled.
This code is verified to work with a fully IPv6 enabled network whereas `release/v2.80` and `development` currently crash on the same box.
The goal of this PR is to again …
=> Fix dnsmasq v2.80 implementation

datastructure.c
---
In release/v4.2, the `counters->clients++` call was moved to be after `newOverTimeClient`. When that change was merged to development, the first call was accidentally not deleted, causing it to happen twice (before and after `newOverTimeClient`).
=> Fix counters->clients getting incremented twice due to v4.2 merge

dnsmasq_interface.c
---
Use improved criterion for detecting "externally blocked" status.
All three points must now be met:
- `AD` bit set, 
- `RA` bit **un**set (new!), and 
- `RCODE` is `NXDOMAIN`
=> Use improved "externally blocked" criterion

docker/arm/Dockerfile
---
The `libcap-dev` dependency was installed from `libcap-dev:armhf`, but it seems the compiler did not find it when compiling development builds, causing the development arm build to fail. Before the armv6 change, the dependency was installed as `libcap-dev`, so it has been changed back to that since it works.
The package installation has been split into two sections, one for the packages required to install the compiler and custom libraries, and the second for the rest of the packages. The first section is earlier in the container, as it does not change much, whereas the second section changes more often then the compiler and libraries, so it is after both.
_This template was …
=> Add libcap-dev to docker container and optimize container for changes

dnsmasq/rfc1035.c
---
This PR fixes a new bug that came up when merging dnsmasq v2.80 in #480 where the blocking status of individual queries is not detected by `pihole-FTL` when using `BLOCKINGMODE=NXDOMAIN` or `NXDOMAIN`.
Since neither of the two `BLOCKINGMODE`s are recommended, this is not a severe bug as blocking itself still works fine and just displaying is broken. I expect only very few users to be affected. …
=> Re-add source record passing to subroutines

dnsmasq/config.h, dnsmasq/rfc1035.c, log.c, main.c, routines.h, signals.c
Release fixing two issues:
- Blocking status display for `NODATA` and `NXDOMAIN` blocking modes
- File permission issues when using shared memory on systems that lack Linux capabilities support
It also adds in a new feature:
- Report both the user `pihole-FTL` **started** as and the user `pihole-FTL` **crashed** as in case it crashes and generated a crash ticket in `pihole-FTL.log`
=> Pi-hole FTL v4.2.1

dnsmasq_interface.c
---
The code was changed to prevent negative indices from being used, but the `validate_access` call was not updated. This causes "fatal" errors to be written to the log even though there is no fatal error.
=> Fix incorrect fatal error message in findQueryID

database.c
---
If no queries were saved to the database, the last timestamp field would be set to zero instead of left as it was. In addition, this commit skips adding zero to the other counters in the database if there were no saved queries.
=> Fix last timestamp getting set to zero if no queries were saved

database.c, networktable.c, sqlite3.h
---
This updates SQlite3 to v3.27.1. We intentionally skipped v3.27.0 as it was known to contain a bug and v3.27.1 was released only one day later.
This PR furthermore enables the SQLite3 logging callback such that SQLite3 errors and warnings are written to `pihole-FTL.log` instead of going to `stderr`, meaning that they are currently lost in most situations.
Change log:
- https://sqlite.org/releaselog/3_27_1.html
The only point relevant for us seems to be:
- Issue an `SQLITE_WARNING` …
=> Update SQLite3 to v3.27.1

FTL.h, shmem.c, shmem.h
**This release fixes #496**
Issue
---
DNS requests and responses can happen over UDP or TCP. UDP is the most common, but TCP is used often for large responses or by some specific products (we have seen this with Netflix in the past). Handling TCP connections requires more communication with the client and server, so `pihole-FTL` creates TCP helper **processes** by forking.
When dynamically allocated shared memory objects get resized, they get resized, and then re-mapped. The problem is that if our shared memory object is now significantly larger and if this happens on a TCP handler process, the other processes were not notified about the virtual memory change keep using the old shared memory, i.e., they were using dangling pointers. This caused a memory corruption or access error when …
=> Pi-hole FTL v4.2.3

FTL.h, shmem.c, shmem.h
---
Code maintenance, merging the latest hotfix into development.
Note that there is one additional change: In 9593233, I moved `close(fd)` further up and into the `if(resize)` code as suggested here: https://github.com/pi-hole/FTL/pull/519#discussion_r259225257
=> Merge hotfix changes into development

shmem.c
---
The overTime shared memory size is now a multiple of the struct size, which is required for the API to safely connect to shared memory.
=> Align overTime shared memory to struct size

shmem.c
---
Due to the requirement of having to be perfectly page-aligned for the API, we used to allocate the shared memory objects in steps of `pagesize`. While this seems meaningful for both, `queries` and `domains`, it doesn't seem useful for `clients` and `forwarded` as rarely any user should see more than 1000 entries in them.
This PR uses the recently added LCM calculator to compute the optimal (minimum) amount of memory that ensures perfect page-alignment.
- `clients`: Allocation step …
=> Use LCM to compute optimal allocation step for dynamic shared memory objects

shmem.c
---
Under certain circumstances, it happened that the obtained optimal (= minimum) page-aligned was too small to hold the entire `overTime` array. Although there was a check for this, we only logged that there is an issue but a `exit(1);` was missing so FTL kept running. This inevitably lead to memory corruption.
We extend this by adding an additional parameter with which we can specify how many slots we want to have *at least*. …
=> Fix shm crash caused by an insufficient obtained optimal structure size

dnsmasq_interface.c
---
Don't create IPv6 cache entries when `IPV6_ADDRESS` is empty in `setupVars.conf`.
Currently, we create empty (`::`) IPv6 entries when users set `BLOCKINGMODE=IP` in `pihole-FTL.conf` when the `IPV6_ADDRESS` variable is empty (or unset) in `setupVars.conf`.
This PR ensures that IPv6 entries are not created in `IP` mode when we don't have a suitable address for them.
=> Don't create IPv6 cache entries when IPV6_ADDRESS is empty

main.c, shmem.c
---
This PR is a follow-up on #527 and adds:
- Output result of optimum size calculation when `DEBUG_SHMEM` is enabled
- Ensure `pihole-FTL.conf` and crash handler are set up before we create shared memory objects (so that the `DEBUG_*` values are already known early on during initialization)
- Log which size has been used we used the multiplier
This PR fixes a bug that is only present …
=> Follow-up on #527

FTL.h, Makefile, daemon.c, datastructure.c, networktable.c
---
Add `-Wshadow` to extra warning flags. `-Wshadow` defaults to `-Wshadow=global` and implies `-Wshadow=local`. Apply corresponding changes due to shadowing of variables in the current codebase.
`man gcc` excerpt:
> ```
> -Wshadow: Warn whenever a local variable or type declaration shadows
> another variable, parameter, type, class member, or whenever a
> built-in function is shadowed.
> ``` …
=> Add -Wshadow to extra warning flags

Makefile, api.c, config.c, database.c, dnsmasq_interface.c, gc.c, log.c, memory.c, msgpack.c, networktable.c, overTime.c, regex.c, request.c, routines.h, setupVars.c, shmem.c, signals.c, socket.c
---
Function attributes help the compiler to optimize functions calls and to check our code more carefully during compilation.
I implement the following attributes:
1. `pure` used for `cmpasc()`, `cmpdsc()`, `in_whitelist()`, `command()`, `getSetupVarsBool()`, `find_equals()`
Many functions have no effects except the return value and their return value depends only on the parameters and/or global variables. Such a function can be subject to common subexpression elimination and loop …
=> Declare attributes for functions in FTL

FTL.h, Makefile, api.c, api.h, args.c, database.c, datastructure.c, dnsmasq/dnsmasq.h, dnsmasq_interface.c, grep.c, log.c, main.c, memory.c, msgpack.c, networktable.c, regex.c, request.c, resolve.c, routines.h, setupVars.c, shmem.c, shmem.h, socket.c
---
This PR adds further general improvements for our code base.
Highlights:
- Added many additional warning flags that are useful and are neither included by `-Wall` and `-Wextra`
- Declare many `char*` which should not be changeable in the corresponding subroutines as `const char*` to have the compiler enforce their immutability.
- Enforce strict prototyping for FTL routines. This ensures that functions have to be *either* made explicitly global (by adding a prototype to the suitable …
=> Further general improvements

FTL.h, regex.c, routines.h, shmem.c
---
This PR improves on the inner-struct alignments. While this does not change any functionality, it results in reduced padding and, due to this, we save a lot of space. This will immediately reduce `pihole-FTL`'s memory footprint.
| struct | before | after | reduction |
| --- | --- | --- | --- |
`queriesDataStruct` | 72 | 56 | **22 %** |
`domainsDataStruct` | 32 | 24 | **25 %** |
`clientsDataStruct` | 656 | 648 | 1 % |
`ConfigStruct` | 32 | 28 | 12.5 % |
`whitelistStruct` | 16  | 16 | …
=> Improve inner-struct alignments

FTL.h, config.c, dnsmasq_interface.c
**How familiar are you with the codebase?:** _
---
Do not mark `PTR` requests as `externally blocked (NULL)` when we serve an entry from cache. This bug exists in the `development` branch only.
Also add new `DEBUG_EXTBLOCKED` property for `pihole-FTL.conf` that logs reasons for why FTL decided a query was externally blocked.
=> Do not mark cached PTR queries as externally blocked even if NXDOMAIN

FTL.h, resolve.c
---
This PR adds a few micro-optimizations and a bug fix for the host name resolving routines.
Improvement:
- Do not add host names of clients and upstream servers if they haven't changed.
Bug fix:
- Any determined host name was allocated using `strdup()`. However, as a consecutive `free()` was missing, some memory got lost.
=> Improvements for hostname resolving routines

FTL.h, api.c, database.c, datastructure.c, dnsmasq_interface.c, gc.c, memory.c, networktable.c, overTime.c, regex.c, resolve.c, routines.h, shmem.c
---
This change removes the global objects:
- `queries`
- `clients`
- `domains`
- `forwarded`
They are now all only be available through corresponding getter functions that will return a pointer to exactly one specific entry. Each cal to a pointer getter is accompanied by corresponding boundary checks. We will have to evaluate if - and if how much - effect this has on FTL's performance.
This change does not affect the shared memory the API uses.
_This template was created based on the …
=> Prevent direct access to global objects queries, clients, domains, and forward

dnsmasq_interface.c
---
Fixes a bug introduced in #529 which applied some major changes in how we access memory objects. This bug is only present in the `development` branch, neither any release nor the current release branch `release/v4.3` are affected.
=> Fix trying to free the wrong variable

gc.c, log.c, routines.h
---
Use thread-safe alternatives of `ctime()` and `localtime()`. 
`ctime()` and `localtime()` fill data into a `char` array resp. `tm` struct in global memory and then return a pointer to that memory. If the function is called from multiple places in the same program, and especially if it is called from multiple threads in the same program, then the calls will overwrite each other's data which we want to avoid. …
=> Use thread-safe alternatives of ctime and localtime

resolve.c, shmem.h
---
Fixes #567 
A reference to shared memory was used after unlocking shared memory, which caused a crash when shared memory was resized.
This PR also removes some extra semicolons in the macro definition of `lock_shm` and `unlock_shm`.
=> Fix string reference held across locks

api.c, args.c, shmem.c
---
Use `memcpy()` instead of `strncpy()` in cases where we want to use only parts of strings. GCC 8.1 and higher warns about using `strncpy()` when it detects a truncation of the string to be copied already at compile time.
=> Use memcpy instead of strncpy where advised

database.c
---
An unnecessarily high amount of messages was printed when the database file did not exist. This is, however, not an unlikely case (new installs, database file was corrupted, ...) and hence we should handle it better.
Previously:
```
[2019-05-25 16:17:16.610 1252] SQLite3 message: cannot open file at line 38565 of [884b4b7e50] (14)
[2019-05-25 16:17:16.610 1252] SQLite3 message: os_unix.c:38565: (2) open(/etc/pihole/pihole-FTL.db) -  (14)
[2019-05-25 16:17:16.610 1252] db_init() - …
```
=> Do not print errors when we create the database for the first time

shmem.c
---
Several micro-optimizations for the shmem `addstr()` subroutine mostly targeted at reducing the overall complexity. This PR contains a fix for a possible memory corruption issue when a string exceeding the `pagesize` is given to `addstr()`. Note that this might be no real issue as strings we handle are size limited (typically less than 250 bytes).
=> Prevent possible memory corruption in addstr()

networktable.c, resolve.c
Fixes the following bugs:
- Crash when resolving clients, caused by holding a reference to shared memory after unlocking it. #567
- Possible crash when updating the network table, caused by accessing shared memory without a lock
=> Hotfix v4.3.1

networktable.c
---
Fix unlocking shared memory lock outside of the networktable loop, we want to lock during the entire loop to avoid interruption of the transaction.
This error has been introduced in #571
=> Fix unlocking shared memory lock outside of networktable loop

database.c, networktable.c
---
This PR fixes #576. Further details can be found therein.
If multiple clients (with the same `hwaddr` but different IP addresses) have been added in the past, they will be fused to unique entries.
This PR bumps the database version to 4 without changing the structure. The version update is merely to signal that the unification of clients in the `network` table has been done on the given database. …
=> Identify clients by hardware address not hardware + IP address

Makefile
---
The `DESTDIR` variable is specified by the user on the make command line as an absolute file name. For example:
```
sudo make DESTDIR=/tmp/stage install
```
Where the installation step would normally install `/usr/bin/pihole-FTL`, then an installation invoked as in the example above would install `/tmp/stage/usr/bin/pihole-FTL` instead. The `DESTDIR` path is created, if necessary. Note that `root` capabilities are nonetheless required for the `install` step as only `root` can add …
=> Add support for DESTDIR

test/run.sh, test/test_suite.bats
---
Tests: Test against `WARNING` and `ERROR` messages in `pihole-FTL.log`. We explicitly ignore the two warnings complaining about missing capabilities. They are unavoidable on the testing machine.
=> Tests: Test against WARNING and ERROR messages

Makefile, database.c, files.c, misc.c, routines.h, test/run.sh, test/test_suite.bats
---
Explicitly set permissions of database files after their creation.
Fixes #586
=> Explicitly set permissions of database file after creation

.circleci/config.yml, Makefile, docker/x86_64-musl/Dockerfile, log.c
---
Compile x86_64-musl binary as static position independent executable. A static position independent executable is similar to static executable, but can be loaded at any address without a dynamic linker.
As a test, I downloaded the generated `pihole-FTL-musl-linux-x86_64` binary into a Debian-based `x86_64` container and made it executable. Thereafter, ran our test suite* using this binary and all tests succeeded.
---
*) For running the tests, 
- cloned the `FTL` repository, 
- …
=> Generate self-contained musl binary

Makefile, api.c, args.c, dnsmasq/option.c, log.c, routines.h
---
So far we used a different algorithm to determine the version in `pihole -v` and other places. This is inconsistent and, hence, a potential bug.
This PR fixes this by providing a common function based on the command line result.
---
Exemplary output in the log file:
```
[2019-06-18 20:18:52.296 365] FTL branch: fix/versions
[2019-06-18 20:18:52.296 365] FTL version: vDev-e0c3577
[2019-06-18 20:18:52.296 365] FTL commit: e0c3577
[2019-06-18 20:18:52.296 365] FTL date: 2019-06-18 …
```
=> Unify version determination mechanism

dnsmasq_interface.c, gravity.c, main.c, regex.c, request.c, routines.h
Use `vw_whitelist` view of table `whitelist` when checking if a domain is contained in the whitelist instead of copying whitelisted domains on receipt of `SIGHUP` into FTL's memory.
This change will not only decrease FTL's memory footprint but also allow a much better scaling to very large / huge whitelists (looking into the 100k+ domains regime).
---
To achieve good performance, we constantly keep the database connection to `gravity.db` open to have a prepared (= precompiled to SQLite …
=> Use whitelist table in gravity.db directly

database.c
---
If the fifth argument of `sqlite3_bind_text()` has the value `SQLITE_TRANSIENT`, then SQLite makes its own private copy of the data immediately, before the routine returns. If, however, the argument is `SQLITE_STATIC`, then SQLite assumes that the information is in static, unmanaged space and does not need to be freed.
As the scope of all strings we pass to the binding routines is larger/longer than the scope of the entire transaction, we can safely use `SQLITE_STATIC` here to avoid …
=> Change SQLITE_TRANSIENT to SQLITE_STATIC

src/database/common.c, src/database/common.h, src/database/network-table.c, src/database/query-table.c, src/main.c
---
Improve error checking in the database routines to cover all actions that can fail, e.g., due to readonly database errors.
- Check if the `pihole-FTL.db` database is still available at the beginning of all database routines in `database/common.c`
- Log if we failed to update the database from version 3 -> 4 and return early if this is the case.
- Simplify logging in case of an error.
Previously:
```
[2019-07-06 17:00:55.526 32339] SQLite3 message: statement aborts at 36: [CREATE …
```
=> Database error checking

src/config.c
---
Currently, setting `DEBUG_ALL` to `true` forces all debugging options to be enabled. If one would want to enable all *but* a single debug option, they had to manually add all except the one they don't want.
With this change, debug options can now selectively be removed even when `DEBUG_ALL` is set to `true`.
Possible use cases:
- `DEBUG_ALL` is unset or set to `false`: No change to previous behavior, all flags need to be enabled individually
- `DEBUG_ALL` is set to `true`: No change …
=> Improve debug flag handling in config file

.circleci/config.yml, Makefile, src/log.c, test/test_suite.bats
---
Print architecture and compiler (incl. version) used to compile the `pihole-FTL` binary. This information will be logged and will also be contained in each crash log.
Example for a pre-compiled binary:
```
[2019-07-15 14:52:37.279 20967] ########## FTL started! ##########
[2019-07-15 14:52:37.279 20967] FTL branch: development
[2019-07-15 14:52:37.279 20967] FTL version: v4.3-303-g5e85489-dirty
[2019-07-15 14:52:37.279 20967] FTL commit: 5e85489-dirty
[2019-07-15 14:52:37.279 20967] …
```
=> Print architecture FTL was compiled for

src/config.c, src/config.h, src/regex.c
---
Add new config flag `REGEX_IGNORECASE` that can be enabled to make FTL's regex case insensitive. It defaults to false (legacy behavior).
A documentation update will be added later.
=> Add new config flag REGEX_IGNORECASE

src/database/common.c, src/database/common.h, src/database/network-table.c, src/database/query-table.c
---
If the transaction fails to open or commit, the shared memory would not be unlocked. This change ensures that shared memory is unlocked in the SQL error case. Also, the SQL statement that failed in the macro is logged.
=> Fix failure during parse_neighbor_cache not unlocking shared memory

src/FTL.h, src/database/common.c, src/database/gravity-db.c, test/test_suite.bats
---
Adding an explicitly allowed timeout of 1000 milliseconds to `pihole-FTL.db` will allow short intervals of busyness to be tolerated by FTL. As `pihole-FTL.db` is only used by threads surrounding the DNS server, this should have no implications on the performance of `pihole-FTL`.
Note that we explicitly set zero timeout for `gravity.db` as timeout might have an influence on DNS resolution due to lookups in the whitelist tables. …
=> Add database busy timeouts

src/database/common.c
---
Ensure we always initialize the database lock mutex even if an error causes us to return early in `db_init()`.
This PR fixes #625 (at least I assume this given the limited information available there so far).
=> Fix possible crash if database is locked on startup

tools/macvendor.py
---
Fix using wrong index when looking for comments in the downloaded file causing the following error:
```
$ python3 macvendor.py 
Downloading...
...done
Processing...
Traceback (most recent call last):
File "macvendor.py", line 32, in <module>
if line[0] == "#" or line == "":
IndexError: string index out of range
```
This bugfix changes two things:
1. Check *first* if the string is empty (short-circuit evaluation)
2. Check the first (instead of the second) character against `#`
_This …
=> Bugfix for tools/macvendor.py

src/dnsmasq/crypto.c, src/dnsmasq/dnsmasq.h
---
This PR fixes two compilation issues with FTL.
1. Fixes #603 - we currently compile against libnettle3.4 on the CI. We cherry-pick this commit from the official `dnsmasq` repository to resolve this issue already now.
2. Recent versions of GCC (tested on `gcc version 9.1.1 20190503 (Red Hat 9.1.1-1) (GCC)`) are currently unable to compile `dnsmasq` resp. `pihole-FTL` because of
```
src/dnsmasq/dhcp.c: In function ‘dhcp_packet’:
src/dnsmasq/dhcp.c:182:17: error: ‘SIOCGSTAMP’ …
```
=> Fix compilation errors in development

Makefile, src/database/sqlite3.h
---
This PR updates the contained SQLite library from version 3.28.0 to version 3.29.0.
There are a few optimizations for the query optimizer, however, more importantly, this release allows us to finally obsolete the [double-quoted string misfeature](https://sqlite.org/quirks.html#dblquote). We use this new feature.
It should be checked if we never used double quotes (by accident) in any release version of FTL. I open this PR as a work-in-progress as I cannot check this right now.
=> Update contained SQLite from 3.28.0 to 3.29.0

src/dnsmasq_interface.c, test/test_suite.bats
---
Our tests currently rely on `regexa.com` to not exist. However, this domain recently became available and is now causing our tests to fail. This PR fixes this by not assuming that `regexa.com` does not exist.
This PR also fixes a small bug as domain equivalence checks should be case-**in**sensitive (which wasn't the case before).
=> Fix tests: regexa.com is now registered

src/database/gravity-db.c
---
Do not try to bind to statements that might not be available when preparing the database failed. This prevents a possible fix when one of the database tables is not available.
This potential bug exists only in `development`.
=> Fix bug seen with incomplete databases

src/api/socket.c
---
Ensure `sockaddr_un.sun_path` does not overflow even for articially large `FTLfiles.socketfile` buffers. This bug has never been observed in the wild and does not seem to be exploitable.
=> Ensure sockaddr_un.sun_path does not overflow

src/database/network-table.c
---
Ensure to reset (=terminate) running statement before calling `DELETE` that affect the transaction. SQLite3 does not accept such a `DELETE` in a running statement resulting in a failed network table upgrade if there are multiple entries for the same hardware address.
=> Restructure network table upgrade procedure

src/database/sqlite3.h
---
See title. This is a code maintenance pull request. There isn't anything particularly useful in the changelog.
Detailed changelog:
1. Add support for the FILTER clause on aggregate functions.
2. Add support for the NULLS FIRST and NULLS LAST syntax in ORDER BY clauses.
3. The index_info and index_xinfo pragmas are enhanced to provide information about the on-disk representation of WITHOUT ROWID tables.
4. Add the sqlite3_drop_modules() interface, allowing applications to disable …
=> Update SQLite from 3.29.0 to 3.30.0

src/database/sqlite3.h
---
Changelog:
1. Fix a [bug in the query flattener](https://www.sqlite.org/src/info/1079ad19993d13fa) that might cause a segfault for nested queries that use the new FILTER clause on aggregate functions.
2. Cherrypick fixes for other obscure problems found since the 3.30.0 release
=> Update SQLite from 3.30.0 to 3.30.1

src/dnsmasq_interface.c
---
Ensure that `print_flags()` cannot overflow. Note that this is a mere code improvement and not really a security fix as current code cannot be exploited. Only a small (and fixed!) subset of flags can be set at once, none of the configured configurations can come even close to the available 256 bytes.
Nevertheless, this PR changes the code to go from hard-coded string limits to fully adaptive limits ensuring we do not accidentally introduce bugs in the future when more flags get added …
=> Security: Ensure print_flags() cannot overflow

src/database/network-table.c, src/database/network-table.h, src/resolve.c
---
This PR implements a [feature requested on Discourse](https://discourse.pi-hole.net/t/show-name-in-top-clients-lists-rather-than-ipv6-addresses/23893/).
With this PR we add the `network` table as secondary data source for client host names. This ensures that devices with multiple IPs (on the same network interface) can all be identified by the host name of the machine even if a only one IP address <-> host name association is available.
Especially concerning IPv6 addresses, this …
=> Use network table as secondary source for client host names

src/database/network-table.c, src/database/network-table.h
---
The subroutine `getDatabaseHostname()` is guaranteed to allocate "fresh" memory not pointing to any existing objects. Hence, it should be given the attribute `((malloc))`.
=> Add malloc attribute to getDatabaseHostname()

src/api/api.c, src/datastructure.c, src/dnsmasq_interface.c, src/gc.c, src/overTime.c, src/resolve.c
---
In case requested object is out of range (`ID < 0` or `ID > maximum`) or has an incorrect magic byte, get getter functions in `shmem.c` return `NULL`. We have check against such `NULL`s before accessing the objects to avoid memory issues and segmentation faults.
Unfortunately, there are many getters and, hence, we have to add many guards. In a more high-level language, something like this will probably done by the language/compiler for us, but as C is a rather low-level language …
=> Check pointers before accessing content

Makefile, src/config.c, src/config.h, src/dnsmasq/cache.c, src/dnsmasq/dnsmasq.h, src/dnsmasq_interface.c, src/dnsmasq_interface.h
Signed-off-by: DL6ER <dl6er@dl6er.de>
---
This PR adds a new debug option. Then enabled, the embedded `dnsmasq` will append `file:line` information for each line (see example below).
`DEBUG_DNSMASQ_LINES=false` (standard):
```
Dec 10 10:53:31 dnsmasq[21723]: query[A] team.pi-hole.net from 192.168.2.223
Dec 10 10:53:31 dnsmasq[21723]: forwarded team.pi-hole.net to 8.8.8.8
Dec 10 10:53:31 dnsmasq[21723]: query[AAAA] team.pi-hole.net from 192.168.2.223
Dec 10 10:53:31 dnsmasq[21723]: …
```
=> Add DEBUG_DNSMASQ_LINES debug flag

src/config.c, src/config.h, src/dnsmasq_interface.c
---
Add `CNAME_DEEP_INSPECT` config option (default: true).
It can be used to disable deep CNAME inspection.
This might be beneficial for very low-end devices.
=> Add CNAME_DEEP_INSPECT config option

test/run.sh
---
The CI cannot always resolve the host names so the tests are written to test for IP addresses.
However, when it can occasionally resolve host names this leads to false-negatives during the CI testing. This PR enables already existing config settings of FTL that prevent it from trying to resolve client host names during the tests.
=> Do not try to resolve client host names during the tests

src/dnsmasq_interface.c, src/shmem.c, src/shmem.h
---
Change ownership of all shared memory objects to the user/group configured in `/etc/dnsmasq.d/01-pihole.conf`. We already do this for `pihole-FTL.log` and `pihole-FTL.db` but forgot to do this for the shm objects.
=> Change ownership of all shared memory objects before switching user

src/datastructure.h, src/dnsmasq_interface.c, src/regex_r.h
---
Changes as discussed on [Discourse](https://discourse.pi-hole.net/t/dev-whitelisting-issue-due-to-cname-blocking/26366).
Whenever we encounter a whitelisted domain, we do not analyze the rest of the CNAME path. This results in whitelisted CNAMEs being permitted, even if they contain to-be-blocked domains. Furthermore the same short-circuiting is done when a whitelisted domain is found while doing the deep CNAME inspection.
=> Tweak CNAME whitelisting behavior

src/dnsmasq_interface.c
---
If we find during a deep `CNAME` inspection that we want to block the entire chain, the originally queried domain itself was not counted as blocked (but as permitted). Later in the chain, when we find that this is a bad guy, we short-circuit it. We need to correct the domain counter of the domain at the head of the chain, otherwise, the data for the top lists is misleading.
For this, we go back the entire path and change the original request to blocked by increasing the blocked count of this domain.
We do this, because the value for the permitted list is computed as `permitted = total - blocked` so it doesn't change when we increase both, the subtrahend and the minuend by one. …
=> Top lists fix for deeply blocked CNAME chains

src/dnsmasq/forward.c, src/dnsmasq_interface.c
---
This PR fixes two bugs in FTL. One was the detection of the address which should be used to reply to a request, the other was the correct synthesis of the DNS header response codes and the requirement of the absence of answer section records for `NODATA` and `NXDOMAIN` blocking modes.
Both issues are fixed by the PR and only appeared when using a different blocking mode than `NULL` (which is Pi-hole's default).
=> Fix for blocking modes

src/dnsmasq_interface.c
---
Necessary backend changes for https://github.com/pi-hole/AdminLTE/pull/1138
=> Store additional data when a deep CNAME inspection identified a domain to be blocked

Makefile
---
Use `libidn`. This will improve support for internationalized domain names (IDNs) by adding an automated conversion from locale's encoding to a legit ASCII domain name string. We do not use `libidn2` as there are some [bug reports](https://redmine.pfsense.org/issues/7820) and we found issues trying to compile statically against `libidn2`. Additionally, there seems to be no clear advantage compared to using `libidn`.
For this to work, we need to add `libidn11-dev`  to our CI …
=> Add support for IDNs in HOSTS files.

src/dnsmasq_interface.c
---
Do not block queries when a domain is known to be blocked, however, the entire CNAME chain is to be permitted.
This should fix a bug reported on [Discourse](https://discourse.pi-hole.net/t/some-domains-are-intermittently-blocked-even-though-they-are-on-the-whitelist/27477/10), waiting on conformation it fixes the issue before switching this PR to live.
=> Fix internal DNS cache twist

.circleci/config.yml
Don't use the `latest` tag, use the specific version.
Fixes #683
=> Pin build image to specific version.

src/database/gravity-db.c, test/gravity.db.sql
---
This speeds up FTL start and reload actions. See discussion [here](https://discourse.pi-hole.net/t/disabling-pi-hole-breaks-dns-for-1-min/274929).
=> Use precomputed gravity count from database

src/dnsmasq_interface.c
---
Propagate ID of responsible regex up from the child to the parent domain if blocking happened during CNAME inspection.
Related Discourse discussion: https://discourse.pi-hole.net/t/request-show-regex-responsible-for-blocking/27656
=> Propagate ID of responsible regex up in CNAME inspection

src/database/gravity-db.c
---
Access to the gravity database is essential for correct working of `pihole-FTL`. Try to reopen the gravity database when it was not available due to an existing lock.
=> Try to reopen gravity database when not available

src/dnsmasq/cache.c, src/dnsmasq/rfc1035.c, src/dnsmasq_interface.c
---
Correctly handle `REFUSED` responses. There are mainly two possibilities for such replies:
- **Forwarding failed because no forward destinations are known.**
This happens when `/etc/resolv.conf` is empty and there are no upstream servers specified in `/etc/dnsmasq.d/01-pihole.conf`. `dnsmasq` rejects such queries with response code `REFUSED`.
- **Forwarding cannot happen as we ran out of resources.**
`dnsmasq` limits how many concurrent queries can be made. Once this number is reached, it will reject further queries until the backlog has been cleared.
This PR also makes sure to correctly process received `SERVFAIL` replies sent from forward destinations.
=> Correctly handle REFUSED and SERVFAIL responses

src/config.c, src/config.h, src/daemon.c, src/daemon.h, src/main.c
---
Adding a supported way of delaying the startup of the embedded `dnsmasq`. Even though it would be good to solve this otherwise, it is still better to do this in a supported way instead of hacking `cron` jobs or modify the `init.d` files which makes debugging much harder.
=> Add DELAY_STARTUP setting to delay startup of the embedded dnsmasq

src/database/common.c
---
This was broken before as we returned too early (the SQLite3 engine was not yet fully initialized) when the long-term database was disabled.
=> Ensure blocking also works when the long-term database is not used

src/config.c, src/database/network-table.c, src/database/sqlite3-ext.c, src/database/sqlite3-ext.h, src/datastructure.c, src/resolve.c
---
This PR fixes a bug in `release/v5.0` reported in #718.
The underlying heap memory access violation occurred only when there are both, multiple addresses for the same devices in the ARP table, and only some of these addresses are already known to FTL (i.e., they sent DNS queries to the Pi-hole before).
If either all addresses of a device (or likely none) were already known to FTL because they made requests in the past, this bug doesn’t show up.
This is likely because users with IPv6 are much more likely to see this bug as there is a high likelihood that an interface has at least one address that has never been used to ask Pi-hole any questions. Multiple addresses on the same …
=> Fix FTL crashes in ARP table parsing

Makefile, src/config.c, src/config.h, src/database/gravity-db.c, src/database/gravity-db.h, src/datastructure.c, src/datastructure.h, src/dnsmasq/config.h, src/dnsmasq/dnsmasq.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h, src/main.c, src/signals.c, src/vector.c, src/vector.h
---
FTL is a complex multi-dimensional application. The main process has a number of threads surrounding it, each of which performing specific duties (like updating the database, resolving host names and parsing the network (ARP) cache, ...). To make things even more complicated, FTL adds yet another level of parallelism, namely it forks the main process in order to maintain individual DNS clients connecting over a persisting TCP connections. The forking is done to ensure a non-blocking DNS resolution even in the presence of persistent connections.
During the investigation of #698, we have been remindet that SQLite3 is [not …
=> Restore fork-safety

src/database/gravity-db.c
---
With Pi-hole v4.x we had wildcard-support in the audit log. When migrating this list into the database, we lost this ability. This PR is the successor of #722 which aimed at restoring this feature. A few changes were necessary that exceeded Github's ability to suggest changes so I moved this into a new PR, preserving the OP's authorship of the first commit.
This PR is milestoned for still being included in the v5.0 release.
=> Restore audit wildcard-support

src/config.c, src/config.h, src/dnsmasq_interface.c, src/resolve.c
---
This PR modifies FTL's internal resolver to work in two phases:
- First, try to obtain a host name by using the internal resolver (i.e., FTL).
- In a second step, only executed when FTL didn't know the answer, we ask the resolvers as configured by `resolvconf`.
We've seen that the latter is necessary to get proper name resolution in docker environments. This change turns out to be necessary for some upstream servers such as 1.0.0.1 and ensures that FTL is always the first server that gets asked for host names.
This PR also considers if FTL runs on a non-default (!= 53) port, e.g., in testing environments.
=> Improve internal resolver algorithm

src/config.c, src/config.h, src/datastructure.c, src/datastructure.h, src/dnsmasq_interface.c
---
[Encrypted Server Name Indication (ESNI)](https://tools.ietf.org/html/draft-ietf-tls-esni-06) is certainly a good step into the right direction to enhance privacy on the web. It prevents on-path observers, including ISPs, coffee shop owners and firewalls, from intercepting the TLS Server Name Indication (SNI) extension by encrypting it. This prevents the SNI from being used to determine which websites users are visiting.
ESNI will obviously cause issues for `pixelserv-tls` which will be unable to generate matching certificates on-the-fly when it cannot read the SNI. Cloudflare and Firefox are already enabling ESNI.
According to the IEFT draft, we can easily restore …
=> Automatically block _esni.* subdomains of blocked domains

src/dnsmasq/dnsmasq.c, src/dnsmasq/dnsmasq.h, src/dnsmasq/netlink.c
---
Revert intermediate fix and install solution chosen by [`dnsmasq` upstream](http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=913fa15fb1d11f50aeb7a9a1f68de5af0eac0419):
Reply by Simon:
> The presence or absence of `NETLINK_NO_ENOBUFS` in the system headers is only coincidentally related to whether `qemu-user` supports the syscall.
> 
> The best we can do is to convert the `setsockopt()` failure into a warning rather than a hard failure, or fix `qemu-user`, of course.
=> Install proper qemu fix

src/config.c, src/config.h, src/regex.c
---
Make regex matching case-insensitive by default and remove config option to control this (added in https://github.com/pi-hole/FTL/pull/620).
=> Make regex matching case-insensitive by default

src/args.c
---
Add dnsmasq drop-in replacement support. Fixes #734
=> Add dnsmasq drop-in replacement support

src/database/gravity-db.c, src/vector.c
---
When FTL detects that `gravity.db` has been corrupted in any way (maybe a user deleted an essential table within the database, or the database is malformed due to I/O issues such as unrecoverable power-loss failures), it tries to release all allocated memory for this database. Unfortunately, this could have given rise to a crash under certain conditions when trying to free memory which wasn't allocated. This could have happened when we failed very early in preparing the database statements, such as during the preparation of the audit-list table statement.
We fix this by ensuring that invoking `free_sqlite3_stmt_vec()` on a `NULL` pointer is a harmless no-op. This routine will …
=> Fix FTL crash on closing handle to corrupted databases

src/database/sqlite3-ext.c
---
Fixes bug reported on Discourse + adds more debugging output to the subnet matching.
=> Fix bit-order in subnet mask generation

src/database/gravity-db.c, src/database/sqlite3-ext.c, src/datastructure.c, src/datastructure.h
---
This allows to configure specific settings for a whole range of devices but still exclude others. Complain softly (no error) if multiple configured subnets match with the same number of relevant bits.
We log in case there are multiple groups defined matching equally which one FTL chose. It will deterministic chose the most matching *last added one*.
resulting in the following log line (only the last line is logged in non-DEBUG mode, I kept all for illustrative proposes here):
```plain
[2020-05-11 20:26:55.425 18858] SQL: Comparing 127.0.0.1 vs. 127.0.0.0/8 (subnet 255.0.0.0) - !! MATCH !!                                            
[2020-05-11 20:26:55.425 18858] SQL: Comparing …
```
=> Always chose best (= maximum match) subnet for clients

Makefile, src/database/common.c, src/database/message-table.c, src/database/message-table.h, src/datastructure.c, src/dnsmasq_interface.c, src/regex.c
---
This PR is no. 1 in a series of commits which will eventually lead to a new diagnosis environment in Pi-hole ensuring easily accessible and helpful error messages
Regex errors are now logged more verbosely, like:
```plain
[2020-05-11 20:10:03.636 17925] REGEX WARNING: Invalid regex blacklist filter "(((": Unmatched ( or \(
[2020-05-11 20:10:03.663 17925] REGEX WARNING: Invalid regex blacklist filter "![^(": Unmatched [ or [^
```
caused by
Furthermore, the information will be available on the web dashboard where users can easily see and address them:
The new web interface page will be added in a follow-up pull request.
=> Store warnings in database table

src/database/gravity-db.c, src/database/gravity-db.h, src/database/message-table.c, src/database/message-table.h
---
Store `SUBNET` warnings in the database. This will add warnings as in this example (first entry):
=> Store subnet warnings in the message table

.circleci/config.yml
Internal PR: Following the [CircleCI v2.0 documentation](https://circleci.com/docs/2.0/env-vars/) our check for skipping external contributions from uploading to our binary bucket doesn't work any longer.
We should instead use:
Variable | Type | Value
-- | -- | --
`CIRCLE_PR_USERNAME` | String | The GitHub or Bitbucket username of the user who created the pull request. **Only available on forked PRs.**
I verified that `${CIRCLE_PR_USERNAME}` was indeed set to `fhriley` on #772 whereas it is empty in this build (you can see in the CircleCI run that the binary was uploaded).
=> Skip CircleCI Upload step on PRs coming from forks

src/dnsmasq_interface.c, src/signals.c
Signed-off-by: Frank Riley <fhriley@gmail.com>
**How familiar are you with the codebase?:** 5
---
I made two simple optimizations that speed up cached queries quite a bit:
1) The code was opening, reading, and parsing the config file for every query to get the privacy level. Instead, I am using the cached level. Now, a change of privacy level only takes effect when reloading FTL. Considering the performance improvement, I think this is acceptable.
2) `inet_ntop` is an expensive function and was being called for every query. It …
=> Simple optimizations

src/signals.c
---
We often have to ask for debugging details when users submit error reports. This improves the embedded backtrace generator significantly by allowing FTL to translate its own stack addresses into code lines. This will be very helpful for us in future crashes.
**Before**
```plain                                                                           
[2020-05-20 12:16:51.385 236182] Received signal: Segmentation fault 
[2020-05-20 12:16:51.385 236182]      at address: (nil)                                                                                                                                                   [26/1840]
[2020-05-20 12:16:51.385 236182]      with code: …
```
=> Improve self-generated backtraces

FTLtest.sh, src/config.c, test/run.sh, tools/socket_client.c
**How familiar are you with the codebase?:** _8_
---
On modern OS versions, /var/run is not used anymore but /run instead. For backwards compatibility /var/run is a symlink to /run, but /run should be consequently used to be failsafe. The `pihole-FTL.service` file currently uses /run for the port file and both, /var/run + /run inconsistently for the PID file. The following PR addresses this by changing all to /run: https://github.com/pi-hole/pi-hole/pull/3248
Both PRs should be hence merged together, as of: https://github.com/pi-hole/pi-hole/pull/3248#issuecomment-620752054
More background about /run vs /var/run: …
=> Use /run instead of /var/run for FTL runtime files

src/dnsmasq/rfc1035.c
---
`dnsmasq` added caching for `SRV` records. As FTL wasn't aware of this new type of cache records, it displayed query response "Unknown (0)" for cached SRV records (the first query, which was forwarded, did show the correct status).
As this was missing, it gave rise to a few bug reports, e.g.,
- https://github.com/pi-hole/FTL/issues/759
- https://github.com/pi-hole/pi-hole/issues/3399
- https://discourse.pi-hole.net/t/pi-hole-v5-0-query-log-shows-status-unknown-9-since-having-upgraded-from-v4-4/32386
This PR adds analysis capabilities for cache `SRV` records to resolve these issues.
=> Process cached SRV records

src/config.c, src/config.h, src/resolve.c
---
This adds a new option `NAMES_FROM_NETDB` which allows to disable the try to obtain an addresses host name using the network table.
One use case it that there is a IPv6 client without a host names itself.
However, using the network table we can find out that this client is the same device where we also kwon an IPv4 address together with a valid host names for. In this case, we use the host name associated to the other address as this is the same device. This behavior can now be disabled using `NAMES_FROM_NETDB=false`
This feature has been discussed on Discourse: https://discourse.pi-hole.net/t/incorrect-hostnames/33111
=> Add NAMES_FROM_NETDB option

src/database/gravity-db.c, src/datastructure.c, src/datastructure.h
---
Store client group information in shared instead of process-local memory. Fixes #786
=> Store client group information in shared memory

src/config.c
---
See title. This improves consistency.
=> Allow no/false and yes/true for all config options.

src/resolve.c
---
Reacquire client and upstream pointers after a name resolution. As we're leaving the locked area for the resolve, we cannot control if the shared memory object changed meanwhile. If it did, then the pointers will point into nowhere, leading to a `SEGV_MAPERR`.
This PR fixes #785
=> Reacquire client and upstream pointers after a name resolution

src/capabilities.c, src/config.c, test/run.sh, test/test_suite.bats
---
Set nice value of pihole-FTL to increase DNS server performance. The new niceness default to `-10` (lower is less nice = getting more CPU cycles for our own). The value can be changed through a config option. Changing the niceness can be avoided by setting `NICE=0` (this will set `0` as niceness, which is the default) or `NICE=-999` (this will skip trying to set the niceness, altogether).
If the user is not allowed to change their niceness, FTL will log:
```
NICE: Cannot change niceness to -10 (permission denied)
```
If the user specified an invalid niceness, it will be clamped to the according extremum (`+/- 20`):
```
NICE: Set process niceness to -20 (asked for -100)
```
If …
=> Be less nice

src/database/common.c, src/database/common.h, src/database/message-table.c, src/database/message-table.h, src/resolve.c
---
Add a message for Pi-hole diagnostics when host names with invalid characters have been found during FTL's internal name resolution (typically client host names containing non-ASCII characters).
Example:
```
$ grep /etc/hosts "127.0.0.53
127.0.0.53 Cöfte
```
results in
id|timestamp|type|message|blob1|blob2|blob3|blob4|blob5
--|--|--|--|--|--|--|--|--
98|1590222660|HOSTNAME|127.0.0.53|Cöfte|1|||
where `message (TEXT)` = IP of the host names, `blob1 (UTF8 TEXT)` = the obtained host names, `blob2 (INT)` = position of the invalid character
=> Add warning for invalid hostnames to FTL message table

src/database/gravity-db.c, src/database/gravity-db.h, src/regex.c
---
Be explicit (=do not rely on "hidden" short-circuit evaluation principles) about if we count or query the number of domains. This simplifies the current logic and makes the subroutine overall somewhat more readable.
This has been reported to resolve an issue with added delays on DNS server reloading.
=> Simplify domain counting logic

src/dnsmasq/config.h, src/dnsmasq/dnsmasq.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h
---
We've seen reports where connection termination due to timeout and foreign client disconnecting can happen at the same time (on milliseconds accuracy). The detailed bug description can be found in https://github.com/pi-hole/FTL/issues/816#issuecomment-660013854.
We're performing four changes in this pull request:
1. We skip second termination if there is already a termination event in progress. This ensures that a running termination cannot be interrupted. To ensure non-interruptibility, we use C11 atomic functions ensuring we generate atomic test code.
2. In addition to step 1, we try to ensure that this situation does not even happen by doubling the TCP worker timeout from 105 …
=> Improve TCP worker handling

src/database/gravity-db.c, src/database/gravity-db.h, src/datastructure.c
---
Wrap gravity reopening in locking to avoid a race collision with API requests. As these are performed from independent threads, it was possible that API calls could have been received in the middle of a database reopening. This can lead to a crash in SQLite3.
Fixes #841 where the fix has already been confirmed to work.
=>  Safely reopen gravity database

src/database/common.c, src/database/query-table.c, src/dnsmasq/cache.c, src/dnsmasq/rfc1035.c, src/dnsmasq_interface.c, test/test_suite.bats
---
- Add `additional_info column` to queries table. We fill it with the domain that caused blocking the entire CNAME chain.
- Log CNAME blocking to pihole.log
- Store + import ID of regex used for blocking in `additional_info` field
- Fix an edge-case where CNAME blocking can be foiled when parts of the CNAME chain are already in the cache
- Fix incorrect attribution of the blocked status to the wrong domain. This also simplifies the terminology in the CNAME inspection routine
=> Add logging for CNAME inspection

src/CMakeLists.txt
---
Factor out FTL sources into a separate object. This slightly enhances compilation speed.
=> Make FTL builds faster

src/dnsmasq/cache.c, src/dnsmasq/config.h, src/dnsmasq/dbus.c, src/dnsmasq/dhcp-common.c, src/dnsmasq/dnsmasq.c, src/dnsmasq/dnsmasq.h, src/dnsmasq/forward.c, src/dnsmasq/network.c, src/dnsmasq/option.c, src/dnsmasq/radv.c, src/dnsmasq/tftp.c
---
Update the embedded `dnsmasq` to the just released (5 hrs ago) dnsmasq v2.82.
Changelog:
```
version 2.82
Improve behaviour in the face of network interfaces which come
and go and change index. Thanks to Petr Mensik for the patch.
Convert hard startup failure on NETLINK_NO_ENOBUFS under qemu-user
to a warning.
Allow IPv6 addresses ofthe form [::ffff:1.2.3.4] in --dhcp-option.
Fix crash under heavy TCP connection load introduced in 2.81. <--- This is already included in FTL 5.1
Thanks to Frank for good work chasing this down.
Change default lease time for DHCPv6 to one day.
Alter calculation of preferred and valid times in router
advertisements, so that these do not have a floor …
```
=> Update embedded dnsmasq to v2.82

src/dnsmasq_interface.c
---
Fixes #858 and #854. This bugfix has independently been verified by two users in the referenced issue tickets.
=> Create and use a temporary copy of the domain string during the analysis

src/api/api.c, src/config.c, src/config.h, src/database/query-table.c, src/gc.c, src/overTime.c, src/signals.c
---
`musl` 1.2.0 changes the definition of `time_t`, and thereby the definitions of all derived types, to be 64-bit across all archs. This and related changes are collectively referred to as "time64", and are necessary so that data types and functions dealing with time can represent time past early 2038, where the existing 32-bit type on 32-bit archs would overflow.
Explicitly cast `time_t` to (`long long`) before printing to address the `musl`-decision to make `time_t` a 64-bit variable even on 32-bit machines.
=> Explicitly cast time_T

src/api/api.c
---
Add new telnet API hook `>getallqueries-client-blocked` allowing to show only blocked queries for a specific client.
=> Add ability to show only blocked queries for a specific client

src/resolve.c
#
---
Show also possible IPv6 name servers when `DEBUG_RESOLVER` is enabled. They are stored in a somewhat auxiliary (external) structure so they were not included in FTL's debug outputs **even when they were used** during resolving host names. Hence, this PR is a purely cosmetic change without any effect on the functionality. Without `DEBUG_RESOLVER` being enabled, the changed printing routine is never called.
Before:
```
[2020-08-16 21:15:52.793 21996/T22008] Trying to resolve 127.0.0.2
[2020-08-16 21:15:52.793 21996/T22008] Using nameservers:
[2020-08-16 21:15:52.793 21996/T22008]  0: 127.0.0.1:53 (IPv4)
[2020-08-16 21:15:52.793 21996/T22008]  1: 0.0.0.0:0 (IPv4)
[2020-08-16 …
```
=> Show also IPv6 nameservers in DEBUG_RESOLVER

src/dnsmasq/rfc1035.c, src/dnsmasq_interface.c
---
Fix error displaying if the upstream server replied with REFUSED or SERVFAIL
Before (incorrect):
```
[2020-08-23 14:37:44.124 15047/F15035] **** got reply error is ::500:a505:dcc1:1656:0
```
Now (fixed):
```
[2020-08-23 14:37:44.124 15047/F15035] **** got reply error is REFUSED (nowhere to forward to)
```
=> Fix error displaying if the upstream server failed

src/CMakeLists.txt, src/args.c, src/dhcp-discover.c, src/dhcp-discover.h
---
This add a new feature to scan all available interfaces for available DHCP servers.
Usage:
``` bash
sudo pihole-FTL dhcp-discover
```
=> Add dhcp-discover feature

src/dhcp-discover.c
---
Request a lease with validity of 1 second in the DHCPDISCOVER packet of the `dhcp-discover` feature
Considered valid by `wireshark`
=> Request a lease with validity of 1 second in the DHCPDISCOVER packet

src/datastructure.c, src/datastructure.h, src/resolve.c, src/shmem.c
---
This PR is a feature request from discourse (see link below). Only try to resolve host names of upstream servers which were recently active. The current limit for "recently active" is hard-coded to two hours.
=> Only resolve active clients

src/dhcp-discover.c
---
Fixes warnings showing up with the most recent `gcc` compiler. The code still works the same, however, it is a bit safer, so this is a good change. The fix is to not print the existing buffer into itself but to append to the string by starting to write from the memory address immediately behind the current content of the buffer.
=> Fix GCC9 regression for printing the same buffer into itself

src/api/api.c
---
Extend domain filtering to also check the CNAME domain for domain-filtering (if this is indicated by the query status).
This fixes a subitem of #833 we seemingly have forgotten.
http://pi.hole/admin/queries.php?domain=aax-eu.amazon.de
http://pi.hole/admin/queries.php?domain=aax-eu-retail-direct.amazon-adsystem.com
Note: Reply type "N/A" is expected as I restarted FTL in between and these are queries re-imported from the database.
=> Extend domain filtering to also check the CNAME domain for domain-fil

src/config.c, src/database/network-table.c
---
This PR enables cleaning of IP addresses from the `network_addresses` table which have not be seen for a set number of days. The maximum age of entries can be controlled though the `MAXNETAGE` config option and defaults to the value of `MAXDBDAYS`.
`MAXNETAGE` can be set to zero if a user doesn't want auto-cleaning.
=> Clean network addresses

src/resolve.c, src/resolve.h
---
This fixes a variant of the bug in `development` which was forgotten in https://github.com/pi-hole/FTL/pull/889
=> Do not block shared memory when inactive upstreams are skipped

src/signals.c
---
As soon as the memory in `/dev/shm` is used up completely, access to it may fail and FTL is being killed by the memory manager (receives `SIGBUS`). Before this PR, such an event caused FTL to fail silently.
Now, we catch the memory manager error and show a proper crash report (we cannot do anything else when the memory manager prevents us from reading any memory at all).
It will be visible as a regular crash report with some information, like:
```
[2020-09-25 14:24:53.424 121019M] Received signal: Bus error
[2020-09-25 14:24:53.425 121019M]      at address: 0x7ffff7ca9000
[2020-09-25 14:24:53.425 121019M]      with code:  BUS_ADRERR (Non-existant physical address)
```
Similarly, …
=> Handle SIGBUS SIGILL and SIGFPE in our crash reporter

src/shmem.c
---
Every time FTL allocates more memory, we explicitly log how much (out of how much) space is used in `/dev/shm`. This should help users to better identify out-of-memory situations. We have just seen such a thing on Discourse (link by Pralor below).
Before this PR, we printed log lines like
```
[2020-09-25 13:34:24.559 42121M] Creating shared memory with name "/FTL-queries" and size 262144
[...]
[2020-09-25 13:34:51.979 42121M] Resizing "/FTL-queries" from 262144 to 524288
```
These log lines now provide more information about the `/dev/shm` where they're living in:
```
[2020-09-25 13:37:38.779 42322M] Creating shared memory with name "FTL-queries" and size 262144 (/dev/shm: …
```
=> Log disk usage in /dev/shm

src/args.c, src/dnsmasq/dnsmasq.c
---
Add more verbose version output (`./pihole-FTL -vv`)
Exemplary output:
```
****************************** FTL **********************************
Version:         v5.2-169-g22b99929
****************************** dnsmasq ******************************
Version:         pi-hole-2.81
Compile options: IPv6 GNU-getopt no-DBus no-UBus no-i18n IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify dumpfile
****************************** SQLite3 ******************************
Version:         3.31.1
Compile options: COMPILER=gcc-7.5.0 DEFAULT_FOREIGN_KEYS OMIT_DEPRECATED OMIT_LOAD_EXTENSION OMIT_MEMORYDB OMIT_PROGRESS_CALLBACK THREADSAFE=1
```
=> Add more verbose version output (./pihole-FTL -vv)

src/shmem.c
---
Use `fallocate()` instead of `ftruncate()` when resizing and/or creating shared memory objects.
This ensures we reserve the requested memory exclusively for ourselves. With `ftruncate` we only announce we want the memory, however, other processes can still take the memory when the `/dev/shm` is close to being full.
This has the effect that this PR ensures that FTL does not crash when `/dev/shm` is getting full.
In addition, even when the shared memory arena is full, there will be a better error message, like
```
[2020-10-01 00:18:42.812 13052M] Creating shared memory with name "FTL-lock" and size 48 (/dev/shm: 2.0GB used, 2.0GB total)
[2020-10-01 00:18:42.812 13052M] WARNING: …
```
=> Allocate shared memory instead of only reserving it

.circleci/config.yml, test/arch_test.sh
---
Add additional
- ARMv4 (`armv4t`, 3-stage pipeline, Thumb, ARMv4 first to drop legacy ARM 26-bit addressing),
- ARMv5 (`armv5te`, Thumb, enhanced DSP instructions, caches), and
- ARMv8 (`armv8-a`, fundamental change to the ARM architecture with mandatory vector floating point and SIMD (Neon)) 
workflows.
- ARMv6 (with hard-float, for Raspberry Pi Model 1 and Zero), and
- ARMv7 (with hard-float, for Raspberry Pi Model 2)
already exist and have just been renamed to clarify the supported architecture.
=> Add pre-compiled ARMv4, ARMv5 and ARMv8 binaries to CI workflow

src/dhcp-discover.c, src/log.c, src/log.h, src/main.c, src/timers.c, src/timers.h
---
Make timer output at termination of FTL human readable (days/hours/minutes/seconds).
Exemplary line ***before*** this change:
```
########## FTL terminated after 5.088878e+05 s! ##########
```
Exemplary line ***after*** this change:
```
########## FTL terminated after 5d 21h 41m 27s ! ##########
```
=> Make timer output at termination of FTL human readable

src/database/common.c
---
Mark database as being available when creating a new database to avoid FTL skipping adding the tables thinking the database connection isn't ready. This fixes a bug in `development` preventing FTL to create new databases from scratch.
=> Mark database as being available when creating a new database

src/dnsmasq/forward.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h, src/enums.h, src/gc.c
---
Add new status `RETRIED` (12) to be used for queries which were retried. If a query was retried five times until we received a reply form upstream, queries 1-4 will be marked as `RETRIED` and only query 5 will stay in status `FORWARDED`. This does not affect the statistics because all five queries where send upstream, so five upstream packages are counted, even when only one query stays in status `FORWARDED`.
**edit** Add another new status `RETRIED_DNSSEC` (13) to be used for queries for which which automatic DNSSEC queries were retried. If we've already got an answer to a query, but we're awaiting keys for validation, there's no point retrying the query, so we're retrying the …
=> Add new query retried status

src/dnsmasq/dnsmasq.c, src/dnsmasq_interface.c, src/edns0.c, test/test_suite.bats
---
We should not rewrite the client's address if the announced address is a loopback address. See [this Discourse post](https://discourse.pi-hole.net/t/support-for-add-subnet-option-from-dnsmasq-ecs-edns0-client-subnet/35940/89) for further details of what might happen.
=> ECS: Ignore distant loopback address

.circleci/config.yml
---
Occassionally, we see that the transfer of the binaries fails for our binary bucket. This can seldomly cause issues for exotic architectures on custom branches. We add an additional step in the CI tool chain that downloads the just uploaded binary + checksum to verify that everything worked well during transmission.
=> Verify CI-generated binaries after uploading

src/dnsmasq_interface.c
---
Log information about the user FTL is running as and whether we're dropping to another user (such as `nobody`/`nogroup`). This should aid debugging issues like #920 in the future. Virtually all users will see
```
[2020-11-12 22:20:18.216 25044M] INFO: FTL is running as user pihole (UID 999)
```
`docker` users will see something like
```
[2020-11-12 22:20:18.216 25044M] INFO: FTL is running as root
```
Last but not least, users with a more complex configuration might see something like
```
[2020-11-12 22:20:18.216 25044M] INFO:FTL is going to drop from root to user nobody (UID xyz)
```
Note that the latter case isn't standard as we always explicitly advise against starting FTL as …
=> Log process owner details.

src/FTL.h, src/api/api.c, src/database/query-table.c, src/datastructure.c, src/datastructure.h, src/dnsmasq/forward.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h
---
So far, FTL keeps servers apart solely based on their IP addresses. This is typically sufficient, however, users may decide to run different DNS servers on the same IP address. A popular example is, for instance, running FTL on `127.0.0.1#53` and `unbound` on `127.0.0.1#5353` where `#` is the `dnsmasq`-style port separator.
This PR extends the logic in FTL to identify upstream servers by both, address, and port. This also changes the format we store the server in the database. So far, the servers were saved without a port, in the future, they are stored like `127.0.0.1#53`.
There is one expected cosmetic issue: FTL cannot know the port of the server responsible for queries in …
=> Differentiate upstream servers by address AND port

src/api/api.c, src/resolve.c
---
Keep upper case characters in host names because they may make them more readable (like `FritzBox`, `WDMyCloud`, or `VacuumRobot`). Inspired by https://github.com/pi-hole/FTL/issues/924
We make the corresponding API filters case-insensitive to preserve the current behavior (where everything was converted to lowercase) and as capitalization does not play a role in domain names.
=> Keep upper case characters in host names

src/database/common.c, src/database/message-table.c, src/database/message-table.h, src/dnsmasq/log.c, src/log.c, src/log.h
---
Fatal errors during the start-up of the `dnsmasq` core lead to a complete failure of the DNS resolver + a message is logged to `/var/log/pihole.log`. This PR also logs the message to `pihole-FTL.log` and the `message` table from where the Pi-hole diagnosis system will pick it up:
=> Log dnsmasq config errors to pihole-FTL.log

src/config.c, src/database/common.c, src/database/common.h, src/database/database-thread.c, src/log.c, src/main.c
---
With modern Pi-hole we cannot easily disable the database because it is used for a lot more than simple long-term query logging. Instead, it also contains the entire network table wisdom (and hence an essential source for how to identify clients in groups), messages about warnings and errors such as config errors or regex syntax issues, alias-client definitions and a lot more.
The recommended way to disable the database is setting `MAXDBDAYS=0`.
However, as the documentation mentions that `DBFILE=` is also possible, we handle this case by using the default path if we find an empty path but setting `MAXDBDAYS=0` internally in this case. This allows old configurations to work as …
=> Tweaks to disabling the FTL database

src/api/api.c, src/api/api.h, src/api/request.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h
---
As the title says: Adds a new API callback to remove DHCP leases without the need for a restart. This implements a Discourse feature request. See link for said request + the connected AdminLTE branch below.
=> Add API callback to remove DHCP leases without the need for a restart

src/api/api.c
---
Skip clients with no active counts (may be old IPv6 addresses). This should help reducing the workload for the dashboard (specifically the clients-over-time graph) for very active networks (speaking of 500+ clients). See linked Discourse post for further details.
=> Skip clients with no active counts at all (may be old IPv6 addresses)

src/dhcp-discover.c, src/dnsmasq/dhcp-common.c
---
By using the internal list of DHCP options supported by `dnsmasq`, our tool should be able to analyze all interesting DHCP options. This avoids that we'd need to implement more and more options as they are requested (this implements all of them at once). The output of the script changes slightly as we're now using the very same keywords `dnsmasq` would also use for the options.
Example:
```
Scanning all your interfaces for DHCP servers
Timeout: 10 seconds
* Received 300 bytes from enp2s0:192.168.2.10
Offered IP address: 192.168.2.217
Server IP address: 192.168.2.10
Relay-agent IP address: N/A
DHCP options:
Message type: DHCPOFFER (2)
server-identifier: 192.168.2.10
lease-time: …
```
=> Analyze all DHCP options dnsmasq is aware of

.circleci/config.yml, test/arch_test.sh
Fixes errors like
```
pihole-FTL: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by pihole-FTL)
```
This PR does two things:
1. Use `ftl-build:v1.8` containers (identical to `v1.7` *except* that they're all based on `stretch` instead of `buster`)
2. Update the binary tests to expect the older versions of `glibc`
=> Downgrade ftl-build containers to restore Debian stretch support

src/CMakeLists.txt, src/datastructure.h
**How familiar are you with the codebase?:** 1
---
GCC 10 defaults to -fno-common, which requires "extern" when defining global variables in headers.
=> Fix compatibility with GCC 10.

src/resolve.c
---
Always try to resolve hostnames when seeing a client/upstream server for the first time. Also when it wasn't recently active (may happen on re-import from database history).
=> Always try to resolve hostnames at least once

src/database/network-table.c
---
Use case-insensitive comparison of MAC address to ensure capitalization does not play a role. This fixes a bug reported on Discourse.
=> Use case-insensitive comparison for MAC addresses

src/config.c
---
We have to explicitly set `conflinebuffersize` to zero when freeing the buffer itself to avoid `getline()` crashing in some special edge-cases. Thanks @BlueSpaceCanary fir pointing this out!
```
man (3)  getline
If  *lineptr  is set to NULL and *n is set 0 before the call, then get‐
line() will allocate a buffer for storing the line.  This buffer should
be freed by the user program even if getline() failed.
```
=> Fix possible crash in parse_FTLconf()

src/dhcp-discover.c
---
Show content of the BOOTP server and file strings during `dhcp-discover`. They may contain TFTP details.
=> Show BOOTP server and file strings used by TFTP

src/args.c, src/lua/ftl_lua.c, src/lua/ftl_lua.h, test/test_suite.bats
---
- Show complete list of args when complaining about unsupported argument
- Allow `pihole-FTL` to be symlinked to `/usr/bin/lua` (or `/usr/bin/pihole-lua`) and work as drop-in replacement of a regular `lua` interpreter
- The same for `luac`
=> Add "lua" and "luac" drop-in support

src/regex.c
---
Fix freeing regex pointers to set the global not the local object to `NULL` after `free()`. Thanks  @BlueSpaceCanary for identifying this bug.
=> Fix freeing regex pointers to free the global objects

src/shmem.c
---
Fall back to using `ftruncate()` when `fallocate()` returns with `Operation not supported`. This may happen if the kernel is older than 2.6.23 or `glibc` older than 2.10. `ftruncate()` has its own disadvantages, however, it is POSIX compliant (POSIX.1-2001) so should be supported even by ancient kernels.
Fixes #977
=> Improve compatibility with old (ancient) kernels

src/overTime.c
There is a small typo in src/overTime.c.
Should read `timestamp` rather than `timestemp`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, timestemp -> timestamp

src/shmem.c
---
Reverts pi-hole/FTL#984 as discussed in https://github.com/pi-hole/FTL/issues/977#issuecomment-748586933. The reason for reverting this is that #969 (more specifically commit fd788585a1e3a51cc8c2834954a0d1f6e5ea6fe7) provides a much more elegant solution than the simple fallback we added in #984 that also solves the potential issues of the fallback (possible errors when running out of memory).
It has been confirmed working in https://github.com/pi-hole/FTL/issues/977#issuecomment-748593586
As a side-effect, it will resolve the merge conflict in #969 which can then be merged as well.
=> Revert #984

src/dnsmasq/forward.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h
---
So far, queries blocked during deep CNAME inspection where always short-circuited. This technical limitation led to an empty `NOERROR` reply for the user *ignoring* the configured blocking mode.
This PR improves on this by ensuring we create an artificial answer record with the reply type the user actually wants to see.
Fixes https://github.com/pi-hole/FTL/issues/990
=> Fix CNAME query blocking mode

src/regex.c
---
Do not sync after executing regular expression on a domain. We accidentally added a `sync()` call which should have been called only in debugging mode. This obviously could lead to issues when you're running on a system with a slow disk/storage attached to it. The branch above avoids calling sync. This fixes the new issues brought up in #962
=> Do not sync after executing regular expression on a domain

src/api/api.c, test/test_suite.bats
Signed-off-by: Fabian Preuß <preuss_fabian@gmx.de>
**How familiar are you with the codebase?:** 2
---
**What does this PR aim to fix?:**
When the Query Types chart tries to fetch the query types, it does not receive info about the "NS" type. This results in two issues:
1. The "NS" type is completely missing from the chart. Tooltips do not add up to 100%.
2. The legend of the Query Types chart on the dashboard allows you to filter the Query Log for a specific query type. This works fine for all types except "OTHER". Clicking on "OTHER" filters the Query Log for the type "NS". There is a mismatch between the query type id that the chart forwards to the Query Log and the one FTL will ultimately send back.
What FTL uses:
["A …
=> Added missing NS query type to getQueryTypes()

src/api/api.c, src/datastructure.c, src/dnsmasq_interface.c, src/enums.h, test/test_suite.bats
---
Add special handling for `SVCB` and `HTTPS` query types as specified by [this](https://datatracker.ietf.org/doc/draft-ietf-dnsop-svcb-https/) IETF draft, section 2. Usually, we would not add query types still in draft mode, however, this time a big player in the market (imagine a bitten into fruit) decided to push something not even yet standardized into the market. Hence, many users are seeing this new query type now. The move from this vendor makes it unlikely that the standard can be much different from the draft (without needing a lot of effort), however, we stay fully flexible with Pi-hole as we're only storing a numeric value in the database and can change its translation …
=> Add new query types SVCB and HTTPS

src/dnsmasq_interface.c
---
We cannot really decide whether local configuration lines are meant for blocking or something else. Just record such queries as replied to from cache because this is what they are. This code made sense at the time where wildcards were implemented as dnsmasq config lines, however, we've advanced to our own regex engine since then and all config lines should have also been auto-migrated.
This fixes a bug reported on Discourse (see below).
Assume I'm authoritative for `lan` (this is the case when the Pi-hole DHCP server is used) and run `dig whatever.lan`
Before:
Now:
=> Do not record NXDOMAIN from DNS cache as "regex blocked"

src/database/gravity-db.c, src/database/gravity-db.h, src/datastructure.c, src/datastructure.h, src/dnsmasq_interface.c, src/regex.c, src/regex_r.h
---
Detect and handle interface changes of clients with the same IP. If such a change happens, we reload the associated groups. This is a feature that has been requested on Discourse (see link below).
=> Detect and handle interface changes of clients with the same IP

src/api/api.c
---
Only return regex index when allowed by privacy settings. This may leak information, otherwise. Fixes https://github.com/pi-hole/AdminLTE/issues/1684
=> Do not return regex idx if privacy level > 0

src/dnsmasq/dnsmasq.c, src/dnsmasq_interface.c
---
Bug fix adding a missing check for the validity of a pointer that may be omitted in (very) rare cases. Fixes #1015
=> Check for validity if iface pointe before dereferencing it

src/api/api.c, src/database/query-table.c, src/datastructure.h, src/dnsmasq_interface.c, src/shmem.c
---
Implement support for displaying exact type instead of the catch-them-all category `OTHER`. The `OTHER` category is still used when it comes to computing statistics to ensure your chart's legend does not explode.
Example:
```
dig -t TYPE65 google.de
dig -t TYPE66 google.de
```
results in:
(note that type 65 is correctly translated into the named type `HTTPS` rather than showing `TYPE65`)
And the database contains the expected (`16` = `HTTPS` mapped status, `166` = `TYPE66` with offset 100)
``` sql
SELECT * FROM queries WHERE domain = 'google.de' ORDER BY id DESC LIMIT 2;
```
``` plain
id          timestamp   type        status      domain      client      forward …
```
=> Implement support for displaying exact type instead of just "OTHER"

src/syscalls/ftlallocate.c
---
We switched from `fallocate( to `posix_fallocate()` to enhance compatibility to very old kernels (see https://github.com/pi-hole/FTL/issues/977). Unfortunately, this had an unintended side-effect of not catching errors correctly as `errno` is not set by `posix_fallocate()` (in contrast to fallocte() who did set it). 
This PR fixes this by using the return value instead of `errno` which is what you should do with `posix_...` routines.
=> Fix for errno not being set by posix_fallocate()

src/CMakeLists.txt, src/FTL.h, src/api/api.c, src/config.h, src/database/aliasclients.c, src/database/gravity-db.c, src/database/gravity-db.h, src/database/network-table.c, src/database/query-table.c, src/datastructure.c, src/datastructure.h, src/dnsmasq/forward.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h, src/edns0.c, src/edns0.h, src/overTime.h, src/regex.c, src/regex_r.h, src/resolve.c, src/shmem.h, src/static_assert.h, src/vector.h
---
This PR fixes https://github.com/pi-hole/FTL/issues/1026 and https://github.com/pi-hole/FTL/issues/1027 by ensuring the first upstream destination is not a collector for all kinds of other queries. There was an ill assumption in the API code leading to a (much) too loose filtering.
Furthermore, I added a bitfield to the `queriesData` struct to allow further simplification of the API code easing future maintainability (the same code will go into v6.0 so this still matters). While at it, I added a mechanism to ensure the size of memory objects does not change without us noticing (the CI will fail).
The first commit optimized the internal datastructure FTL uses. By this, we were …
=> Fix for Query Log filtering and memory optimizations

src/config.c, src/database/database-thread.c
---
Add `MAXDBDAYS=-1` as an option to disable database auto-cleaning and ensure overflow cannot happen. In case of an overflow, we just enforce the maximum of `INT_MAX / 24 / 60 / 60 = 24855 days (roughly 68 years)`
Fixes https://github.com/pi-hole/FTL/issues/1021
=> Config option MAXDBDAYS fixes and tweaks

src/api/api.c
Signed-off-by: Fabian Preuß <preuss_fabian@gmx.de>
**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**
**How familiar are you with the codebase?:** 3
---
Fixes an issue reported on discourse: [https://discourse.pi-hole.net/t/domain-queries-include-wrong-results/43472](https://discourse.pi-hole.net/t/domain-queries-include-wrong-results/43472)
=> Don't display unrelated blocked CNAME queries when filtering for specific domain

src/database/query-table.c
---
Fixes incorrect "Found unknown status 14 in long term database" warning in the logs. We change the code to use a enum-based struct so we cannot forget to update this in the future when adding further query status types.
Fixes #1045
=> Fixes incorrect "Found unknown status 14 in long term database" warning

src/dhcp-discover.c, src/dnsmasq/option.c
---
Do not explicitly request a lease time in our DHCPREQUEST as this may lead to incorrect responses. Also, when sending a request to lo, we should send it to the interface address instead of the broadcast (lo doesn't support broadcast destinations).
=> Improvements for `dhcp-discover`

src/CMakeLists.txt, src/gc.c, src/log.c, src/log.h, src/main.c, src/procps.c, src/procps.h, src/shmem.c, test/test_suite.bats
---
Undo some shared memory code from the time when we wanted to be able to resume shared memory still in use by an external (Rust) component. FTL should always be the one and only shared memory holder.
This allows us to detect if shared memory objects are currently used and, if so, inferring that another FTL process is running. If this is the case, we stop start startup process early enough to not cause any trouble for the running FTL instance, preventing it from crashing.
In addition, we print some useful lines to the log that should aid self-helping:
```
[2021-02-05 11:45:56.691 18850M] ########## FTL started! ##########
[2021-02-05 11:45:56.691 18850M] FTL branch: …
```
=> Prevent crashing when FTL is started multiple times

src/database/query-table.c, src/datastructure.c, src/datastructure.h, src/dnsmasq_interface.c
---
Fix queries sent upstream being counted incorrectly when modified later on (blocked externally, blocked during CNAME inspection). This also applies to queries loaded from the database.
=> Fix inconsistent counters on CNAME or exernally blocked queries

src/config.c, src/config.h, src/database/query-table.c, src/datastructure.h, src/dnsmasq_interface.c, src/gc.c
---
Add per-client rate-limiting. Rate-limited queries are answered with a `REFUSED` reply and not further processed by FTL Even when they are logged in `pihole.log`, they will not contribute to the overall statistics nor enter the Query Log or the database.
This serves the purpose of a real rate-limit and ensures that abnormally behaving clients hammering FTL with thousands of queries per second cannot lead to a denial-of-service failure.
Rate-limiting is very customizable, it defaults to allowing not more than 1000 queries in 60 seconds. Both numbers can be changed by the user.
It is important to note that rate-limiting is happening on a *per-client* basis. Other clients can …
=> Add per-client rate-limiting

src/api/socket.c, src/args.c, src/daemon.c, src/daemon.h, src/database/database-thread.c, src/database/message-table.c, src/database/query-table.c, src/database/query-table.h, src/dnsmasq/dnsmasq.c, src/dnsmasq_interface.c, src/gc.c, src/log.c, src/main.c, src/procps.c, src/procps.h, src/resolve.c, src/shmem.c, src/shmem.h, src/signals.c, src/syscalls/vsnprintf.c, test/test_suite.bats
---
Fix a few issues revealed when checking why `pihole-FTL test` doesn't work as expected:
1. The `test` option is currently broken: It immediately terminates all FTL components (threads surrounding the resolver, etc.), however, it did not terminate the resolver itself leading to an attempt to `kill` the resolver in the docker container.
1. The log file lock should be shared among processes to ensure we cannot outpace forks (which may result in a log deadlock). This may fix #906 as byproduct of our improvements in here
2. We should not detach threads we want to cancel explicitly later on when terminating
3. Ensure we clean up behind us on crashes and fatal errors (such as port 53 …
=> Fix for `pihole-FTL test`

src/database/query-table.c, src/dnsmasq_interface.c, src/shmem.c
---
Retried queries due to missing DNSSEC validation have no upstream server (the related DNSSEC queries where retried, not this one). Hence, we shouldn't update the counts of any upstream here. This silences an incorrect "FATAL: Trying to access upstream ID -1" warning in the logs.
This issue has been reported on Discourse (see link below).
=> Fix incorrect "FATAL: Trying to access upstream ID -1" warning in the logs

src/dhcp-discover.c, src/log.c, src/log.h
---
Sanitize string returned by DHCP servers in `dhcp-discover` to reveal if they contain binary garbage like control characters (where they shouldn't).
**edit** Also implement DHCPv4 PCP Option (RFC 7291)
=> Escape DHCP options if necessary

src/database/query-table.c, src/datastructure.c, src/dnsmasq_interface.c, src/files.c, src/log.c, src/shmem.c, src/shmem.h
---
Instead of enlarging the shared memory objects whenever we need to do so, we enlarge them only in one central spot - that is the time of successful memory locking. This is not really a functional change, however, it makes the code more read- and understandable. Discussions in the past have shown that the current way of handling it isn't at all easy to understand. Also, this reduces the surface for possible mistakes in the future.
=> Resize shared memory only when locking

.gitignore, .vscode/settings.json, src/database/shell.c, src/database/sqlite3.h
---
This PR updates the embedded SQLite engine to v3.35.0 released today. [CHANGELOG](https://www.sqlite.org/releaselog/3_35_0.html)
Highlights for us:
- Math functions (disabled by default as we don't need them right now)
- Added support for [`ALTER TABLE DROP COLUMN`](https://www.sqlite.org/lang_altertable.html#altertabdropcol)
- Improvements for [`UPSET`](https://www.sqlite.org/lang_upsert.html)
`UPSERT` is a clause added to `INSERT` that causes the `INSERT` to behave as an `UPDATE` or a no-op if the `INSERT` would violate a uniqueness constraint.
- Add support for the [`RETURNING`](https://www.sqlite.org/lang_returning.html) clause on `DELETE`, `INSERT`, and `UPDATE` statements. …
=> Update SQLite from 3.34.0 to 3.35.0

src/dhcp-discover.c
1
---
The `format_time` function expects buffer of length 42, but it was called with a buffer of size 32.
https://github.com/pi-hole/FTL/blob/2999e2b57c62b4455187ee9b77840d49df0a8e2e/src/log.h#L21
https://github.com/pi-hole/FTL/blob/2999e2b57c62b4455187ee9b77840d49df0a8e2e/src/dhcp-discover.c#L305-L306
=> Use properly-sized buffer for format_time()

src/args.c, test/test_suite.bats
---
If the first argument ends in `*.lua`, we immediately start the embedded LUA engine.
Same for "`*.db` files which are directly routed into the embedded SQLite3 engine.
=> Simplify handling of `.lua` and `.db` files

src/database/shell.c, src/database/sqlite3.h
---
Bugfix release for SQLite3:
- Enhance the OP_OpenDup opcode of the bytecode engine so that it works even if the cursor being duplicated itself came from OP_OpenDup. This problem only came to light due to the recent MATERIALIZED hint enhancement.
- When materializing correlated common table expressions, do so separately for each use case, as that is required for correctness. This fixes a problem that was introduced by the MATERIALIZED hint enhancement.
- Fix a problem in the filename normalizer of the unix VFS.
- Fix the "box" output mode in the CLI so that it works with statements that returns one or more rows of zero columns (such as PRAGMA incremental_vacuum).
- Improvements …
=> Update SQLite to 3.35.3

.circleci/config.yml
Signed-off-by: Anton Bershanskiy <45960703+bershanskiy@users.noreply.github.com>
1
---
When external contributor (like me) forks FTL and enables Circle CI on it, Circle CI tries to upload artifacts to Pi-Hole's FTP server. Of course, upload fails and fails the whole workflow and skips actual test.
Example run before this change: …
=> Circle CI: skip uploading build artifacts on forks

src/database/sqlite3.h
---
Yet another bugfix release for 3.35.
CHANGELOG:
- Fix a defect in the query planner optimization:
- Attempt to process `EXISTS` operators in the `WHERE` clause as if they were `IN` operators, in cases where this is a valid transformation and seems likely to improve performance. 
- Fix a defect in the new `RETURNING` syntax.
- Fix the new `RETURNING` feature so that it raises an error if one of the terms in the `RETURNING` clause references a unknown table, instead of silently ignoring that error.
- Fix an assertion associated with aggregate function processing that was incorrectly triggered by the push-down optimization.
=> Update SQLite3 to 3.35.4

.vscode/settings.json, src/config.h, src/database/message-table.c, src/database/network-table.c, src/regex.c, src/signals.c
---
This PR fixes #1050 by ensuring we add all warnings also to the `message` table (so they can be shown on the dashboard). It also fixes incorrect regex links in the message display and adds a bit more error reporting to the network table.
=> Add more regex warnings to message table

src/config.c, src/config.h, src/dnsmasq/dnsmasq.c, src/dnsmasq/forward.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h
---
Until now, FTL's [Full IP](https://docs.pi-hole.net/ftldns/blockingmode/#pi-holes-full-ip-blocking) and [IP (IPv6 NODATA)](https://docs.pi-hole.net/ftldns/blockingmode/#pi-holes-ip-ipv6-nodata-blocking) blocking modes sourced the IP to deliver on a blocked domain from the `setupVars.conf` values `IPV4_ADDRESS` and `IPV6_ADDRESS`. This is, however, quite a limitation, especially if the device running Pi-hole has more than one interface.
This PR implements an automated IP blocking. Instead of reading the two addresses  from `setupVars.conf`, we now determine the address of the interface a query arrived on. We then use this IP address in the blocked reply. This does not only reduce …
=> Automate IP blocking mode

src/config.c, src/log.c, src/syscalls/fopen.c
---
The uninterruptible syscalls could have entered an infinite loop when logging that they can neither open nor create (due to missing permissions) the non-existing log file. Such a loop is now prevented.
=> Fix possible infinite loop when Pi-hole ecosystem is not present

src/gc.c
---
This fixes https://github.com/pi-hole/FTL/issues/1095 by using the configured limit rather than the hard-coded `MAXLOGAGE` (24 hours).
=> Use MAXLOGAGE to control which queries get deleted by GC

src/database/common.c, src/database/query-table.c, src/database/query-table.h, test/test_suite.bats
---
Fix database update to version 7 reporting error when there is none:
``` plain
Column additional_info not initialized, database not available
```
This is not a critical bug as the issue resolves itself on the next start of FTL.
=> Fix database update to version 7 reporting error

src/CMakeLists.txt, src/database/common.c
---
Enable compile-time flag `SQLITE_ENABLE_DBPAGE_VTAB` to add support for `.recover` shell option:
```
sqlite> .help recover
.recover                 Recover as much data as possible from corrupt db.
--freelist-corrupt       Assume the freelist is corrupt
--recovery-db NAME       Store recovery metadata in database file NAME
--lost-and-found TABLE   Alternative name for the lost-and-found table
--no-rowids              Do not attempt to recover rowid values
that are not also INTEGER PRIMARY KEYs
```
Exemplary use:
```
pihole-FTL /etc/pihole/pihole-FTL.db ".recover" | pihole-FTL ~/pihole-FTL_recovered.db
```
=> Enable `.recover` option for embedded sqlite3 shell

src/config.c, src/overTime.c
---
Improve warning message when importing queries from the future (a typical problem of systems starting at 1970-01-01 on every boot). Also, show the warning only once instead of flooding the log file.
=> Improve warning messages for defect hwclocks

src/dnsmasq/dnsmasq.c, src/dnsmasq/network.c
---
Fix crash when `bind-address` option is used. Original issue reported in https://github.com/pi-hole/docker-pi-hole/issues/855
=> Fix crash when bind-address is used

src/daemon.c, src/database/aliasclients.c, src/database/common.c, src/database/gravity-db.c, src/database/network-table.c, src/database/query-table.c, src/dnsmasq_interface.c, src/main.c, src/shmem.c, src/shmem.h, src/signals.c, src/signals.h
---
Lock when terminating forks to ensure we remap shared memory if heavy TCP activity causes shared memory objects to resize often.
=> Improve locking during heavy TCP forking

src/database/common.c, src/database/common.h, src/database/gravity-db.c, src/database/message-table.c, src/database/network-table.c, src/log.c, src/log.h, src/overTime.c, src/shmem.c, src/syscalls/accept.c, src/syscalls/sendto.c
Change the logging mode to the new style
=> New logging style

src/CMakeLists.txt, src/database/shell.c, src/database/sqlite3.h
---
SQLite Release 3.36.0 On 2021-06-18
1.  Improvement to the [EXPLAIN QUERY PLAN](https://sqlite.org/eqp.html) output to make it easier to understand.
2.  Byte-order marks at the start of a token are skipped as if they were whitespace.
3.  An error is raised on any attempt to access the [rowid](https://sqlite.org/lang_createtable.html#rowid) of a VIEW or subquery. Formerly, the rowid of a VIEW would be indeterminate and often would be NULL. The -DSQLITE_ALLOW_ROWID_IN_VIEW compile-time option is available to restore the legacy behavior for applications that need it.
4.  The [sqlite3_deserialize()](https://sqlite.org/c3ref/deserialize.html) and …
=> Update SQLite engine to 3.36.0

src/api/socket.c, src/daemon.c, src/daemon.h
---
Cancel still running API threads at shutdown. This avoids a possible crash when a long-running API task is still running when FTL closes database connections on shut down.
=> Fix possible crash during shutdown

src/config.c, src/config.h, src/dnsmasq_interface.c, src/enums.h
---
Ensure FTL always replies with `NXDOMAIN` to `A` and `AAAA` queries of `use-application-dns.net`
This is following the recommendation on https://support.mozilla.org/en-US/kb/configuring-networks-disable-dns-over-https
Enforcing `NXDOMAIN` for `use-application-dns.net` can be disabled by setting `MOZILLA_CANARY=false` in `/etc/pihole/pihole-FTL.conf`
The Query Log will display this as reply answered from cache:
We could also introduce a new "special domain" status, but I don't see this necessary for now (and it'd require another change to the AdminLTE repo as well).
=> Implement special handling of the Mozilla canary domain to disable Firefox automatic DoH

src/database/message-table.c, src/database/message-table.h, src/dnsmasq_interface.c, src/enums.h
---
Add hint to Pi-hole diagnosis system when clients are rate-limited. This should make it easier to debug cases of clients going haywire.
=> Log rate-limiting of clients to the message table

src/config.c, src/config.h, src/database/gravity-db.c, src/database/gravity-db.h, src/database/query-table.c, src/datastructure.c, src/dnsmasq/forward.c, src/dnsmasq_interface.c, src/enums.h, src/gc.c, src/shmem.h
---
When the gravity database is locked/busy, Pi-hole allows all queries because it has no way of detecting if they should be blocked or not. However, for very large lists and/or on very busy networks and/or on very (!) slow devices, this may open a windows of up to several seconds where undesired queries may get through, ads and unwanted telemetry could be the result.
This PR adds a config option (`REPLY_WHEN_BUSY`) to customize what happens to queries while the database is locked:
1. `ALLOW` - as before, just allow all queries when the database is busy
2. `BLOCK` - block all queries when the database is busy. This uses the configured `BLOCKINGMODE` (default `NULL`)
3. `REFUSE` - …
=> Customizable locking while database is busy

src/database/database-thread.c, src/database/query-table.c
---
This PR consists of two changes. It fixes #1157.
- Only open database when really necessary. This may reduce disk activity slightly and save a bit of CPU time.
- Update database counters still within the running `TRANSACTION` to reduce I/O
=> Reduce disk I/O in database thread

src/dnsmasq_interface.c
---
https://github.com/pi-hole/FTL/pull/1111 has added special handling for `pi.hole` and `<hostname>`. However, we forgot about the case when Pi-hole is the DHCP server and we know the local domain. In this case, we should use the automated reply forming - to serve the most appropriate IP address - also for `pi.hole.<local_domain>` and `<hostname>.<local_domain>`.
This PR adds these two new rules and hereby fixes #1168.
=> Add handling for "pi.hole.<local_domain>" and "<hostname>.<local_domain>"

src/api/api.c, src/api/socket.c, src/capabilities.c, src/daemon.c, src/database/common.c, src/database/gravity-db.c, src/database/network-table.c, src/database/query-table.c, src/datastructure.c, src/dhcp-discover.c, src/dnsmasq_interface.c, src/edns0.c, src/files.c, src/gc.c, src/log.c, src/log.h, src/regex.c, src/resolve.c, src/shmem.c, src/shmem.h, src/signals.c
---
This PR fixes several one-time memory leaks that might appear in failure cases of the database or memory allocation issues in several other places. None of them should be severe, however, we should obviously not leak memory in the first place. Furthermore, we check for the return value of a lot of routines that should not (but could) fail and enforce upper bounds for some DHCP options (relevant for `dhcp-discover`).
=> Improvements based on static-analysis of source code

src/dnsmasq/dnsmasq.c, src/dnsmasq/forward.c, src/dnsmasq/network.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h
---
This PR ensures we're recognizing virtual interfaces (e.g., `eth0:0`) as distinct interfaces even when the kernel does not treat the as interfaces with their own interface index. This is necessary to pick the correct local address when determining which address is the right one for replying to `A` and `AAAA` queries to `pi.hole` and `<hostname>`.
In addition, we fix a small glitch if the interface we received a query on doesn't have the requested address type (e.g. virtual interfaces only configured with one IPv6 but no IPv6 address). Instead of replying with `0.0.0.0` resp. `::`, we reply with `NODATA` which seems more menaingful.
=> Fix virtual interface address determination

src/config.c, src/config.h, src/dnsmasq_interface.c
---
So far, we used `local-ttl=2` hard-coded in dnsmasq's config because this ensured clients won't cache blocked queries for longer times, possibly rendering whitelisting ineffective.
This PR implements a **new TTL for blocked queries only**. This allows users to set `local-ttl` to any value they prefer without this being overwritten in `01-pihole.conf` after each update. This seems useful in context of locally used hostnames that are known to stay constant over long times (e.g., printers, etc.).
The new value defaults to `2` seconds (no change in behavior) and can be controlled using the new FTL config option `BLOCK_TTL=2`
=> Handle TTL for blocked queries seperately 

src/database/common.c, test/test_suite.bats
1
---
Sets the file permission of the `pihole-FTL.db` to `664` to allow write permission to the `pihole` group. This is necessary for https://github.com/pi-hole/AdminLTE/pull/1886 as it allows the web interface write permission to delete items from the `message` table
=> Change FTL database permission to 664

src/config.c, src/config.h, src/dnsmasq_interface.c
---
Implement special handling of Apple iCloud Private Relay domains to prevent Applie devices from bypassing Pi-hole.
> Some enterprise or school networks might be required to audit all network traffic by policy, and your network can block access to Private Relay in these cases. The user will be alerted that they need to either disable Private Relay for your network or choose another network.
>
> The fastest and most reliable way to alert users is to **return a negative answer from your network’s DNS resolver, preventing DNS resolution for the following hostnames used by Private Relay traffic**. Avoid causing DNS resolution timeouts or silently dropping IP packets sent to the …
=> Add special handling of iCloud Private Relay domains

.github/workflows/build.yml
Ready GHA to take over from circle.
This still leaves circle in place to build and push branch builds to ftl.pi-hole.net
However, this will automatically attach binaries built by GHA to the release when we release. I have tested this over on my own fork.  If, for whatever reason, the binaries that GHA builds are duff, we can easily replace them with the ones circle builds.
=> Github Actions

src/dnsmasq/cache.c, src/dnsmasq/dnsmasq.h, src/dnsmasq_interface.c
---
This PR adds further cache metrics that can be queried via the API (http://pi.hole/admin/api.php?getCacheInfo). No changes are necessary on the web front end. We add a breakdown of the current cache content for inspection:
This has been inspired by the linked Discourse discussion.
=> Add further cache metrics

src/dnsmasq/rfc1035.c, test/test_suite.bats
---
This PR fixes deep CNAME inspection. It was broken recently in a `dnsmasq` commit (https://github.com/pi-hole/FTL/commit/09051c65ac55eb26e0ad413722d298f5e1d9ed45),
> This commit also fixes a long-standing bug in caching of CNAME chains leading to a PTR record.
when CNAME handling was redesigned. We also add a proper test of a "deep" CNAME to ensure this won't happen again in the future.
=> Fix deep CNAME inspection

src/resolve.c
---
This PR fixes #1195 by ensuring local queries are sent to `127.0.0.1` instead of `1.0.0.127`. The issue comes from the networking constant `INADDR_LOOPBACK` being in host byte order whereas `struct in_addr` expects an address in network byte order so we need to convert the static constant. This was not mentioned in [`man 7 ip`](https://man7.org/linux/man-pages/man7/ip.7.html), however, once we've seen the symptoms, it became clear that this is what is meant with
```
/* Internet address */
struct in_addr {
uint32_t       s_addr;     /* address in network byte order */
};
```
There is no extra information attached to the constant itself that it'd be converted:
```
There are …
```
=> Fix network byte order confusion in local lookups

.github/workflows/build.yml
---
Prevents an issue with `pihole -v -f` hitting a condition where it includes additional output. In Circle, tagged releases have `GIT_BRANCH` set to `master`, so this is just replicating that
=> Only set GIT_BRANCH to the branch name if GIT_TAG is empty

src/database/message-table.c, src/database/message-table.h, src/datastructure.h, src/dnsmasq_interface.c, src/gc.c, src/gc.h
---
This PR tweaks rate-limiting by ensuring clients are not unblocked after the configured interval if they are continuously querying and, hence, deserve continued blocking.
Interesting side-effect: I forgot about this change, sorry. If we'd have it in the current release, #1197 would not have even happened (it is fixed herein as well, even if differently). Nonetheless, it still makes sense to also merge #1197
=> Tweak rate-limiting

src/dnsmasq/dnsmasq.c, src/dnsmasq/forward.c, src/dnsmasq_interface.c, src/dnsmasq_interface.h
---
Fixes https://github.com/pi-hole/FTL/issues/1191 by extending interface analysis to also support configurations defining `bind-interface`. So far, we have only seen users having this config line enabled unintentionally (auxiliary `ubuntu-fan` or `lxd` config files placed by the system into `/etc/dnsmasq.d`), however, this does not mean we should not support it. A second goal of the PR is to largely extend the `DEBUG_NETWORKING` toolset to ease debugging in complex network environments.
The bug fix as been confirmed working.
=> Improve interface detection

src/CMakeLists.txt
Current FTL won't build at all if static libraries are not available.
But dynamic libraries might be usable. Be able to use dynamic libraries
if static are not ready.
Signed-off-by: Petr Menšík <pemensik@redhat.com>
**How familiar are you with the codebase?:** 3
---
Current FTL won't build at all if static libraries are not available.
But dynamic libraries might be usable. Be able to use dynamic libraries
if static are not ready. …
=> Support dynamic linking as fallback

src/config.c, src/dnsmasq_interface.c, src/enums.h, src/resolve.c, test/hostnames.sh, test/test_suite.bats
---
This PR adds the new `PIHOLE_PTR=HOSTNAMEFQDN` option that replies to local interface address PTR lookups with `<hostname>.<local domain>` if set. We already have `PIHOLE_PTR=HOSTNAME` responding with `<hostname>` alone. Looking up names in `/etc/hosts` is removed from the internal resolver as this makes lookups somewhat opaque. Everything should be done with proper (internal) PTR lookups.
We furthermore add CI testing for the automatic replying with `pi.hole` for all local interface addresses with exceptions for the loopback addresses.
=> Add `PIHOLE_PTR=HOSTNAMEFQDN` option

src/dnsmasq_interface.c
---
Analyze and store which upstream sent us an error report (e.g. `SERVFAIL` on `DNSSEC BOGUS` or `REFUSED` on rate-limiting)
=> Analyze error report origins

src/database/message-table.c, src/database/message-table.h, src/datastructure.c, src/dnsmasq/log.c, src/enums.h, src/log.c, src/log.h, src/main.c
---
Add DNSMASQ_WARN message type whenever dnsmasq logs a warning. Also do not flush the message table on reload (but only on restart) so that config-related (i.e. one-time) warnings are not accidentally deleted.
=> Add dnsmasq warnings to message table

src/daemon.c, src/database/aliasclients.c, src/database/common.c, src/database/message-table.c, src/database/network-table.c, src/database/query-table.c
---
Reduce code duplication by using labels + ensure we do not run `dbclose()` multiple times on database issues (e.g., when database is locked). The double-closing can cause some warnings in the FTL log even when this is harmless, for instance,
```
[2021-11-13 09:52:03.250 875/T879] ERROR: SQL query "END TRANSACTION" failed: database is locked
[2021-11-13 09:52:03.251 875/T879] WARNING: Storing devices in network table failed: database is locked
[2021-11-13 09:52:03.251 875/T879] SQLite3 message: API call with invalid database connection pointer (21)
[2021-11-13 09:52:03.251 875/T879] SQLite3 message: misuse at line 166280 of [5c9a6c0687] (21)
[2021-11-13 09:52:03.251 875/T879] …
```
=> Ensure dbclose() is not called multiple times

src/dnsmasq_interface.c
---
Add support for conditional domain suffices in `HOSTNAMEFQDN` mode. Fixes https://github.com/pi-hole/FTL/issues/1247
=> Add support for conditional domain suffices in HOSTNAMEFQDN mode

src/database/shell.c, src/database/sqlite3.h
---
Changelog:
1.  [STRICT tables](https://www.sqlite.org/stricttables.html) provide a prescriptive style of data type management, for developers who prefer that kind of thing.
2.  When adding columns that contain a [CHECK constraint](https://www.sqlite.org/lang_createtable.html#ckconst) or a [generated column](https://www.sqlite.org/gencol.html) containing a [NOT NULL constraint](https://www.sqlite.org/lang_createtable.html#notnullconst), the [ALTER TABLE ADD COLUMN](https://www.sqlite.org/lang_altertable.html#altertabaddcol) now checks new constraints against preexisting rows in the database and will only proceed if no constraints are violated.
3.  Added the [PRAGMA …
=> Update SQLite engine from 3.36.0 to 3.37.0

CMakeLists.txt, src/dnsmasq/cache.c, src/dnsmasq/dnsmasq.c, src/dnsmasq/dnsmasq.h, src/dnsmasq/domain-match.c, src/dnsmasq/edns0.c, src/dnsmasq/forward.c, src/dnsmasq/option.c, src/dnsmasq/rrfilter.c, src/dnsmasq/util.c
---
This mainly adds bugfixes for issues reported against the current embedded version of `dnsmasq`. The first two bug fixes are important for us as we have seen them being reported on our own platforms.
- 2924c29 fixes query status being reported incorrectly for retired domains and some special edge-cases (see comment message)
- ea689a2 fixes case-insensitive domain matching, see https://github.com/pi-hole/FTL/issues/1254 (fix has been confirmed therein)
- 89a8864 fixes a regression in `rebind-domain-ok` option recently introduced by `dnsmasq` v2.86
- 5129c7e fixes locally generated answers returning an incorrect answer count when the packet gets too large and UDP truncation …
=> Update embedded dnsmasq to v2.87test4-6

src/dnsmasq/dnsmasq.c
---
The recent `dnsmasq` update included a commit (https://github.com/pi-hole/FTL/commit/95473e7696bd9408a413c0a17123dfc21321edab) that forced the entire `pihole-FTL` process to adhere to the system-wide defined locale. In the majority of non-English locales (German, French, Italian, and Spanish, ...), a comma is used as decimal separator instead of a dot.
This caused troubles in the PHP API scripts that are not aware of the system-wide locale as the comma is not interpreted as decimal separator leading to malfunctions of the statistics on the dashboard.
This PR fixes this by ensuring that the the numeric part of the locale, responsible for things such as decimal separators, is set …
=> Fix locale issue in Telnet API

src/args.c
---
A small Christmas present :christmas_tree:: `pihole-FTL sqlite3 -h ...`
Normal table printing:
``` plain
$ pihole-FTL sqlite3 /etc/pihole/pihole-FTL.db "SELECT * FROM network_addresses LIMIT 2"
19|169.254.48.28|1610737320||
20|169.254.157.55|1610737320||
```
New human-readable output (added `-h`):
``` plain
$ pihole-FTL sqlite3 -h /etc/pihole/pihole-FTL.db "SELECT * FROM network_addresses LIMIT 2"
network_id  ip              lastSeen    name    nameUpdated
----------  --------------  ----------  ------  -----------
19          169.254.48.28   1610737320  (null)  (null)     
20          169.254.157.55  1610737320  (null)  (null)
```
This also works in interactive mode:
``` plain …
```
=> Add human-readable table output mode

src/api/api.c, src/api/api.h, src/api/request.c, test/test_suite.bats
---
See title.
Example:
```
$ echo ">dns-port >quit" | nc 127.0.0.1 4711
53
```
Meant to be useful for https://github.com/pi-hole/pi-hole/pull/4485. Can be closed without merging when not used there. Note that the port can also be `0` is someone decides to disable the DNS server part of Pi-hole (possible even when not useful).
=> Return DNS port on ">dns-port" telnet command

src/capabilities.c, src/main.c
Do not warn about missing capabilities during startup. The embedded `dnsmasq` does the same but in a better (config-aware) way, i.e. it will not complain about missing `CAP_NET_ADMIN` when DHCP is not enabled. As its warnings are now much more present in all logs, we don't need to do the check twice.
Further/related changes:
- The existing checks remain there but are only used in debug mode (`DEBUG_CAPS`)
- Check for both `E` and `P` flag as we need both for TCP workers
- Remove check for `CAP_IPC_LOCK` as we are not using `mlock()`
=> Improve Linux capabilities check

src/database/shell.c, src/database/sqlite3.h
- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [] I have considered, and confirmed that this submission will be valuable to others.
- [] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [] I give this submission freely, and claim no ownership to its content.
**How familiar are you …
=> Update SQLite to v3.37.1

src/database/sqlite3.h
---
**CHANGELOG**
1.  Fix [a bug](https://sqlite.org/forum/forumpost/b03d86f9516cb3a2) introduced in [version 3.35.0](../releaselog/3_35_0.html) (2021-03-12) that [can cause database corruption](https://sqlite.org/howtocorrupt.html#svptbug) if a [SAVEPOINT](https://sqlite.org/lang_savepoint.html) is rolled back while in [PRAGMA temp_store=MEMORY](https://sqlite.org/pragma.html#pragma_temp_store) mode, and other changes are made, and then the outer transaction commits. [Check-in 73c2b50211d3ae26](https://sqlite.org/src/info/73c2b50211d3ae26)
2.  Fix a long-standing problem with `ON DELETE CASCADE` and `ON UPDATE CASCADE` in which a cache of the …
=> Update Sqlite3 engine to 3.37.2

src/CMakeLists.txt
---
See title. Everything was already configured correctly, we just needed to enable the feature. For the sake of simplicity, we use the history of `sqlite3` so you can immediately use `pihole-FTL sql` with your recent history. Auto-completion is available though <kbd>Tab</kbd>, as usual.
=> Enable history and auto-completion for embedded SQLite3 engine

test/gravity.db.sql, test/pdns/setup.sh, test/run.sh, test/test_suite.bats
---
Use FTLs embedded SQLite3 engine for the tests instead of relying whatever the system may be providing. This exclusively affects tests. Nothing is changed in FTL itself.
=> Use embedded SQLite3 engine for the tests

src/api/api.c, test/test_suite.bats
---
There are queries which are neither sent upstream nor are they cached or blocked. These are incorrectly ignored in the upstream server pie chart leading to a mismatch of the blocked percentage compared to the value reported at the top. Even when both are correct (their difference is caused by different reference frames), this is confusing. To compensate, we add a new type `other` which summarizes all these queries, causing the two reference frames to be identical.
=> Add others section to upstream servers pie chart

src/datastructure.c, src/regex.c, test/test_suite.bats
---
Prints details about parsed Pi-hole regex extensions changing the effect of regular expressions.
Examples:
```
./pihole-FTL regex-test "f" 'f;querytype=AAAA'
[i] Compiling regex filter...
Compiled regex filter in 0.646 msec
Checking domain...
f;querytype=AAAA matches
Hint: This regex matches only type AAAA queries   <-----------
Time: 0.449 msec
```
```
./pihole-FTL regex-test "f" 'f;querytype=!TXT'
[i] Compiling regex filter...
Compiled regex filter in 0.646 msec
Checking domain...
f;querytype=!TXT matches
Hint: This regex never matches type TXT queries   <-----------
Time: 0.449 msec
```
```
./pihole-FTL regex-test "f" 'g;invert'
[i] Compiling regex filter...
Compiled regex …
```
=> Print more details in CLI regex-test

src/database/common.c, src/database/query-table.c, src/database/query-table.h, src/datastructure.h, test/test_suite.bats
---
When restarting FTL, it imports history from the database to repopulate the history. So far, this was only possible with a reduced set of variables to keep the database from growing forever. Recent database optimizations https://github.com/pi-hole/FTL/pull/1255 reduced the database size significantly allowing us to store more data in the database.
This PR adds storing all the details necessary for the query log so a restart goes (almost) invisible and without any data loss.
*) almost because some queries may not have been completed due to the forced restart and according service interruption.
=> Keep Query Log details across FTL restart

src/database/query-table.c
---
The `query->reply_time` variable serves two purposes: (1) When sending a query upstream, we store the current time in this field. (2) When the reply arrives, we compute the difference and store it in the same field. We memorize the transition from (1) to (2) by setting the flag `query->flags.response_calculated` to `true`.
Currently (broken in `development`, not in `master`), we store the reply_time field unconditionally, hence, for a few queries which are still being processed upstream at restart, we store the real time instead of the response. FTL incorrectly interprets the (homogeneous!) timestamp as difference and telly you the query needed quadrillions of milliseconds to …
=> Prevent excessive reply times in the Query Log after restarting

src/datastructure.c, src/datastructure.h
2
---
The function findDomainID() is called a lot and contains a simple test to avoid
further iteration and more expensive calls within.  This commit improves the
performance overall by optimizing the simple test to match more frequently and
perform the actual comparison quicker too.
The original code will try a quick match on the first char of the domain before
continuing, which from my testing actually appears to match more regularly
than expected, and therefor, continue with more …
=> perf improvements for findDomainID()

src/api/api.c, test/test_suite.bats
---
Renames the Upstream server name for blocked queries from "blocklist" to "blocked".
The term "blocklist" was omitted in v5 by "adlist" but this would still not be comprehensively enough. This special upstream server includes queries blocked by gravity, regex or domainlist. Therefore I suggest to just name it "blocked".
Fixes https://github.com/pi-hole/AdminLTE/issues/1468
Accompanied by https://github.com/pi-hole/AdminLTE/pull/2119
=> Rename upstream 'blocklist' => 'blocked' and 'cache' => 'cached'

src/api/api.c
---
Fix the reference using in the `Upstream Servers` pie chart. This chart shows how many queries are being sent to the respective destinations. We recently introduced a special category "other" that summarizes everything which does not fall into one of the available categories (like local SERVFAIL). The bug is that we have recently seen reports for *negative* other shares. This is caused by a wrong reference being used. As Pi-hole is periodically sending one and the same query to multiple upstream servers to probe which one is the fastest. This may cause five queries for only one "real" query. You see where this is leading...
The bugfix simply changes the reference frame from "how …
=> Fix negative "others" in Upstream Servers pie chart

src/database/shell.c, src/database/sqlite3.h
---
No. 1 from the changelog below is very interesting as it allows to store and retrieve advanced content (such as arrays) in the database conveniently. We'll likely be using this a lot after giving it some time to mature. Some examples:
```
'{"a":2,"c":[4,5,{"f":7}]}'   -> '$'          result is:   '{"a":2,"c":[4,5,{"f":7}]}'
'{"a":2,"c":[4,5,{"f":7}]}'   -> '$.c'        result is:   '[4,5,{"f":7}]'
'{"a":2,"c":[4,5,{"f":7}]}'   -> 'c'          result is:   '[4,5,{"f":7}]'
'{"a":2,"c":[4,5,{"f":7}]}'   -> '$.c[2]'     result is:   '{"f":7}'
'{"a":2,"c":[4,5,{"f":7}]}'   -> '$.c[2].f'   result is:   '7'
'{"a":2,"c":[4,5],"f":7}'     -> '$.c[#-1]'   result is:   '5' …
```
=> Update SQLite to v3.38.0

src/gc.c
**How familiar are you with the codebase?:** 2
---
This hard-coded GCinterval value makes any change to the macro defining the GCinterval ineffective
when the GC runs.
For e.g., if I reduce the GC from once an hour to once every 3 minutes, the GC runs every 3 minutes,
but the mintime is set to the start of the next hour, which wipes everything from the overTime data.
I believe that this change is safe and can be merged and shipped to existing users because the
GCinterval value is not configurable and users who don't build the …
=>  Replace reference to hard-coded default GCinterval value

src/shmem.c
---
When FTL encounters invalid characters within a query, it will escape them with `~`.
From the logging it was not clear which character was the replacement. This PR makes the logging more precise.
Example:
```
[2022-03-09 06:37:56.649 528M] INFO: FTL escaped 1 characters in "150.109.179.161Æz¡hÌz¡~ob¡"
[2022-03-09 06:37:56.676 528M] INFO: FTL escaped 1 characters in "150.109.179.161Æz¡hÌz¡~ob¡"
[2022-03-09 06:37:56.701 528M] INFO: FTL escaped 1 characters in "150.109.179.161Æz¡hÌz¡~ob¡"
[2022-03-09 06:37:56.719 528M] INFO: FTL escaped 1 characters in "150.109.179.161Æz¡hÌz¡~ob¡"
```
See this discourse thread: …
=> Be more precise about escaping invalid characters in queries

src/database/shell.c, src/database/sqlite3.h
---
This is a bugfix release.
CHANGELOG
1. Fix problems with the new Bloom filter optimization that might cause some obscure queries to get an incorrect answer. 
2. Fix the [localtime modifier](https://sqlite.org/lang_datefunc.html#localtime) of the [date and time functions](https://sqlite.org/lang_datefunc.html) so that it preserves fractional seconds. 
3. Fix the [`sqlite_offset` SQL function](https://sqlite.org/lang_corefunc.html#sqlite_offset) so that it works correctly even in corner cases such as when the argument is a virtual column or the column of a view. 
4. Fix [row value `IN` operator](https://sqlite.org/rowvalue.html#rvinop) constraints on [virtual …
=> Update SQLite to 3.38.1

.github/dco.yml, src/static_assert.h
**How familiar are you with the codebase?:** 3 (I looked only at what was required to pass the build on mips).
---
Compiling FTL on MIPS platform would fail with the following error (repeated multiple times).
```
/path/to/FTL/src/database/../shmem.h:57:41: error: expected declaration specifiers or ‘...’ before numeric constant
57 | ASSERT_SIZEOF(countersStruct, 240, 240, 240);
```
This error originates from `static_assert.h`, where there are no definition of `ASSERT_SIZEOF` and `STATIC_ASSERT` for the mips architecture.
This PR …
=> Added support for compilation on MIPS platform

src/database/shell.c, src/database/sqlite3.h
---
CHANGELOG:
1. Fix another user-discovered problem with the new Bloom filter optimization that might cause an incorrect answer when doing a `LEFT JOIN` with a `WHERE` clause constraint that says that one of the columns on the right table of the `LEFT JOIN` is `NULL`. See [forum thread 031e262a89b6a9d2](https://sqlite.org/forum/forumpost/031e262a89b6a9d2). 
2. Other minor patches. See the [timeline](https://sqlite.org/src/timeline?from=branch-3.38&to=version-3.38.1) for details.
=> Update SQLite to v3.38.2

src/overTime.c
**How familiar are you with the codebase?:** 2
---
initOverTime calculate's the last slot timestamp with the assumption that `OVERTIME_INTERVAL` will
allow atleast `OVERTIME_SLOTS` number of slots between now and the last slot in the current
hour. This leads it to calculate the timestamp of the last slot, and then assign timestamps to each
slot counting down from that timestamp.
This logic is not compatible with changes in the OVERTIME_INTERVAL and the MAXLOGAGE variables. Here is a demonstration of a case where this can be shown …
=> Fix initOverTime's calculation of last slot timestamp

.github/workflows/stale.yml
---
Internal housekeeping. Will become effective once this is merged and the next FTL version is released. I see no pressing need to merge this straight to `master`. This is a 1:1 copy of [pi-hole/docker-pi-hole//.github/workflows/stale.yml](https://github.com/pi-hole/docker-pi-hole/blob/279b206cdda562836c03ea7ff88cea2d9e23b047/.github/workflows/stale.yml).
=> Add stale bot to FTL repo

src/overTime.c
---
See title, fixes a logic quirk introduced in #1312. `master` isn't affected.
=> Fix overtime computation logic broken in PR #1312

src/procps.c
---
Reduce allocated memory when determining process names. This possible buffer overflow by one byte (which should, however, be impossible to exploit). Thanks to Raymond Weber for pointing this out!
=> Fix for theoretical one byte buffer overflow

src/dnsmasq_interface.c
---
Log "Forcing next reply to ..." only when DEBUG_QUERIES is enabled to avoid log flooding. Fixes #1339
=> Log reply forcing only in DEBUG_QUERIES mode

src/database/shell.c, src/database/sqlite3.h
---
Changelog
1. Fix a case of the query planner be overly aggressive with optimizing automatic-index and Bloom-filter construction, using inappropriate ON clause terms to restrict the size of the automatic-index or Bloom filter, and resulting in missing rows in the output. [Forum thread 0d3200f4f3bcd3a3](https://sqlite.org/forum/forumpost/0d3200f4f3bcd3a3). 
2. Other minor patches. See the [timeline](https://sqlite.org/src/timeline?from=branch-3.38&to=version-3.38.2) for details.
=> Update SQLite to v3.38.3

src/database/shell.c, src/database/sqlite3.h
---
**CHANGELOG**
**Additional changes in version 3.38.4 (2022-05-04):**
1.  Fix a byte-code problem in the Bloom filter pull-down optimization added by release 3.38.0 in which an error in the byte code causes the byte code engine to enter an infinite loop when the pull-down optimization encounters a NULL key. [Forum thread 2482b32700384a0f](https://sqlite.org/forum/forumpost/2482b32700384a0f).
2.  Other minor patches. See the [timeline](https://sqlite.org/src/timeline?p=branch-3.38&bt=version-3.38.3) for details.
**Additional changes in version 3.38.5 (2022-05-06):**
1.  Fix [a blunder](https://sqlite.org/news.html#2022-05-06) in the [CLI](https://sqlite.org/cli.html) of the 3.38.4 …
=> Update SQLite to v3.38.5

src/FTL.h, src/api/api.c, src/dnsmasq_interface.c, src/gc.c, src/overTime.c
---
The current version of FTL tries to be clever when returning overtime data and returns *trimmed* content, i.e., if there is nothing before 9am and nothing after 11am, it returns only thee two hours of data instead of a full 24 hours window. While looking at what caused https://github.com/pi-hole/FTL/issues/1335, I realized that this may be too much hand-holding and may actually even be confusing because it starts from super-wide bars (new installed and newly Initialized FTL database) progressing slowly to the well-known narrow bars after 24 hours.
This PR removes the "smart" reduction of the reported time span and ensures we always return all overtime data when requested. Even …
=> Always return full overTime data

src/api/api.c
---
The number of queries we are computing percentages against can be larger than the total number of queries. This can, e.g., happen when all-servers is in use as this generates more than one upstream query for every processed downstream query.
Fixes #1348
=> Fix forward percentages with all-servers

src/config.c
---
The current default is in conflict with the description in https://github.com/pi-hole/FTL/pull/1156 which says we use `DROP` as the default. This is changed here.
=> Make REPLY_WHEN_BUSY=DROP the new default (was ALLOW)

src/api/socket.c, src/daemon.c
---
This PR tries to remove the PID file during shutdown. We still empty the file above to ensure it is at least empty when it cannot be removed. because removing files on Linux is actually `unlink`ing them. If any processes still have the file open, it will remain in existence until the last file descriptor referring to it is closed.
=> Remove PID and PORT file during shutdown

src/FTL.h, src/daemon.c
---
Apply `DELAY_STARTUP` only when the system is still booting. The amount of time we consider a system still booting is a compile-time constant. It defaults to 60 seconds.
=> DELAY_STARTUP only when booting

src/api/api.c, src/api/api.h, src/api/request.c, src/log.c, test/test_suite.bats
---
Adds a bit of network information to be used in [PADD](https://github.com/pi-hole/PADD).
```
$ echo ">interfaces" | ncat 127.0.0.1 4711
enp2s0 UP 1000 3.4GB 5.1GB
lo UP -1 54.4MB 54.4MB
docker0 DOWN -1 0.0B 0.0B
wg0 UP -1 855.6MB 137.4MB
sum UP 0 4.3GB 5.3GB
---EOM---
```
Column definitions are:
1. Interface name
2. UP/DOWN status
3. Link speed in MBit/s (-1 means "Not available" (like link down) or "Not applicable" (like virtual interface))
4. TX bytes
5. RX bytes
The default interface (the one connected to the (favorite) gateway) will always be the first one so PADD can just `head -n1` it. The `sum` will always be the last one - even if you have (for whatever reason) an …
=> Add interface info for PADD

.github/workflows/stale.yml
Adds `Bug:Confirmed` and `Bugfix in progress` to `exempt-issue-labels` of the stale action. Those two labels are used quite regularly and should prevent issues from going stale.
**Target: Master branch.**
=> Stale exempt

.github/workflows/stale.yml
- **What does this PR aim to accomplish?:**
Github recently added the `issue-closed-reason` feature (https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/), which can be `complete` and `not-planned`. The latter is meant, among others, for `stale`. 
This PR https://github.com/actions/stale/pull/764 added the option `close-issue-stale` for the GH action `stale` to allow setting the `issue-closed-reason`.
This PR adds `close-issue-stale: not_planned` to our action.
**Target: master branch**
--- …
=> Add stale-issue-reason: not-planned

src/database/shell.c, src/database/sqlite3.h
---
1. Add (long overdue) support for [`RIGHT` and `FULL OUTER JOIN`](https://sqlite.org/lang_select.html#rjoin). 
2. Add new binary comparison operators [`IS NOT DISTINCT FROM`](https://sqlite.org/lang_expr.html#isdf) and [`IS DISTINCT FROM`](https://sqlite.org/lang_expr.html#isdf) that are equivalent to IS and IS NOT, respective, for compatibility with PostgreSQL and SQL standards. 
3. Add a new return code (value "3") from the [`sqlite3_vtab_distinct()`](https://sqlite.org/c3ref/vtab_distinct.html) interface that indicates a query that has both `DISTINCT` and `ORDER BY` clauses. 
4. Added the [`sqlite3_db_name()`](https://sqlite.org/c3ref/db_name.html) interface. 
5. The unix os …
=> Update embedded SQLite3 engine to 3.39.0

.github/workflows/build.yml
Don't run built workflow on dependabot PRs and pushes.
**Target: master branch**
=> Do not run built workflow on dependabot pushes and PRs

build.sh
---
Use `cmake --install` instead of `make install` to only copy the binary to its destination instead of running a second compilation when installing. The latter was caused because the scripts generated a new version (compilation timestamp) when installing so the binary had to be regenerated.
=> Use cmake --install . instead of make install

.github/workflows/stale.yml
Do not run `stale` workflow once an hour, but once a day (randomly picked 8:00).
=> Run stale workflow at 8:00 once per day
